### ISSUE TITLE
mbedTLS support on Linux platform

### ISSUE THREAD

**Issue by JeremieFiniel** [Azure/azure-iot-sdk-c#772] opened 2018-12-14 16:46 UTC
- **OS and version used:** Ubuntu 18.04 

- **SDK version used:**  1.2.12 

Hello,
We are currently using the SDK on a Linux platform, thus using the default `openSSL` adapter for the TLS communication.
We are trying to move from `openSSL` adapter to the `mbedTLS` one.
Currently, the SDK adapter is only available when using `mbed` platform.
We can not use it as a replacement of `openSSL` (as we can use `wolfSSL`) for Linux/Windows platform.

We made a PoC that is available on our `EcoStruxure` forks of both SDK and c-utility, under branches [EcoStruxure/azure-c-shared-utility](https://github.com/EcoStruxure/azure-c-shared-utility/tree/add_mbedtls_support) and [EcoStruxure/azure-iot-sdk-c](https://github.com/EcoStruxure/azure-iot-sdk-c/tree/add_mbedtls_support).

Is the ability to use `mbedTLS` as TLS layer is something planned or interesting for you?
We are willing to work on the integration if this can be eventually integrated in the SDK.

We are currently facing some issue in our current implementation.
While using the `tlsio_mbedtls` adapter with `compact_http` and berkeley sockets work great (in the c-utility),
the integration within the SDK with `MQTT` and `websocket` triggers a segmentation fault (in the remote_monitoring_client sample).

We suspect a NULL context called in complete_send_frame from web socket client. Can you help us to investigate on this?

Best regards

**Comment by alexmrtn** [comment] 2019-01-14 13:52
Hi,

Just some more input for this: I did a few modification on Jeremie's code and now we were able to connect to the iothub using mbedTLS as TLS layer in network stack. We had to change the tlsio_mbedtls_close function in order to have a similar implementation as in other tls layer (openssl, wolfssl and schannel). the change is still available in a branch in our [Ecostruxure mirror of the c-utility](https://github.com/EcoStruxure/azure-c-shared-utility/tree/add_mbedtls_support). 

Here the change we made:
```
@@ -588,22 +599,16 @@ int tlsio_mbedtls_close(CONCRETE_IO_HANDLE tls_io, ON_IO_CLOSE_COMPLETE on_io_cl
             tls_io_instance->tlsio_state = TLSIO_STATE_CLOSING;
             tls_io_instance->on_io_close_complete = on_io_close_complete;
             tls_io_instance->on_io_close_complete_context = callback_context;
+
             if (xio_close(tls_io_instance->socket_io,
                           on_underlying_io_close_complete_during_close, tls_io_instance) != 0)
             {
+                LogError("xio_close failed");
                 result = __FAILURE__;
             }
             else
             {
-                if (tls_io_instance->tls_status == TLS_STATE_INITIALIZED)
-                {
-                    mbedtls_ssl_close_notify(&tls_io_instance->ssl);
-                    tls_io_instance->tls_status = TLS_STATE_CLOSING;
-                }
-                else
-                {
-                    result = 0;
-                }
+                result = 0;
             }
         }
     }
```

The previous implementation of tlsio_mbedtls_close closes the underlying socket and then try to send some data to close the TLS connection (using `mbedtls_ssl_close_notify`), resulting in an error as the socket was already closed. It seems that in all other TLS implementation, the closing of the TLS connection is made by closing the underlying TCP connection. That is why we replicated this behavior.

It is normal that the TLS connections are not properly closed before the TCP connection in all TLS adapters? for instance in the tlsio_openssl adapter there is no call to `SSL_shutdown` function.

Having modified the tlsio_mbedtls.c file made the connection to the iothub work great using both MQTT and AMQP protocols. I validated using the `iothub_ll_telemetry_sample` sample. But when trying to use the web-socket version of both protocols, the connection fails. It seems that the websocket upgrade of the connection is made properly, but when sending the CONNECT packet for the MQTT protocol, we get the following error:

```
-> 18:21:02 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 192 | USERNAME: XXXXX.azure-devices.net/alexis/?api-version=2017-11-08-preview&DeviceClientType=iothubclient%2f1.2.12%20(native%3b%20Linux%3b%20x86_64) | PWD: XXXX | CLEAN: 0
Error: Time:Wed Jan  9 18:21:02 2019 File:/home/alex/Sources/azure-iot-sdk-c/c-utility/src/uws_client.c Func:on_underlying_io_send_complete Line:1897 Failing getting singlylinkedlist_item_get_value on_underlying_io_send_complete
```

From here, I'm not sure if the problem comes from the WS client implementation or if the problem comes from the mbedtls adapter.


@jebrando Is this is something you still want to put in your investigation list? Let us know if we can have some help on this!

Best,

Alexis.

**Comment by jebrando** [comment] 2019-02-11 18:29
We have made some changes to the mbedtls library code and this issue should be resolved.  If you notice any more error please let us know.

**Comment by az-iot-builder-01** [comment] 2019-02-11 18:29
@JeremieFiniel, @jebrando, @alexmrtn, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed** 2019-02-11 18:29 UTC
Labels: enhancement

**Comment by alexmrtn** [comment] 2019-02-12 11:08
Hi @jebrando , this is awesome! The issue is indeed solved and I was able to use mbedTLS as TLS layer. I made 2 PR in both c-utility and sdk:
- https://github.com/Azure/azure-c-shared-utility/pull/270
- https://github.com/Azure/azure-iot-sdk-c/pull/862

Best,
Alexis Martin
