### ISSUE TITLE
Serializer APIs & DeviceTwin evolution

### ISSUE THREAD

**Issue by jurko** [Azure/azure-iot-sdk-c#374] opened 2018-02-12 07:53 UTC
Hi,

We'd like to confirm the behavior of the Serializer APIs if the declared desired properties (DECLARE_MODEL & friends) do not match with what is received from IoTHub, for example in the case of a firmware update. Our investigations make us think that this is something that seems to work as we are expecting (with some improvements), but we'd like to confirm the implementation is intentional and the use-case is supported.

- ability to report properties even in case of failure to receive/match desired
- robustness of the api implementation and the ability to recover once the desired properties are modified in IoTHub
- how to detect this situation, ie some desired properties do not parse and match
- [minor] ability to receive desired properties that the serializer is able to match

Thanks,
Juraj

Following is an example of log in case of a mismatch between what is declared in the code and IoTHub desired properties:
```[12:55:33.135][DEBUG]{mqtt_client.c:267}                -> 13:55:33 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 192 | USERNAME: ....................../api-version=2016-11-14&DeviceClientType=iothubclient%2f1.1.31%20(native%3b%20Linux%3b%20x86_64) | PWD: XXXX | CLEAN: 0
[12:55:33.494][DEBUG]{mqtt_client.c:294}                <- 13:55:33 CONNACK | SESSION_PRESENT: true | RETURN_CODE: 0x0
[12:55:33.497][DEBUG]{mqtt_client.c:267}                -> 13:55:33 SUBSCRIBE | PACKET_ID: 2 | TOPIC_NAME: devices/device01/messages/devicebound/# | QOS: 1 | TOPIC_NAME: $iothub/twin/res/# | QOS: 0 | TOPIC_NAME: $iothub/twin/PATCH/properties/desired/# | QOS: 0 | TOPIC_NAME: $iothub/methods/POST/# | QOS: 0
[12:55:33.501][DEBUG]{mqtt_client.c:267}                -> 13:55:33 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE | TOPIC_NAME: $iothub/twin/PATCH/properties/reported/?$rid=3 | PAYLOAD_LEN: 764
[12:55:33.653][DEBUG]{mqtt_client.c:294}                <- 13:55:33 SUBACK | PACKET_ID: 2 | RETURN_CODE: 1 | RETURN_CODE: 0 | RETURN_CODE: 0 | RETURN_CODE: 0
[12:55:33.656][DEBUG]{mqtt_client.c:267}                -> 13:55:33 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE | TOPIC_NAME: $iothub/twin/GET/?$rid=4
[12:55:33.725][DEBUG]{mqtt_client.c:294}                <- 13:55:33 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE = 0x00 | TOPIC_NAME: $iothub/twin/res/204/?$rid=3&$version=26 | PAYLOAD_LEN: 0
[12:55:33.725][INFO ]{iothubAgent_dm.c:29}              Reported properties delivered with status_code = 204
[12:55:33.765][DEBUG]{mqtt_client.c:294}                <- 13:55:33 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE = 0x00 | TOPIC_NAME: $iothub/twin/res/200/?$rid=4 | PAYLOAD_LEN: 928
[12:55:33.765][ERROR]{commanddecoder.c:839}             INTERNAL ERROR: unexpected function return
[12:55:33.765][ERROR]{commanddecoder.c:931}             not all constituents of the JSON have been ingested
[12:55:33.765][ERROR]{commanddecoder.c:897}             failure in validateModel_vs_Multitree
[12:55:33.765][ERROR]{commanddecoder.c:931}             not all constituents of the JSON have been ingested
[12:55:33.765][ERROR]{iotdevice.c:440}                  failure in CommandDecoder_IngestDesiredProperties
[12:55:33.765][ERROR]{codefirst.c:1612}                 failure in Device_IngestDesiredProperties
[12:55:33.765][ERROR]{serializer_devicetwin.h:38}       failure ingesting desired properties
```

**Comment by alexmrtn** [comment] 2018-02-15 17:31
Hi,

Here some details about the behavior we observed when device twin are not synchronized: 

- Reported:
  - Change/New reported name on Device => create a new reported on the Hub (but can't clean old reported on Hub side)
- Desired: 
  - Desired on Device but not on Hub => No impact
  - Desired on the Hub but not on the Device => triggers error but other desired still working
- Direct Methods:
  - Method not implemented on Device => `failure in EXECUTE_METHOD` error log but other Methods still working

**Comment by jspaith** [comment] 2018-02-16 20:04
@alexmrtn  - All of this is by design.

* For reported, this is expected.  We leave the old values on the hub by default.  You can remove them if you send "value:null" in the json, but the serializer doesn't have this ability.  If you *really* cared you could write some sort of post-update migration utility that would send up the null'd values to the twin (using the raw C SDK, not serializer).  
* For desired, this behavior is as expected.
* For direct method, again as expected since there's nothing to accept the call.

Any concerns with any of this?

**Comment by alexmrtn** [comment] 2018-02-19 12:36
Hi @jspaith 

Thanks for the confirmation! We are now able to build our solution to support model changes based on this behavior of the serializer.

**Comment by jspaith** [comment] 2018-02-20 16:53
Cool.  I'm going to close this out based on this, but as always by all means re-open or create a new issue if there's further concerns.

**Closed by jspaith** 2018-02-20 16:53 UTC
Labels: investigation-required
