### ISSUE TITLE
Message Tracking ID big Number 1960959496 crash 

### ISSUE THREAD

**Issue by sarangkalbande** [Azure/azure-iot-sdk-c#165] opened 2017-06-22 08:56 UTC
# Description of the issue:
 Send Confirmation coming with Big Number Tracking ID 1960959496 crash.

I kept SDK Running with full load for 3 days and suddenly Application got crashed when I saw the crash log,I got Message Tracking ID as 1960959496 for send confirmation.
why the ID Coming is huge.While sending the message I am taking care of tracking ID should not cross 65535 max but still sometimes send confirmation is coming with huge number.

# Code sample exhibiting the issue:
Confirmation[885] received for message tracking id =1960959496 with result = IOTHUB_CLIENT_CONFIRMATION_OK

**Comment by tameraw** [comment] 2017-06-27 17:51
@sarangkalbande - Thanks for filing this issue. We'll investigate it.

**Comment by chrit-msft** [comment] 2017-06-27 18:43
@sarangkalbande I have a few questions for you so I can continue the investigation.  
1) Have you tried reproducing this issue with the SDK samples?
2) What platform are you seeing this issue on?
3) What protocol are you using?

**Comment by sarangkalbande** [comment] 2017-07-01 19:01
@chrit-msft 
1.Have you tried reproducing this issue with the SDK samples?
Yes Actually I have integrated this SDK with our application and It was working pretty well till I recently upgraded SDK to 1.1.16 

2.What platform are you seeing this issue on?
Ubuntu 14.04 and Core is ARM Cortex A9

3.What protocol are you using?
MQTT

This happens very rarely and difficult to reproduce from my end again till it occurs again automatically.

But I have seen it when you run SDK will full load sending multiple messages very often.

**Comment by chrit-msft** [comment] 2017-07-07 16:12
@sarangkalbande I have been unable to reproduce this issue so far.  Here is what I am using:
1) C SDK 1.1.18
2) Ubuntu 16.04 Intel Core i7-4790
3) AMQP

I will switch over to MQTT to see if I am able to reproduce this issue.

**Comment by chrit-msft** [comment] 2017-07-12 18:09
@sarangkalbande would it be possible to see the code you are using to reproduce this?

**Comment by chrit-msft** [comment] 2017-08-03 20:32
@sarangkalbande I am unable to reproduce this failure.  I will be closing this GitHub issue now.  If you are able to reproduce the issue please open a new thread with the source code.

**Closed by chrit-msft** 2017-08-03 20:32 UTC
Labels: CSS, investigation-required

**Comment by sarangkalbande** [comment] 2017-08-18 09:39
Hi Chrit-msft,
I was able to reproduce this issue again.
Here it goes as below.
[1]When we try to send message with same tracking id 2-3 times without getting Send confirmation ACK
then very last time when we get send confirmation ACK  we get wrong tracking id.

Actually In my application I have assigned dedicated trackIds to differentiate among messages. 
I have never faced this issue with Ethernet or wifi since we used to get ACK very quickly but with cellular connectivity[which is not very reliable and delays confirmation ACK] I started facing this issue like suppose when I send message-1 with track id as 12 and before getting send confirmation ack I sent message-2 with same track ID 12 and when connectivity comes up and I get send confirmation ACK it comes as huge number as said earlier and crash.

Not sure how you can simulate No ack scenario 
But I have below questions for you.
[1]If I send message with same track ID multiple times how would SDK make sure of its tracking number 
since queue has different messages with same track IDS?
