### ISSUE TITLE
Extra product info not being included in Client Version for AMQP

### ISSUE THREAD

**Issue by jadeiceman** [Azure/azure-iot-sdk-c#1142] opened 2019-08-23 18:28 UTC
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**

Ubuntu 18.04.1 LTS

**SDK Version (Please Give Commit SHA if Manually Compiling)**

azure-iot-sdk-c @ 4996100

**Protocol**

AMQP

**Describe the Bug**

When using SetOption to set OPTION_PRODUCT_INFO, the product info is not included in the Client Version.  I'm using the version of the C SDK with fix https://github.com/Azure/azure-iot-sdk-c/pull/1056

Console log (lines with <code>>>>>></code> are debug statements added to the C SDK)
```
06-11-08 PM [00042932] [00036988] ---- ---- Connecting ---- ----
06-11-08 PM [00042932] [00036988] Microsoft::Azure::DeviceManagement::Client::AzureDMClient::InitializeIoTHubConnection
06-11-08 PM [00042932] [00036988] Microsoft::Azure::DeviceManagement::Client::AzureDMClient::GetConnectionString
06-11-08 PM [00042932] [00036988] Attempting to read the connection string from configuration file...
06-11-08 PM [00042932] [00036988] Found connection string...
06-11-08 PM [00042932] [00036988] Using device twin...
>>>>>>>>>> make_product_info: iothubclient/1.3.4 (native; WindowsProduct:0x00000004 6.2; x64; {14B21B04-6286-473F-AE2E-96A32C31AF1C})
>>>>>>>>>> clone_device_config
>>>>>>>>>> prod_info_cb(prod_info_ctx)): iothubclient/1.3.4 (native; WindowsProduct:0x00000004 6.2; x64; {14B21B04-6286-473F-AE2E-96A32C31AF1C})
>>>>>>>>>> make_product_info: device-agent iothubclient/1.3.4 (native; WindowsProduct:0x00000004 6.2; x64; {14B21B04-6286-473F-AE2E-96A32C31AF1C})
06-11-08 PM [00042932] [00036988] Device client product info has been set!
06-11-08 PM [00042932] [00036988] Microsoft::Azure::DeviceManagement::Client::AzureRawHost::InitializeDeviceConnection
06-11-08 PM [00042932] [00036988] Microsoft::Azure::DeviceManagement::Client::AzureRawHost::EnableIoTHubNotifications
06-11-08 PM [00042932] [00036988] Microsoft::Azure::DeviceManagement::Client::AzureRawHost::SignalConnectionStatusChanged
…
06-11-09 PM [00042932] [00036988] Microsoft::Azure::DeviceManagement::Client::OutOfProcPluginBinaryProxy::CacheHandlerState
<- [ATTACH]* {link-snd-jochi-pnp-08b0d7c9-b3dd-420c-b0fc-481e8730a220,2,true,0,NULL,* {link-snd-jochi-pnp-08b0d7c9-b3dd-420c-b0fc-481e8730a220-source,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL},* {amqps://IoTSelfhostHub.azure-devices.net/devices/jochi-pnp/messages/events,NULL,NULL,NULL,NULL,NULL,NULL},NULL,NULL,NULL,1048576,NULL,NULL,{[com.microsoft:client-version:device-agent iothubclient/1.3.4 (native; WindowsProduct:0x00000004 6.2; x64; {14B21B04-6286-473F-AE2E-96A32C31AF1C})]}}
<- [FLOW]* {1,5000,2,4294967295,2,0,1000,0,NULL,false,NULL}
06-11-09 PM [00042932] [00036988] Id   : GetInstalledUwpAppsCmd
06-11-09 PM [00042932] [00036988] Value: {
        "interfaceVersion" : "1.0.0",
        "tags" : "",
        "type" : "raw"
}

<- [ATTACH]* {link-snd-jochi-pnp-8053dfb0-4892-40a7-9385-4dbf343880c6,3,true,1,0,* {link-snd-jochi-pnp-8053dfb0-4892-40a7-9385-4dbf343880c6-source,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL},* {amqps://IoTSelfhostHub.azure-devices.net/devices/jochi-pnp/twin,NULL,NULL,NULL,NULL,NULL,NULL},NULL,NULL,NULL,1048576,NULL,NULL,{[com.microsoft:client-version:iothubclient/1.3.4 (native; WindowsProduct:0x00000004 6.2; x64; {14B21B04-6286-473F-AE2E-96A32C31AF1C})],[com.microsoft:channel-correlation-id:twin:0e339f45-3773-4511-bdc7-8c0b910f1a97],[com.microsoft:api-version:2016-11-14]}}
<- [FLOW]* {1,5000,2,4294967295,3,0,1000,0,NULL,false,NULL}
-> [ATTACH]* {link-rcv-jochi-pnp-1222c633-fbec-438c-88bd-192b67dfb33c,4,true,0,0,* {amqps://IoTSelfhostHub.azure-devices.net/devices/jochi-pnp/twin},* {link-rcv-jochi-pnp-1222c633-fbec-438c-88bd-192b67dfb33c-target},NULL,NULL,NULL,18446744073709551615,NULL,NULL,{[com.microsoft:client-version:iothubclient/1.3.4 (native; WindowsProduct:0x00000004 6.2; x64; {14B21B04-6286-473F-AE2E-96A32C31AF1C})],[com.microsoft:channel-correlation-id:twin:0e339f45-3773-4511-bdc7-8c0b910f1a97],[com.microsoft:api-version:2016-11-14]}}
06-11-09 PM [00042932] [00036988] Microsoft::Azure::DeviceManagement::Client::OutOfProcPluginBinaryProxy::CacheHandlerState
06-11-09 PM [00042932] [00036988] Id   : ManageAppLifeCycleCmd
06-11-09 PM [00042932] [00036988] Value: {
        "interfaceVersion" : "1.0.0",
        "tags" : "",
        "type" : "raw"
}
```

ClientVersion in the backend shows the string without the extra "device-agent" string that was added.

**Comment by danewalton** [comment] 2019-08-28 23:00
Hi @jadeiceman. I just ran the [iothub_ll_telemetry_sample](https://github.com/Azure/azure-iot-sdk-c/tree/master/iothub_client/samples/iothub_ll_telemetry_sample) with AMQP and successfully added the product info. Can you possibly give me some more information about when/where you are setting the option?

**Comment by danewalton** [comment] 2019-08-29 00:02
Actually now that I look at this further it seems to be attaching it to the message (for your pasted output and my repro) but not the twin. I will look into this further and get to you here.

**Comment by danewalton** [comment] 2019-08-29 16:31
@jadeiceman I just confirmed that we do seem to have a bug here. I will look into a fix and report back here when I have that lined up. Thanks for bringing it up!

**Comment by danewalton** [comment] 2019-09-13 21:22
PR has been opened.
https://github.com/Azure/azure-iot-sdk-c/pull/1176

**Comment by danewalton** [comment] 2019-09-17 02:25
PR has been merged. Thanks again for pointing this out @jadeiceman.

**Comment by az-iot-builder-01** [comment] 2019-09-17 02:26
@danewalton, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed by danewalton** 2019-09-17 02:25 UTC
Labels: bug
