### ISSUE TITLE
CMake command for linking libiothub_client.so fails

### ISSUE THREAD

**Issue by bb-dsa** [Azure/azure-iot-sdk-c#505] opened 2018-05-30 14:26 UTC
After cloning the SDK with 
   `git clone -b 2018-05-04 --recursive https://github.com/Azure/azure-iot-sdk-c.git`
the step for linking libiothub_client.so fails ob Debian Jessie with the following error:
```
[ 72%] Linking C shared library libiothub_client.so
cd /tmp/azure-iot-sdk-c/build/iothub_client && /opt/cmake-3.10.1-Linux-x86_64/bin/cmake -E cmake_link_script CMakeFiles/iothub_client_dll.dir/link.txt --verbose=1
/opt/cmake-3.10.1-Linux-x86_64/bin/cmake -E __create_def CMakeFiles/iothub_client_dll.dir/exports.def CMakeFiles/iothub_client_dll.dir/exports.def.objs
CMake Error: cmake version 3.10.1
....
```

**Comment by bb-dsa** [comment] 2018-05-30 14:31
Compilation is performed in a Docker container with the following instruction in the Dockerfile:
```
	git clone -b 2018-05-04 --recursive https://github.com/Azure/azure-iot-sdk-c.git && \
	cd azure-iot-sdk-c && \
	mkdir build  && \
	cd build && \
	cmake -Dbuild_as_dynamic=ON -Dskip_samples=ON -Duse_prov_client=ON .. && \
	make all install 
```
The now non-existing branch `release_2018_04_02 `compiled successfully with this instruction,.

**Comment by jebrando** [comment] 2018-05-31 00:27
@bb-dsa I am looking into this error.  Not sure why cmake is throwing it, but I'll investigate.

**Comment by lakshmisivareddy** [comment] 2018-06-01 07:37
Hi @bb-dsa  i tried in Ubantu 14.04 i am able to compile with out any problem

**Comment by jebrando** [comment] 2018-06-01 15:34
@bb-dsa There seems to be a cmake issue with version 10 and higher.  We are looking into this and try to find an resolution.

**Comment by pboettch** [comment] 2018-07-02 09:47
I bisected the problem down this commit (42a5fc9388f44b96bc829ebad7bdab11d304006a):

```
42a5fc9388f44b96bc829ebad7bdab11d304006a is the first bad commit
commit 42a5fc9388f44b96bc829ebad7bdab11d304006a
Author: Jelani <jelani.brandon@microsoft.com>
Date:   Mon Apr 30 17:30:27 2018 +0000

    Update cmake to handle 2 def files
```

**Comment by pboettch** [comment] 2018-07-02 10:02
` __create_def` is not a cmake command allowed with -E in Linux. Maybe it was before 3.10, but it's no longer.

It seems cmake learned how to handle .def-files and considers them as sources now even in Linux. (I don't really know what a .def-file is).

**Comment by pboettch** [comment] 2018-07-02 10:08
The problem is triggered by having two .def-files in the list.

**Comment by pboettch** [comment] 2018-07-10 10:05
Issue is no more present with CMake 3.12.0-rc1. It seems to be fixed with https://gitlab.kitware.com/cmake/cmake/commit/1ac042aa67c0e0ab531cd38977cb2f65fd96ed4b

. This bug-fix is not included in 3.11.3 .

**Comment by jspaith** [comment] 2018-07-23 21:31
Thanks @ pboettch for the investigation here.  

I saw very similar issues building dynamic links for cmake 3.10.2 and the issue went away immediately when installing the Linux x86_64 binary distributable form https://cmake.org/download/.  

Anyone hitting this for now can bring down this updated cmake to a local directory (it exists side-by-side with apt-get installed cmake fine) and invoke this local copy until apt-get packages for updated cmake are available.

**Comment by az-iot-builder-01** [comment] 2018-07-23 21:31
@bb-dsa, @lakshmisivareddy, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/DesignPage.aspx#FormId=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu&Token=af48ed4ed02842bea21e0d3933b78fac)

**Closed** 2018-07-23 21:31 UTC
Labels: investigation-required
