### ISSUE TITLE
Use LOG() instead of printf() in the samples

### ISSUE THREAD

**Issue by vanti** [Azure/azure-iot-sdk-c#583] opened 2018-08-02 16:53 UTC
Output from examples (samples) in the Azure IoT C SDK is currently performed with direct calls to printf(). This makes it difficult to plug in a different implementation on embedded systems where the output needs to be routed differently. Based on the discussion in this [thread](https://github.com/Azure/azure-c-shared-utility/issues/170#issuecomment-409810633), vendors can define a function in the adaptation layer that would route the output of the logging facility. Could the examples be modified to use this same mechanism, ie. LOG(), instead of printf()? It would ensure all output is consistently routed in the same manner.

**Comment by jspaith** [comment] 2018-08-02 17:14
Marking as an enhancement as this is a good idea.

**Comment by jspaith** [comment] 2018-08-03 20:20
We've discussed this internally a bit and I've slept on it and we have concerns doing this.  

The problem is on other embedded systems, printf() routes directly to a serial and on Windows/Linux printf() ties into the standard CRT off to a console/file/etc.  So we need to balance clarity for a non-printf() device versus clarity for devices with printf(), where a printf() statement in code is immediately obvious whereas a LogInfo() may cause a new customer to do needless debugging.

Even though this is a good idea, we've decided that the printf() simplicity should win out.  Sorry I wrongly had you open this & then backed off.

**Comment by az-iot-builder-01** [comment] 2018-08-03 20:21
@vanti, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/DesignPage.aspx#FormId=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu&Token=af48ed4ed02842bea21e0d3933b78fac)

**Closed by jspaith** 2018-08-03 20:20 UTC
Labels: enhancement
