### ISSUE TITLE
Random timeouts waiting for CONNACK cause process crashes in iothubtransport_mqtt_common module

### ISSUE THREAD

**Issue by RivaStyle** [Azure/azure-iot-sdk-c#842] opened 2019-02-01 11:30 UTC
- **OS and version used:** Ubuntu 16.04

- **SDK version used:** 2019-01-31 (v1.2.13)

# Description of the issue:
When connecting to IoT Hub to push data, it randomly happens (after many successful attempts) that the MQTT connection times out at initialization, waiting for CONNACK.

This triggers DisconnectFromClient where the case is:
- **transport_data->mqttClientStatus** = MQTT_CLIENT_STATUS_CONNECTING
- **transport_data->isDestroyCalled** = false

Despite that **isDestroyCalled** flag, a xio_destroy is called anyway on **transport_data->xioTransport**, causing a crash.

Could it be an issue similar to #446?

# Code sample exhibiting the issue:
_iothub_client_sample_mqtt_esp8266_, put in a state machine and set to push a single message in a user-selectable time interval (between 5 minutes and 1 hour).

Modifications made:
- Added Connection Status callback: it basically quits the main do-while loop after _CONN_RETRY_NUM_ (set to 4) unsuccessful connection attempts.
```
static void ConnStatCallback(IOTHUB_CLIENT_CONNECTION_STATUS result, IOTHUB_CLIENT_CONNECTION_STATUS_REASON reason, void* userContextCallback)
{
    int* counter = (int*)userContextCallback;

    if (result == IOTHUB_CLIENT_CONNECTION_AUTHENTICATED)
    {
        IOTHUB_LOGDEBUG("Attempt %d of %d: MQTT connection established", *counter, CONN_RETRY_NUM);
    }
    else
    {
        (*counter)++;

        switch (reason)
        {
            case IOTHUB_CLIENT_CONNECTION_EXPIRED_SAS_TOKEN:
            {
                IOTHUB_LOGDEBUG("Attempt %d of %d: Id rejected because of expired SAS Token", *counter, CONN_RETRY_NUM);
            }
            break;

            case IOTHUB_CLIENT_CONNECTION_DEVICE_DISABLED:
            {
                IOTHUB_LOGDEBUG("Attempt %d of %d: Device disabled by IoT Hub", *counter, CONN_RETRY_NUM);
            }
            break;

            case IOTHUB_CLIENT_CONNECTION_BAD_CREDENTIAL:
            {
                // Bad login credentials, no need to retry again and again - exit immediately
                *counter = CONN_RETRY_NUM;
                IOTHUB_LOGDEBUG("Attempt %d of %d: Invalid Device Id or Shared Access Key", *counter, CONN_RETRY_NUM);
            }
            break;

            case IOTHUB_CLIENT_CONNECTION_RETRY_EXPIRED:
            {
                // Retry timeout set by policy has expired, exit immediately
                *counter = CONN_RETRY_NUM;
                IOTHUB_LOGDEBUG("Attempt %d of %d: Retry Policy timeout expired", *counter, CONN_RETRY_NUM);
            }
            break;

            case IOTHUB_CLIENT_CONNECTION_NO_NETWORK:
            {
                // VMU-C is not connected to a network, exit immediately
                *counter = CONN_RETRY_NUM;
                IOTHUB_LOGDEBUG("Attempt %d of %d: Network error", *counter, CONN_RETRY_NUM);
            }
            break;

            case IOTHUB_CLIENT_CONNECTION_COMMUNICATION_ERROR:
            default:
            {
                IOTHUB_LOGDEBUG("Attempt %d of %d: Unauthorized MQTT connection", *counter, CONN_RETRY_NUM);
            }
            break;
        }
    }

    IOTHUB_LOGDEBUG("ConnStat callback counter = %d, reason = %d", *counter, reason);
    if (*counter >= CONN_RETRY_NUM)
    {
        IOTHUB_LOGDEBUG("Maximum number of attempts reached, exiting IoT Hub Client");
        g_retVal = STATUSCODE_SRV_UNAV;
        g_continueRunning = false;
    }
}
```

- Modified Send Confirmation callback, so as to quit the loop after one message:
```
static void SendConfirmationCallback(IOTHUB_CLIENT_CONFIRMATION_RESULT result, void* userContextCallback)
{
    EVENT_INSTANCE* eventInstance = (EVENT_INSTANCE*)userContextCallback;
    IOTHUB_LOGDEBUG("Confirmation[%d] received for message tracking id = %zu with result = %s",
                    callbackCounter, eventInstance->messageTrackingId,
                    ENUM_TO_STRING(IOTHUB_CLIENT_CONFIRMATION_RESULT, result));

    callbackCounter++;
    IoTHubMessage_Destroy(eventInstance->messageHandle);

    // Quit after receiving last callback
    IOTHUB_LOGDEBUG("callbackCounter = %d", (int)callbackCounter);
    if (callbackCounter >= MESSAGE_COUNT)
    {
        g_continueRunning = false;
    }
}
```

# Console log of the issue:
```
2019-02-01 10:55:50  IOTHUB_DEBUG: 250 iothub_clientMQTTRun() IoTHubClient_LL_SetConnectionStatusCallback...successful.
2019-02-01 10:55:50  IOTHUB_DEBUG: 262 iothub_clientMQTTRun() IoTHubClient_LL_SetMessageCallback...successful.
2019-02-01 10:55:50  IOTHUB_DEBUG: 297 iothub_clientMQTTRun() IoTHubClient_LL_SendEventAsync accepted message [0] for transmission to IoT Hub.
-> 10:55:51 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 192 | USERNAME: smxiothub.azure-devices.net/GavazziTest-device_VMU-C/?api-version=2017-11-08-preview&DeviceClientType=iothubclient%2f1.2.13%20(native%3b%20Linux%3b%20armv5tejl) | PWD: XXXX | CLEAN: 0
Error: Time:Fri Feb  1 10:56:21 2019 File:/mnt/ssd/Progetti/uwp_workspace_photon/UWP3/userapps/public/libs/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:InitializeConnection Line:2344 mqtt_client timed out waiting for CONNACK
* crash *
sigChildHnd(): sig=17 killed taskpid=17745 
sigChildHnd(): removed taskpid=17745 from list
```

**Comment by jebrando** [comment] 2019-02-04 16:52
@RivaStyle How are you building the SDK on the ESP32, I'm looking at recreated, and I'd like to get as close to your configuration as possible.

Thanks.

**Comment by RivaStyle** [comment] 2019-02-05 10:22
(I forgot to add an information, that "build_serializer" is a custom option I added to not build the serializer module as it wasn't needed)

**Comment by jebrando** [comment] 2019-02-11 16:56
@RivaStyle (As a side note I really like that build_serializer flag, I will try to get the team to incorporate it).  I guess there are two issues here, the wait for CONNACK and the segfault.  For the CONNACK, did you lose network connectivity around this time?  It's unusual for the IoTHub to not send back a CONNACK unless the device loses it's network.

For the Segfault, do you now what communication stack you're using (tlsio_openssl, tlsio_mbedtls, tlsio_wolfssl, ...)?  I believe that there is some clue in the issue.

Thanks,
Jelani

**Comment by RivaStyle** [comment] 2019-02-11 17:04
No, when the CONNACK timeout happens I don't lose network connectivity, but it could be some kind of overload as other heavy processes are running alongside it. I'll try to disable it and have a further check.

Regarding the communication stack, it's tlsio_openssl.

Thanks,
Luca

**Comment by jitin17** [comment] 2019-02-18 07:16
@RivaStyle @jebrando I could reproduce this issue. I suspect the problem is with `InitializeConnection` function in `iothubtransport_mqtt_common.c`. `InitializeConnection` does not handle all retry actions appropriately. 

I am adding some pain points in the `InitializeConnection` function, which I think causes the crash. _(Note: This is compared against master branch)_

**Line 2331** : [View Code](https://github.com/Azure/azure-iot-sdk-c/blob/1239a173f7e590dc821bcbb243703bea2969ebc7/iothub_client/src/iothubtransport_mqtt_common.c#L2338)

I think `result = 0` is incorrect, and this is causing a crash when I add `IoTHubDeviceClient_LL_SetRetryPolicy(iotHubClientHandle, IOTHUB_CLIENT_RETRY_INTERVAL, 20)` in the application logic.

**RETRY_ACTION_RETRY_LATER retry action is not being handled**

When retry action is `RETRY_ACTION_RETRY_LATER`, the return value of `InitializeConnection` is `0`, which also results in crash. The return value when retry action is `RETRY_ACTION_RETRY_LATER` should be something other than `0`.

@jebrando Can you confirm whether this is true, and let me know if you would like me to raise a PR to resolve this issue. Thanks.

**Comment by RivaStyle** [comment] 2019-02-18 12:54
@jitin17 if you wanna check if that can intercept my case, the retry policy I'm using is `IoTHubClient_LL_SetRetryPolicy(iotHubClientHandle, IOTHUB_CLIENT_RETRY_EXPONENTIAL_BACKOFF_WITH_JITTER, 10) `.

**Comment by jitin17** [comment] 2019-02-18 13:00
@RivaStyle This is the default retry policy. And this fails because `RETRY_ACTION_RETRY_LATER` is not being handled.
This case can be handled by setting `result` as non-zero in `InitializeConnection` function of `iothubtransport_mqtt_common.c` file when retry action is `RETRY_ACTION_RETRY_LATER`. Let me know, if this works for you.

**Comment by RivaStyle** [comment] 2019-02-21 07:51
@jitin17 @jebrando  a non-zero value in case of `RETRY_ACTION_RETRY_LATER` actually prevented crashes on library side... I'm still seeing some crashes, but now it's more on my side, about how I call my push client to exit.

**Comment by jitin17** [comment] 2019-02-21 11:04
@RivaStyle I have raise a PR https://github.com/Azure/azure-iot-sdk-c/pull/875 to fix this issue.

**Comment by ewertons** [comment] 2019-03-07 19:40
Hi @RivaStyle , PR #875  has been merged.
Could you verify it fixes your issue please?

**Comment by RivaStyle** [comment] 2019-03-11 07:17
I confirm that the library, as it was cloned from Git last Friday, definitely fixes the issue.

**Comment by ewertons** [comment] 2019-03-14 18:55
Alright, thanks for confirming.
We will close this issue, but please feel free to reopen it if you would like to follow up.
Thanks,
Azure IoT SDK Team

**Comment by az-iot-builder-01** [comment] 2019-03-14 18:55
@jebrando, @RivaStyle, @ewertons, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed** 2019-03-14 18:55 UTC
Labels: investigation-required
