### ISSUE TITLE
the new version of the azure-iot-sdk-c 1.1.13 is not working with CC3200 ti rtios

### ISSUE THREAD

**Issue by kcpoduru** [Azure/azure-iot-sdk-c#125] opened 2017-05-02 21:59 UTC
Hi there! thank you for discovering and submitting an issue!

Please first tell us a little bit about the environment you're running:
I am using tirtos for cc3200 and azure iot sdk c. 

# Description of the issue:
At first there was a build problem. Because of the compiler. It was solved by using ti_cgt_tms470_5.2.9(worked).  The designated one as per the document is ti-cgt-arm_5.2.5(not working).  Later it is throwing the error as shown in the below image. But when I used different SDK which is version 1.0.12 It worked seamlessly. why is it? what are the advantages with the new version over ol
![capture](https://cloud.githubusercontent.com/assets/25354759/25641227/b116165c-2f58-11e7-89ee-1e2370123ea1.PNG)
d.

**Comment by markrad** [comment] 2017-06-13 01:17
This issue is being investigated and will be updated when more information is available.

**Comment by jensnielsen** [comment] 2017-08-14 09:32
For anyone else running into this, the problem is that c-utility/adapters/platform_stub.c is used for TIRTOS, which returns NULL from platform_get_platform_info()

Workaround to return STRING_construct("(tirtos)"); instead seems to work for me but I don't know what kind of implications this has.

**Comment by ewertons** [comment] 2017-11-09 23:23
Hi @kcpoduru , 
a fix is being reviewed and will be available on the master branch soon.

**Comment by ewertons** [comment] 2017-11-17 02:58
Fix checked in.
https://github.com/Azure/azure-c-shared-utility/commit/e16ab047db3fb553dabfe1dde96e76833ad02150
Please feel free to reopen this issue if you find necessary.

Thanks for contributing to the Azure IoT SDK.

**Closed** 2017-11-17 02:58 UTC
Labels: bug, CSS, fix checked in
