### ISSUE TITLE
Azure IOT SDK: Prov_Device_Register_Device - status not received on callback

### ISSUE THREAD

**Issue by seemamathew** [Azure/azure-iot-sdk-c#1965] opened 2021-05-19 05:23 UTC
Hi,
We are developing an C++ QT application using azure-iot-sdk -c 1.3.8 version. While keeping system for long run, we are getting PROV_DEVICE_RESULT_TRANSPORT multiple times during device provisioning.

In such situation application is retrying for connection. But once, it seems that response status is not received in call back function on 9th retry( we wait for more than 10 hrs).
Does anyone have similar experience?

Previously on one instance, we have observed a 15 minute delay for getting response for device provisioning.

Additional information

During retry application is uninitialize SDK and again initialize

For uninitialize following steps are performed:
IoTHubDeviceClient_Destroy
Prov_Device_Destroy
prov_dev_security_deinit
IoTHub_Deinit

Thanks in Advance
Seema

**Comment by seemamathew** [comment] 2021-05-20 12:21
Hi,

We are able to reproduce the issue again in low network environment.
It is observed that status of Prov_Device_Register_Device not receiving in callback even after 1 hour.

Please see trace log from issue reported environment:

m_pAzureIoTHubClientManager->Initialize completed
m_pCloudAbstractionLib->Initialize completed going for provisioning.

PROV_DEVICE_RESULT :0
PerformDeviceProvisioning waiting started
Info: Failed DNS lookup for global.azure-devices-provisioning.net: -5
Error: Time:Thu May 20 10:49:10 2021 File:/home/Workspace/AzureSDK/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:initiate_socket_connection Line:304 DNS resolution failed
Error: Time:Thu May 20 10:49:10 2021 File:/home/Workspace/AzureSDK/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_send Line:938 Failure: sending socket failed. errno=32 (Broken pipe).
Error: Time:Thu May 20 10:49:10 2021 File:/home/Workspace/AzureSDK/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:write_outgoing_bytes Line:641 Error in xio_send.
Error: Time:Thu May 20 10:49:10 2021 File:/home/Workspace/AzureSDK/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:send_handshake_bytes Line:685 Error in write_outgoing_bytes.
Error: Time:Thu May 20 10:49:10 2021 File:/home/Workspace/AzureSDK/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_dowork Line:1062 Socketio_Failure: Receiving data from endpoint: errno=107.
Error: Time:Thu May 20 10:49:10 2021 File:/home/Workspace/AzureSDK/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:onOpenComplete Line:454 Error: failure opening connection to endpoint
Error: Time:Thu May 20 10:49:10 2021 File:/home/Workspace/AzureSDK/azure-iot-sdk-c/provisioning_client/src/prov_transport_mqtt_common.c Func:mqtt_error_callback Line:139 MQTT communication error
Error: Time:Thu May 20 10:49:10 2021 File:/home/Workspace/AzureSDK/azure-iot-sdk-c/provisioning_client/src/prov_device_ll_client.c Func:on_transport_registration_data Line:770 Failure retrieving data from the provisioning service
CAzureIoTHubClientManager::DeviceProvisioningOperationStatus received
Application callback - Device Registration Operation Result Status received: DP Failed Status: 5. Hub Url: . Device ID: 

OnDeviceRegistrationOperationResult
m_bLibraryInitDone so disconnecting
m_bLibraryInitDone so disconnected.
m_pAzureIoTHubClientManager->Initialize completed
m_pCloudAbstractionLib->Initialize completed going for provisioning.

PROV_DEVICE_RESULT :0
PerformDeviceProvisioning waiting started
Info: Failed DNS lookup for global.azure-devices-provisioning.net: -5
Error: Time:Thu May 20 10:49:40 2021 File:/home/Workspace/AzureSDK/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:initiate_socket_connection Line:304 DNS resolution failed
Error: Time:Thu May 20 10:49:40 2021 File:/home/Workspace/AzureSDK/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_send Line:938 Failure: sending socket failed. errno=32 (Broken pipe).
Error: Time:Thu May 20 10:49:40 2021 File:/home/Workspace/AzureSDK/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:write_outgoing_bytes Line:641 Error in xio_send.
Error: Time:Thu May 20 10:49:40 2021 File:/home/Workspace/AzureSDK/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:send_handshake_bytes Line:685 Error in write_outgoing_bytes.
Error: Time:Thu May 20 10:49:40 2021 File:/home/Workspace/AzureSDK/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_dowork Line:1062 Socketio_Failure: Receiving data from endpoint: errno=107.
Error: Time:Thu May 20 10:49:40 2021 File:/home/Workspace/AzureSDK/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:onOpenComplete Line:454 Error: failure opening connection to endpoint
Error: Time:Thu May 20 10:49:40 2021 File:/home/Workspace/AzureSDK/azure-iot-sdk-c/provisioning_client/src/prov_transport_mqtt_common.c Func:mqtt_error_callback Line:139 MQTT communication error


Log stopped here and application is still waiting for response.
Could you please help us to find root cause. Also could you please suggest how we can recover it

Thanks in advance
Seema

**Comment by seemamathew** [comment] 2021-05-25 04:13
Hi,

We are our release is blocked due this issue. 
It will be very helpful if we get response on this issue.

Thanks in advance
Seema

**Comment by ericwol-msft** [comment] 2021-05-26 21:38
I could not reproduce your issue. This is what I did. Both times I get the register_device_callback. What version of the SDK are you using? Is it the latest LTS?

```
    PROV_DEVICE_RESULT prov_device_result = PROV_DEVICE_RESULT_ERROR;
    PROV_DEVICE_HANDLE prov_device_handle;
    (void)IoTHub_Init();
    (void)prov_dev_security_init(hsm_type);
    g_registration_complete = false;
    prov_device_handle = Prov_Device_Create(global_prov_uri, id_scope, prov_transport);
    prov_device_result = Prov_Device_Register_Device(prov_device_handle, register_device_callback, NULL, registration_status_callback, NULL);
    (void)printf("\r\nRegistering Device try 1\r\n\r\n");
    do
    {
        ThreadAPI_Sleep(1000);
    } while (!g_registration_complete);
    Prov_Device_Destroy(prov_device_handle);
    prov_dev_security_deinit();
    IoTHub_Deinit();

    (void)IoTHub_Init();
    (void)prov_dev_security_init(hsm_type);
    g_registration_complete = false;
    prov_device_handle = Prov_Device_Create(global_prov_uri, id_scope, prov_transport);
    prov_device_result = Prov_Device_Register_Device(prov_device_handle, register_device_callback, NULL, registration_status_callback, NULL);
    (void)printf("\r\nRegistering Device try 2\r\n\r\n");
    do
    {
        ThreadAPI_Sleep(1000);
    } while (!g_registration_complete);
    Prov_Device_Destroy(prov_device_handle);
    prov_dev_security_deinit();
    IoTHub_Deinit();
```

Also if you want to retry device provisioning, you don't need to call the deinits. Just retry calling Prov_Device_Register_Device() also call IoTHub_Deinit when your app exits.

**Comment by smartmedic** [comment] 2021-05-27 03:25
Hi Eric,

Thanks for reply.
We are using azure-iot-sdk -c 1.3.8 version. We could reproduce this issue in low network environments.

We will retry after removing deinits and will update you.

Thanks and Regards
Seema

**Comment by smartmedic** [comment] 2021-05-27 06:18
Hi Eric,

Even after changing Deinits, we are able to reproduce the issue.
Signal strength at issue reported environment is 7 ASU.
I appreciate your quick response.

Thanks and Regards
Seema

**Comment by ericwol-msft** [comment] 2021-05-27 20:59
Can you try it against the latest LTS release?

https://github.com/Azure/azure-iot-sdk-c/releases/tag/LTS_01_2021_Ref01

**Comment by seemamathew** [comment] 2021-05-28 12:09
Hi Eric,

Issue is reproducible with latest SDK too. But frequency is reduced. Now issue issue is reproduced(hang) on 4th trail
Logs are given below:
PerformDeviceProvisioning waiting started
Info: Failed DNS lookup for global.azure-devices-provisioning.net: -5
Error: Time:Fri May 28 09:45:29 2021 File:/usr/src/debug/azure-iot-sdk-c/1.7.0-r0/git/c-utility/adapters/socketio_berkeley.c Func:initiate_socket_connection Line:308 DNS resolution failed
Error: Time:Fri May 28 09:45:29 2021 File:/usr/src/debug/azure-iot-sdk-c/1.7.0-r0/git/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:829 lookup_address_and_connect_socket failed
Error: Time:Fri May 28 09:45:29 2021 File:/usr/src/debug/azure-iot-sdk-c/1.7.0-r0/git/umqtt/src/mqtt_client.c Func:onOpenComplete Line:454 Error: failure opening connection to endpoint
Error: Time:Fri May 28 09:45:29 2021 File:/usr/src/debug/azure-iot-sdk-c/1.7.0-r0/git/provisioning_client/src/prov_transport_mqtt_common.c Func:mqtt_error_callback Line:139 MQTT communication error
Error: Time:Fri May 28 09:45:29 2021 File:/usr/src/debug/azure-iot-sdk-c/1.7.0-r0/git/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_open_complete Line:839 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Fri May 28 09:45:29 2021 File:/usr/src/debug/azure-iot-sdk-c/1.7.0-r0/git/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1426 Failed opening the underlying I/O.
Error: Time:Fri May 28 09:45:29 2021 File:/usr/src/debug/azure-iot-sdk-c/1.7.0-r0/git/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:1093 Error: io_open failed
Error: Time:Fri May 28 09:45:29 2021 File:/usr/src/debug/azure-iot-sdk-c/1.7.0-r0/git/provisioning_client/src/prov_transport_mqtt_common.c Func:create_connection Line:644 Failure connecting to mqtt server
Error: Time:Fri May 28 09:45:29 2021 File:/usr/src/debug/azure-iot-sdk-c/1.7.0-r0/git/provisioning_client/src/prov_transport_mqtt_common.c Func:prov_transport_common_mqtt_dowork Line:945 unable to create mqtt connection
Error: Time:Fri May 28 09:45:29 2021 File:/usr/src/debug/azure-iot-sdk-c/1.7.0-r0/git/provisioning_client/src/prov_device_ll_client.c Func:on_transport_registration_data Line:771 Failure retrieving data from the provisioning service
CAzureIoTHubClientManager::DeviceProvisioningOperationStatus received
CAzureIoTHubClientManager::DeviceProvisioningOperationStatus received nullptr != m_pThis
CAzureIoTHubClientManager::DeviceProvisioningOperationStatus received nullptr != m_pThis
CAzureCallbackImplementor::OnDeviceProvisioningOperationResultChanged

Application callback - Device Registration Operation Result Status received: DP Failed Status: 5. Hub Url: . Device ID: 

OnDeviceRegistrationOperationResult
GetStringForDeviceProvisioningOperationResult not success
Start of do : 94421
SendTelemetry not success

PROV_DEVICE_RESULT :0
PerformDeviceProvisioning waiting started
Info: Failed DNS lookup for global.azure-devices-provisioning.net: -5
Error: Time:Fri May 28 09:45:59 2021 File:/usr/src/debug/azure-iot-sdk-c/1.7.0-r0/git/c-utility/adapters/socketio_berkeley.c Func:initiate_socket_connection Line:308 DNS resolution failed
Error: Time:Fri May 28 09:45:59 2021 File:/usr/src/debug/azure-iot-sdk-c/1.7.0-r0/git/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:829 lookup_address_and_connect_socket failed
Error: Time:Fri May 28 09:45:59 2021 File:/usr/src/debug/azure-iot-sdk-c/1.7.0-r0/git/umqtt/src/mqtt_client.c Func:onOpenComplete Line:454 Error: failure opening connection to endpoint
Error: Time:Fri May 28 09:45:59 2021 File:/usr/src/debug/azure-iot-sdk-c/1.7.0-r0/git/provisioning_client/src/prov_transport_mqtt_common.c Func:mqtt_error_callback Line:139 MQTT communication error
Error: Time:Fri May 28 09:45:59 2021 File:/usr/src/debug/azure-iot-sdk-c/1.7.0-r0/git/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_open_complete Line:839 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Fri May 28 09:45:59 2021 File:/usr/src/debug/azure-iot-sdk-c/1.7.0-r0/git/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1426 Failed opening the underlying I/O.


Thanks and Regards
Seema

**Comment by ericwol-msft** [comment] 2021-05-28 21:23
The next step after tlsio_openssl_open is calling SSL_free()/SSL_CTX_free() maybe the issue is in your openSSL library. What version are you using? 

I had no problem calling this repeatedly on OpenSSL 1.1.1k  25 Mar 2021

```
**Registering Device**

Error: Time:Fri May 28 14:21:14 2021 File:C:\temp\azure-iot-sdk-c\c-utility\adapters\socketio_win32.c Func:initiate_socket_connection Line:219 DNS resolution failed
Error: Time:Fri May 28 14:21:14 2021 File:C:\temp\azure-iot-sdk-c\c-utility\adapters\socketio_win32.c Func:socketio_open Line:476 initiate_socket_connection failed
Error: Time:Fri May 28 14:21:14 2021 File:C:\temp\azure-iot-sdk-c\umqtt\src\mqtt_client.c Func:onOpenComplete Line:454 Error: failure opening connection to endpoint
Error: Time:Fri May 28 14:21:14 2021 File:C:\temp\azure-iot-sdk-c\provisioning_client\src\prov_transport_mqtt_common.c Func:mqtt_error_callback Line:139 MQTT communication error
Error: Time:Fri May 28 14:21:14 2021 File:C:\temp\azure-iot-sdk-c\c-utility\adapters\tlsio_openssl.c Func:on_underlying_io_open_complete Line:839 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Fri May 28 14:21:14 2021 File:C:\temp\azure-iot-sdk-c\c-utility\adapters\tlsio_openssl.c Func:tlsio_openssl_open Line:1426 Failed opening the underlying I/O.
Error: Time:Fri May 28 14:21:14 2021 File:C:\temp\azure-iot-sdk-c\umqtt\src\mqtt_client.c Func:mqtt_client_connect Line:1093 Error: io_open failed
Error: Time:Fri May 28 14:21:14 2021 File:C:\temp\azure-iot-sdk-c\provisioning_client\src\prov_transport_mqtt_common.c Func:create_connection Line:644 Failure connecting to mqtt server
Error: Time:Fri May 28 14:21:14 2021 File:C:\temp\azure-iot-sdk-c\provisioning_client\src\prov_transport_mqtt_common.c Func:prov_transport_common_mqtt_dowork Line:945 unable to create mqtt connection
Error: Time:Fri May 28 14:21:14 2021 File:C:\temp\azure-iot-sdk-c\provisioning_client\src\prov_device_ll_client.c Func:on_transport_registration_data Line:771 Failure retrieving data from the provisioning service

Failure registering device: PROV_DEVICE_RESULT_TRANSPORT
```

**Comment by seemamathew** [comment] 2021-05-29 07:18
Hi Eric,

Currently we are using open ssl 1.0.2. We will try to upgrade to OpenSSL 1.1.1k 25 Mar 2021 and update you progress.

Thanks and Regards
Seema

**Comment by seemamathew** [comment] 2021-06-10 04:00
Hi Eric,

Due to limitation of underlying components, we are  not able to upgrade openssl yet. We are trying for same. Meanwhile, it will be helpful if you can suggest  any alternative ways or recovery 

Thanks and Regards
Seema

**Comment by ericwol-msft** [comment] 2021-06-10 16:30
This question should be directed to the openSSL community.

**Comment by seemamathew** [comment] 2021-06-15 10:57
Hi Eric,

Thank you very much for your support. We are discussing it in openSSL community. Before closing this ticket, one more confirmation:- 

>Also if you want to retry device provisioning, you don't need to call the deinits. Just retry calling Prov_Device_Register_Device() also call IoTHub_Deinit when your app exits.

Is it applicable to IoTHub_Deinit() only. Or we don't need to call Prov_Device_Destroy(prov_device_handle) and     prov_dev_security_deinit(); in case of device provisioning retry.

Thanks and Regards
Seema

**Comment by seemamathew** [comment] 2021-06-15 14:13
Hi Eric,

Unfortunately, issue is reproduced with latest SDK and open ssl 1.1.1.

Logs are given below:
AzureIoTClientLibrary::initialize Library init alreday done - Disconnecting.
AzureIoTClientLibrary::initialize Library init alreday done - Disconnected.
Error: Time:Tue Jun 15 12:45:17 2021 File:/home/user/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:openssl_static_locks_install Line:595 Locks already initialized
Error: Time:Tue Jun 15 12:45:17 2021 File:/home/user/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_init Line:1218 Failed to install static locks in OpenSSL!
Error: Time:Tue Jun 15 12:45:17 2021 File:/home/user/azure-iot-sdk-c/iothub_client/src/iothub.c Func:IoTHub_Init Line:16 Platform initialization failed
m_pCloudAbstractionLib->Initialize completed going for provsioning.

PROV_DEVICE_RESULT :0
PerformDeviceProvisioning waiting started
Info: Failed DNS lookup for global.azure-devices-provisioning.net: -3
Error: Time:Tue Jun 15 12:45:27 2021 File:/home/user/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:initiate_socket_connection Line:308 DNS resolution failed
Error: Time:Tue Jun 15 12:45:27 2021 File:/home/user/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:829 lookup_address_and_connect_socket failed
Error: Time:Tue Jun 15 12:45:27 2021 File:/home/user/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:onOpenComplete Line:454 Error: failure opening connection to endpoint
Error: Time:Tue Jun 15 12:45:27 2021 File:/home/user/azure-iot-sdk-c/provisioning_client/src/prov_transport_mqtt_common.c Func:mqtt_error_callback Line:139 MQTT communication error
Error: Time:Tue Jun 15 12:45:27 2021 File:/home/user/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_open_complete Line:839 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Tue Jun 15 12:45:27 2021 File:/home/user/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1426 Failed opening the underlying I/O.
Error: Time:Tue Jun 15 12:45:27 2021 File:/home/user/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_conn

Thanks and Regards
Seema

**Comment by danewalton** [comment] 2021-09-21 19:02
> Is it applicable to IoTHub_Deinit() only. Or we don't need to call Prov_Device_Destroy(prov_device_handle) and prov_dev_security_deinit(); in case of device provisioning retry.

Yes the `_Destroy` can be called between times of retry while the `_security_deinit()` called once during execution.

**Comment by danewalton** [comment] 2021-09-29 17:41
Going to go ahead and close this. Please let us know if you would like it reopened.

**Closed by danewalton** 2021-09-29 17:41 UTC
Labels: question, IoTSDK
