### ISSUE TITLE
High CPU usage during reconnection

### ISSUE THREAD

**Issue by plevesque** [Azure/azure-iot-sdk-c#118] opened 2017-04-20 13:39 UTC
- **OS and version used:** <custom Linux 3.14.23-ge072dce> 

- **SDK version used:** < release_2017_03_24> 

# Description of the issue:
My device send every 5 min a heartbeat message to the cloud and after a random period of time (from 2-3 hour to 12 hour) my process (azure-connector) goes in tight loop showing those message on the console.

# Code sample exhibiting the issue:
// Create the handle
My "connectionString" has 3 value,  HostName=, DeviceId=, SharedAccessKey=

iotHubClientHandle = IoTHubClient_CreateFromConnectionString(connectionString,
AMQP_Protocol_over_WebSocketsTls);
// Attach the callback
result = IoTHubClient_SetMessageCallback(iotHubClientHandle, azureReceiveMessage,
receive_context);
...
// Send message
result = IoTHubClient_SendEventAsync(iotHubClientHandle, message->messageHandle,
azureReceiveConfirmation, message);

# Console log of the issue:
Error: Time:Thu Apr 20 13:26:52 2017 File:/azure-iot-sdk-c/iothub_client/src/iothubtransport_amqp_common.c Func:IoTHubTransport_AMQP_Common_DoWork Line:1343 Device '<private_connection_string>' reported a critical failure; connection retry will be triggered.
Error: Time:Thu Apr 20 13:26:52 2017 File:/azure-iot-sdk-c/iothub_client/src/iothubtransport_amqp_common.c Func:IoTHubTransport_AMQP_Common_DoWork Line:1304 An error occured on AMQP connection. The connection will be restablished.
Error: Time:Thu Apr 20 13:26:52 2017 File:/azure-iot-sdk-c/iothub_client/src/iothubtransport_amqp_connection.c Func:on_cbs_open_complete Line:149 CBS open failed
Error: Time:Thu Apr 20 13:26:53 2017 File:/azure-iot-sdk-c/iothub_client/src/iothubtransport_amqp_common.c Func:IoTHubTransport_AMQP_Common_Device_DoWork Line:979 Failed performing DoWork for device '<private_connection_string>' (device reported state 4; number of previous failures: 0)
Error: Time:Thu Apr 20 13:26:53 2017 File:/azure-iot-sdk-c/iothub_client/src/iothubtransport_amqp_common.c Func:IoTHubTransport_AMQP_Common_Device_DoWork Line:979 Failed performing DoWork for device '<private_connection_string>' (device reported state 4; number of previous failures: 1)
Error: Time:Thu Apr 20 13:26:53 2017 File:/azure-iot-sdk-c/iothub_client/src/iothubtransport_amqp_common.c Func:IoTHubTransport_AMQP_Common_Device_DoWork Line:979 Failed performing DoWork for device '<private_connection_string>' (device reported state 4; number of previous failures: 2)
Error: Time:Thu Apr 20 13:26:53 2017 File:/azure-iot-sdk-c/iothub_client/src/iothubtransport_amqp_common.c Func:IoTHubTransport_AMQP_Common_Device_DoWork Line:979 Failed performing DoWork for device '<private_connection_string>' (device reported state 4; number of previous failures: 3)
Error: Time:Thu Apr 20 13:26:53 2017 File:/azure-iot-sdk-c/iothub_client/src/iothubtransport_amqp_common.c Func:IoTHubTransport_AMQP_Common_Device_DoWork Line:979 Failed performing DoWork for device '<private_connection_string>' (device reported state 4; number of previous failures: 4)
Error: Time:Thu Apr 20 13:26:53 2017 File:/azure-iot-sdk-c/iothub_client/src/iothubtransport_amqp_common.c Func:IoTHubTransport_AMQP_Common_DoWork Line:1343 Device '<private_connection_string>' reported a critical failure; connection retry will be triggered.
Error: Time:Thu Apr 20 13:26:53 2017 File:/azure-iot-sdk-c/iothub_client/src/iothubtransport_amqp_common.c Func:IoTHubTransport_AMQP_Common_DoWork Line:1304 An error occured on AMQP connection. The connection will be restablished.
Error: Time:Thu Apr 20 13:26:53 2017 File:/azure-iot-sdk-c/iothub_client/src/iothubtransport_amqp_connection.c Func:on_cbs_open_complete Line:149 CBS open failed
Error: Time:Thu Apr 20 13:26:53 2017 File:/azure-iot-sdk-c/iothub_client/src/iothubtransport_amqp_common.c Func:IoTHubTransport_AMQP_Common_Device_DoWork Line:979 Failed performing DoWork for device '<private_connection_string>' (device reported state 4; number of previous failures: 0)
Error: Time:Thu Apr 20 13:26:53 2017 File:/azure-iot-sdk-c/iothub_client/src/iothubtransport_amqp_common.c Func:IoTHubTransport_AMQP_Common_Device_DoWork Line:979 Failed performing DoWork for device '<private_connection_string>' (device reported state 4; number of previous failures: 1)
Error: Time:Thu Apr 20 13:26:53 2017 File:/azure-iot-sdk-c/iothub_client/src/iothubtransport_amqp_common.c Func:IoTHubTransport_AMQP_Common_Device_DoWork Line:979 Failed performing DoWork for device '<private_connection_string>' (device reported state 4; number of previous failures: 2)
Error: Time:Thu Apr 20 13:26:53 2017 File:/azure-iot-sdk-c/iothub_client/src/iothubtransport_amqp_common.c Func:IoTHubTransport_AMQP_Common_Device_DoWork Line:979 Failed performing DoWork for device '<private_connection_string>' (device reported state 4; number of previous failures: 3)
Error: Time:Thu Apr 20 13:26:53 2017 File:/azure-iot-sdk-c/iothub_client/src/iothubtransport_amqp_common.c Func:IoTHubTransport_AMQP_Common_Device_DoWork Line:979 Failed performing DoWork for device '<private_connection_string>' (device reported state 4; number of previous failures: 4)

**Comment by olivierbloch** [comment] 2017-04-20 18:21
Closing as duplicate of #117

**Closed by olivierbloch** 2017-04-20 18:21 UTC
Labels: investigation-required
