### ISSUE TITLE
MQTT Connection Fails??

### ISSUE THREAD

**Issue by mv-bp** [Azure/azure-iot-sdk-c#433] opened 2018-03-27 18:27 UTC
- **OS and version used:**
A Linux variation using Kernel 3.12.70
Processor:		32bit ARM5 

- **SDK version used:** 
azure-iot-sdk-c 1.1.32

IoT Hub Client options set via IoTHubClient_SetOption(...):
messageTimeout	:	tested with varied settings (1 second (1000ms) -  20 seconds (20000ms))
sas_token_lifetime	:	tested with varied settings (30 seconds - 86400 seconds = 1day)
logTrace			:	true

IoT Retry Policy set via IoTHubClient_SetRetryPolicy(...):
retryPolicy					:	tested with varied settings (IOTHUB_CLIENT_RETRY_IMMEDIATE, IOTHUB_CLIENT_RETRY_INTERVAL, IOTHUB_CLIENT_RETRY_LINEAR_BACKOFF, IOTHUB_CLIENT_RETRY_EXPONENTIAL_BACKOFF)
retryTimeoutLimitInseconds	:	tested with varied settings (30 second -  3600 seconds)

# Description of the issue:
When IoT Hub in Azure has a server error (see "IoT Hub Error" log below), 
the IoT Device loses MQTT connection to the Hub (see "SDK log trace" below) and 
the device is unable to reconnect to the Hub using the internal retry policy.

Do we need to change the options or retry settings?
Are we missing something on the device like a trust certificate?
Do we need to change settings in the IoT hub or with the Azure IoT C SDK?
The log trace looks similar to case/issue #62, “Memory leaks in case network connection got broken”, is this issue similar?

# Code sample exhibiting the issue:
This issue is not easy to reproduce nor have we determined a way to consistently reproduce. 
1) The application creates a connection (MQTT_WebSocket_Protocol).  

_iothubClientHandle = IoTHubClient_CreateFromConnectionString(connectionString.c_str(), MQTT_WebSocket_Protocol);

2) The application sends (primarily) and receives messages via the IoT Hub connection successfully for a varying period of time (3 days - 3 weeks).
When the error occurs, the application is attempting to send a message.

IOTHUB_CLIENT_RESULT result = IoTHubClient_SendEventAsync(_iothubClientHandle, message_handle, send_callback, &completion);

# Console log of the issue:
Within the application, the connection_callback(IOTHUB_CLIENT_CONNECTION_STATUS result, IOTHUB_CLIENT_CONNECTION_STATUS_REASON reason, void* userContextCallback) logs the following:

result = UNAUTHENTICATED
reason = NO_NETWORK

The SDK log trace:
-> 00:44:00 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/19512462/messages/events/%24.ct=application%2Fjson&%24.ce=utf-8 | PACKET_ID: 6456 | PAYLOAD_LEN: 382
Error: Time:Mon Mar 26 00:44:05 2018 File:/usr/src/debug/azure-iot-sdk/1.1.30-r0/git/c/c-utility/src/uws_client.c Func:uws_client_close_async Line:1537 close has been called when already CLOSED
Error: Time:Mon Mar 26 00:44:05 2018 File:/usr/src/debug/azure-iot-sdk/1.1.30-r0/git/c/c-utility/src/tlsio_openssl.c Func:decode_ssl_received_bytes Line:783 SSL channel closed in decode_ssl_received_bytes.
Error: Time:Mon Mar 26 00:44:05 2018 File:/usr/src/debug/azure-iot-sdk/1.1.30-r0/git/c/c-utility/src/tlsio_openssl.c Func:on_underlying_io_bytes_received Line:832 Error in decode_ssl_received_bytes.
Error: Time:Mon Mar 26 00:44:05 2018 File:/usr/src/debug/azure-iot-sdk/1.1.30-r0/git/c/c-utility/src/tlsio_openssl.c Func:tlsio_openssl_open Line:1221 Invalid tlsio_state. Expected state is TLSIO_STATE_NOT_OPEN.
Error: Time:Mon Mar 26 00:44:05 2018 File:/usr/src/debug/azure-iot-sdk/1.1.30-r0/git/c/c-utility/src/uws_client.c Func:uws_client_open_async Line:1472 Opening the underlying IO failed
Error: Time:Mon Mar 26 00:44:05 2018 File:/usr/src/debug/azure-iot-sdk/1.1.30-r0/git/c/c-utility/src/wsio.c Func:wsio_open Line:512 Opening the uws instance failed.
Error: Time:Mon Mar 26 00:44:05 2018 File:/usr/src/debug/azure-iot-sdk/1.1.30-r0/git/c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:980 Error: io_open failed
Error: Time:Mon Mar 26 00:44:05 2018 File:/usr/src/debug/azure-iot-sdk/1.1.30-r0/git/c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:1784 failure connecting to address GatewayQAHUB01.azure-devices.net.
Error: Time:Mon Mar 26 00:44:06 2018 File:/usr/src/debug/azure-iot-sdk/1.1.30-r0/git/c/c-utility/src/tlsio_openssl.c Func:tlsio_openssl_open Line:1221 Invalid tlsio_state. Expected state is TLSIO_STATE_NOT_OPEN.
Error: Time:Mon Mar 26 00:44:06 2018 File:/usr/src/debug/azure-iot-sdk/1.1.30-r0/git/c/c-utility/src/uws_client.c Func:uws_client_open_async Line:1472 Opening the underlying IO failed
Error: Time:Mon Mar 26 00:44:06 2018 File:/usr/src/debug/azure-iot-sdk/1.1.30-r0/git/c/c-utility/src/wsio.c Func:wsio_open Line:512 Opening the uws instance failed.
Error: Time:Mon Mar 26 00:44:06 2018 File:/usr/src/debug/azure-iot-sdk/1.1.30-r0/git/c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:980 Error: io_open failed
Error: Time:Mon Mar 26 00:44:06 2018 File:/usr/src/debug/azure-iot-sdk/1.1.30-r0/git/c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:1784 failure connecting to address GatewayQAHUB01.azure-devices.net.
...

The retry policy continues to try to reconnect unsuccessfully with the same log trace as above captured.  

IoT Hub Error, the following is captured:

Connect Error:
SourceSystem: Azure
TimeGenerated [UTC]: 2018-03-26T00:36:32Z
ResultType: 500001
ResultDescription: ServerError
OperationName: deviceDisconnect
Category: Connections
Level: Error
properties_s: {"deviceId":"19512462","protocol":"Mqtt","authType":null,"maskedIpAddress":"52.167.229.XXX","statusCode":"500"}
location_s: centralus
ResourceGroup: GATEWAYQA01
ResourceProvider: MICROSOFT.DEVICES
Resource: GATEWAYQAHUB01
ResourceType: IOTHUBS
Type: AzureDiagnostics

Telemetry Error:
SourceSystem: Azure
TimeGenerated [UTC]: 2018-03-26T00:36:32Z
ResultType: 500001
ResultDescription: ServerError
OperationName: ingress
Category: DeviceTelemetry
Level: Error
properties_s: {"deviceId":"19512462","protocol":"Mqtt","authType":"{\"scope\":\"device\",\"type\":\"sas\",\"issuer\":\"iothub\",\"acceptingIpFilterRule\":null}","maskedIpAddress":"52.167.229.XXX","messageId":"","messageSizeInBytes":"403","batchSize":"1","batching":"False","statusCode":"500"}
location_s: centralus
ResourceGroup: GATEWAYQA01
ResourceProvider: MICROSOFT.DEVICES
Resource: GATEWAYQAHUB01
ResourceType: IOTHUBS
Type: AzureDiagnostics

**Comment by jspaith** [comment] 2018-03-27 22:37
This sounds somewhat like #264.  What's happening there is that if you're connected via an HTTPS proxy with MQTT_WS, then we don't recover from a disconnection.  This was 100% repro with proxy, and I don't see your mentioning proxy, so its not a slam dunk that these are duplicates.  

264 was caused by not closing up TLS correctly on a disconnect, and I see unhappy ssl messages in your log especially about internal TLS state expecting to be not open.  So it's not out of the realm of possibility that the fix for 264, which is currently in https://github.com/Azure/azure-iot-sdk-c/compare/mqtt-ws-proxy and undergoing final code review, will fix this too.

The fact that you get sporadic repro makes this harder.  But for next steps, could you pick up the https://github.com/Azure/azure-iot-sdk-c/compare/mqtt-ws-proxy once it hits master and see if this addresses concerns?

**Comment by jspaith** [comment] 2018-03-30 23:31
I've just submitted the fix for this (see #264) and we've fixed another bug in relating to MQTT_WS and disconnections - https://github.com/Azure/azure-c-shared-utility/commit/45d6a1b4f0de711076e2017676cd0842f240a48b

You should be set for pretesting to see if this addresses your problems as both changes are in master.

**Comment by jspaith** [comment] 2018-04-19 03:45
I appreciate these intermittent issues are **very** hard to reproduce.  But since the fixes have been in a few weeks, I'm going to close this out in hopes that our fixes in this space help.

Obviously if you're still having problems, don't hesitate to re-activate this or create a new one.  Thanks.

**Closed by jspaith** 2018-04-19 03:45 UTC
Labels: investigation-required

**Comment by tameraw** [comment] 2018-04-23 22:52
@mv-bp thank you for your contribution to our open-sourced project!  Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V).

**Comment by jmonticelli** [comment] 2019-10-10 22:04
I would reopen this issue and investigate further. I have an extremely similar error, and it happens when using MQTT_WS over a proxy. This issue is entirely resolved by switching to AMQP_WS, but MQTT_WS worked a day before without flaw. I am running the Azure IoTHub SDK Python wrapper versioned at 1.4.6 with a built-from-source version of the SDK, tagged at version 1.4.6.

The error I am getting, specifically, is:

Oct 10 20:43:40 crl-hc-001 hc_cloud_client[7746]: _sdk_python/src/azure_iot_sdk_python_ep/c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_bytes_received Line:846 Error in decode_ssl_received_bytes.
Oct 10 20:43:40 crl-hc-001 hc_cloud_client[7746]: Error: Time:Thu Oct 10 20:38:36 2019 File:/mnt/ssd/work/bld/lib/azure_iot_sdk_python/src/azure_iot_sdk_python_ep/c/c-utility/src/uws_client.c Func:uws_client_close_async Line:1749 close has been called when already CLOSED
Oct 10 20:43:40 crl-hc-001 hc_cloud_client[7746]: Error: Time:Thu Oct 10 20:38:36 2019 File:/mnt/ssd/work/bld/lib/azure_iot_sdk_python/src/azure_iot_sdk_python_ep/c/c-utility/adapters/tlsio_openssl.c Func:decode_ssl_received_bytes Line:797 SSL channel closed in decode_ssl_received_bytes.
Oct 10 20:43:40 crl-hc-001 hc_cloud_client[7746]: Error: Time:Thu Oct 10 20:38:36 2019 File:/mnt/ssd/work/bld/lib/azure_iot_sdk_python/src/azure_iot_sdk_python_ep/c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_bytes_received Line:846 Error in decode_ssl_received_bytes.
Oct 10 20:43:40 crl-hc-001 hc_cloud_client[7746]: Error: Time:Thu Oct 10 20:39:36 2019 File:/mnt/ssd/work/bld/lib/azure_iot_sdk_python/src/azure_iot_sdk_python_ep/c/c-utility/src/uws_client.c Func:uws_client_close_async Line:1749 close has been called when already CLOSED
Oct 10 20:43:40 crl-hc-001 hc_cloud_client[7746]: Error: Time:Thu Oct 10 20:39:36 2019 File:/mnt/ssd/work/bld/lib/azure_iot_sdk_python/src/azure_iot_sdk_python_ep/c/c-utility/adapters/tlsio_openssl.c Func:decode_ssl_received_bytes Line:797 SSL channel closed in decode_ssl_received_bytes.
Oct 10 20:43:40 crl-hc-001 hc_cloud_client[7746]: Error: Time:Thu Oct 10 20:39:36 2019 File:/mnt/ssd/work/bld/lib/azure_iot_sdk_python/src/azure_iot_sdk_python_ep/c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_bytes_received Line:846 Error in decode_ssl_received_bytes.
Oct 10 20:43:40 crl-hc-001 hc_cloud_client[7746]: Error: Time:Thu Oct 10 20:40:38 2019 File:/mnt/ssd/work/bld/lib/azure_iot_sdk_python/src/azure_iot_sdk_python_ep/c/c-utility/src/uws_client.c Func:uws_client_close_async Line:1749 close has been called when already CLOSED
Oct 10 20:43:40 crl-hc-001 hc_cloud_client[7746]: Error: Time:Thu Oct 10 20:40:38 2019 File:/mnt/ssd/work/bld/lib/azure_iot_sdk_python/src/azure_iot_sdk_python_ep/c/c-utility/adapters/tlsio_openssl.c Func:decode_ssl_received_bytes Line:797 SSL channel closed in decode_ssl_received_bytes.
Oct 10 20:43:40 crl-hc-001 hc_cloud_client[7746]: Error: Time:Thu Oct 10 20:40:38 2019 File:/mnt/ssd/work/bld/lib/azure_iot_sdk_python/src/azure_iot_sdk_python_ep/c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_bytes_received Line:846 Error in decode_ssl_received_bytes.
Oct 10 20:43:40 crl-hc-001 hc_cloud_client[7746]: Error: Time:Thu Oct 10 20:41:39 2019 File:/mnt/ssd/work/bld/lib/azure_iot_sdk_python/src/azure_iot_sdk_python_ep/c/c-utility/src/uws_client.c Func:uws_client_close_async Line:1749 close has been called when already CLOSED
Oct 10 20:43:40 crl-hc-001 hc_cloud_client[7746]: Error: Time:Thu Oct 10 20:41:39 2019 File:/mnt/ssd/work/bld/lib/azure_iot_sdk_python/src/azure_iot_sdk_python_ep/c/c-utility/adapters/tlsio_openssl.c Func:decode_ssl_received_bytes Line:797 SSL channel closed in decode_ssl_received_bytes.
Oct 10 20:43:40 crl-hc-001 hc_cloud_client[7746]: Error: Time:Thu Oct 10 20:41:39 2019 File:/mnt/ssd/work/bld/lib/azure_iot_sdk_python/src/azure_iot_sdk_python_ep/c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_bytes_received Line:846 Error in decode_ssl_received_bytes.
Oct 10 20:43:40 crl-hc-001 hc_cloud_client[7746]: Error: Time:Thu Oct 10 20:42:40 2019 File:/mnt/ssd/work/bld/lib/azure_iot_sdk_python/src/azure_iot_sdk_python_ep/c/c-utility/src/uws_client.c Func:uws_client_close_async Line:1749 close has been called when already CLOSED
Oct 10 20:43:40 crl-hc-001 hc_cloud_client[7746]: Error: Time:Thu Oct 10 20:42:40 2019 File:/mnt/ssd/work/bld/lib/azure_iot_sdk_python/src/azure_iot_sdk_python_ep/c/c-utility/adapters/tlsio_openssl.c Func:decode_ssl_received_bytes Line:797 SSL channel closed in decode_ssl_received_bytes.
Oct 10 20:43:40 crl-hc-001 hc_cloud_client[7746]: Error: Time:Thu Oct 10 20:42:40 2019 File:/mnt/ssd/work/bld/lib/azure_iot_sdk_python/src/azure_iot_sdk_python_ep/c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_bytes_received Line:846 Error in decode_ssl_received_bytes.
Oct 10 20:43:40 crl-hc-001 hc_cloud_client[7746]: Error: Time:Thu Oct 10 20:43:40 2019 File:/mnt/ssd/work/bld/lib/azure_iot_sdk_python/src/azure_iot_sdk_python_ep/c/c-utility/src/uws_client.c Func:uws_client_close_async Line:1749 close has been called when already CLOSED
Oct 10 20:44:36 crl-hc-001 hc_cloud_client[7746]: Error: Time:Thu Oct 10 20:43:40 2019 File:/mnt/ssd/work/bld/lib/azure_iot_sdk_python/src/azure_iot_sdk_python_ep/c/c-utility/adapters/tlsio_openssl.c Func:decode_ssl_received_bytes Line:797 SSL channel closed in decode_ssl_received_bytes.

**Comment by jmonticelli** [comment] 2019-10-10 22:06
I would reopen this issue and investigate further. I have an extremely similar error, and it happens when using MQTT_WS over a proxy. This issue is entirely resolved by switching to AMQP_WS, but MQTT_WS worked a day before without flaw. I am running the Azure IoTHub SDK Python wrapper versioned at 1.4.6 with a built-from-source version of the SDK, tagged at version 1.4.6.

The error I am getting, specifically, is:

Oct 10 20:43:40 REDACTED REDACTED[7746]: _sdk_python/src/azure_iot_sdk_python_ep/c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_bytes_received Line:846 Error in decode_ssl_received_bytes.
Oct 10 20:43:40 REDACTED REDACTED[7746]: Error: Time:Thu Oct 10 20:38:36 2019 File:/mnt/ssd/work/bld/lib/azure_iot_sdk_python/src/azure_iot_sdk_python_ep/c/c-utility/src/uws_client.c Func:uws_client_close_async Line:1749 close has been called when already CLOSED
Oct 10 20:43:40 REDACTED REDACTED[7746]: Error: Time:Thu Oct 10 20:38:36 2019 File:/mnt/ssd/work/bld/lib/azure_iot_sdk_python/src/azure_iot_sdk_python_ep/c/c-utility/adapters/tlsio_openssl.c Func:decode_ssl_received_bytes Line:797 SSL channel closed in decode_ssl_received_bytes.
Oct 10 20:43:40 REDACTED REDACTED[7746]: Error: Time:Thu Oct 10 20:38:36 2019 File:/mnt/ssd/work/bld/lib/azure_iot_sdk_python/src/azure_iot_sdk_python_ep/c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_bytes_received Line:846 Error in decode_ssl_received_bytes.
Oct 10 20:43:40 REDACTED REDACTED[7746]: Error: Time:Thu Oct 10 20:39:36 2019 File:/mnt/ssd/work/bld/lib/azure_iot_sdk_python/src/azure_iot_sdk_python_ep/c/c-utility/src/uws_client.c Func:uws_client_close_async Line:1749 close has been called when already CLOSED
Oct 10 20:43:40 REDACTED REDACTED[7746]: Error: Time:Thu Oct 10 20:39:36 2019 File:/mnt/ssd/work/bld/lib/azure_iot_sdk_python/src/azure_iot_sdk_python_ep/c/c-utility/adapters/tlsio_openssl.c Func:decode_ssl_received_bytes Line:797 SSL channel closed in decode_ssl_received_bytes.
Oct 10 20:43:40 REDACTED REDACTED[7746]: Error: Time:Thu Oct 10 20:39:36 2019 File:/mnt/ssd/work/bld/lib/azure_iot_sdk_python/src/azure_iot_sdk_python_ep/c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_bytes_received Line:846 Error in decode_ssl_received_bytes.
Oct 10 20:43:40 REDACTED REDACTED[7746]: Error: Time:Thu Oct 10 20:40:38 2019 File:/mnt/ssd/work/bld/lib/azure_iot_sdk_python/src/azure_iot_sdk_python_ep/c/c-utility/src/uws_client.c Func:uws_client_close_async Line:1749 close has been called when already CLOSED
Oct 10 20:43:40 REDACTED REDACTED[7746]: Error: Time:Thu Oct 10 20:40:38 2019 File:/mnt/ssd/work/bld/lib/azure_iot_sdk_python/src/azure_iot_sdk_python_ep/c/c-utility/adapters/tlsio_openssl.c Func:decode_ssl_received_bytes Line:797 SSL channel closed in decode_ssl_received_bytes.
Oct 10 20:43:40 REDACTED REDACTED[7746]: Error: Time:Thu Oct 10 20:40:38 2019 File:/mnt/ssd/work/bld/lib/azure_iot_sdk_python/src/azure_iot_sdk_python_ep/c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_bytes_received Line:846 Error in decode_ssl_received_bytes.
Oct 10 20:43:40 REDACTED REDACTED[7746]: Error: Time:Thu Oct 10 20:41:39 2019 File:/mnt/ssd/work/bld/lib/azure_iot_sdk_python/src/azure_iot_sdk_python_ep/c/c-utility/src/uws_client.c Func:uws_client_close_async Line:1749 close has been called when already CLOSED
Oct 10 20:43:40 REDACTED REDACTED[7746]: Error: Time:Thu Oct 10 20:41:39 2019 File:/mnt/ssd/work/bld/lib/azure_iot_sdk_python/src/azure_iot_sdk_python_ep/c/c-utility/adapters/tlsio_openssl.c Func:decode_ssl_received_bytes Line:797 SSL channel closed in decode_ssl_received_bytes.
Oct 10 20:43:40 REDACTED REDACTED[7746]: Error: Time:Thu Oct 10 20:41:39 2019 File:/mnt/ssd/work/bld/lib/azure_iot_sdk_python/src/azure_iot_sdk_python_ep/c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_bytes_received Line:846 Error in decode_ssl_received_bytes.
Oct 10 20:43:40 REDACTED REDACTED[7746]: Error: Time:Thu Oct 10 20:42:40 2019 File:/mnt/ssd/work/bld/lib/azure_iot_sdk_python/src/azure_iot_sdk_python_ep/c/c-utility/src/uws_client.c Func:uws_client_close_async Line:1749 close has been called when already CLOSED
Oct 10 20:43:40 REDACTED REDACTED[7746]: Error: Time:Thu Oct 10 20:42:40 2019 File:/mnt/ssd/work/bld/lib/azure_iot_sdk_python/src/azure_iot_sdk_python_ep/c/c-utility/adapters/tlsio_openssl.c Func:decode_ssl_received_bytes Line:797 SSL channel closed in decode_ssl_received_bytes.
Oct 10 20:43:40 REDACTED REDACTED[7746]: Error: Time:Thu Oct 10 20:42:40 2019 File:/mnt/ssd/work/bld/lib/azure_iot_sdk_python/src/azure_iot_sdk_python_ep/c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_bytes_received Line:846 Error in decode_ssl_received_bytes.
Oct 10 20:43:40 REDACTED REDACTED[7746]: Error: Time:Thu Oct 10 20:43:40 2019 File:/mnt/ssd/work/bld/lib/azure_iot_sdk_python/src/azure_iot_sdk_python_ep/c/c-utility/src/uws_client.c Func:uws_client_close_async Line:1749 close has been called when already CLOSED
Oct 10 20:44:36 REDACTED REDACTED[7746]: Error: Time:Thu Oct 10 20:43:40 2019 File:/mnt/ssd/work/bld/lib/azure_iot_sdk_python/src/azure_iot_sdk_python_ep/c/c-utility/adapters/tlsio_openssl.c Func:decode_ssl_received_bytes Line:797 SSL channel closed in decode_ssl_received_bytes.

**Comment by jspaith** [comment] 2019-10-18 22:19
@jmonticelli - the current Python SDK that wraps C is almost totally locked down.  The last time that they took a snap of the C SDK was ea8d7c29ae313754a2f0972494756b97cc6921d7, so the underlying C SDK is over nine months old at this point.  For reference, the C wrapper based Python SDK lives currently [here](https://github.com/Azure/azure-iot-sdk-python/tree/v1-deprecated).

The Python team is creating a new SDK - using the [same repo name as before](https://github.com/Azure/azure-iot-sdk-python/) - which is 100% native Python.  This addresses the many deployment issues customers were hitting due to the C wrapper dependency, in addition to the obvious friction of having Python SDK needing to wait for C fixes and then re-publish everything.

We've made further C SDK fixes in last few months, and if we had repros on a later C SDK we would investigate.  But I'm sorry I don't have a better answer for you on this one specifically.
