### ISSUE TITLE
Memory leaks in case network connection got broken

### ISSUE THREAD

**Issue by mm-ark** [Azure/azure-iot-sdk-c#61] opened 2017-02-08 09:45 UTC
Hi folks!

I use azure-iot-sdk-c "2017-01-27" f348ba0. Valgrind memory check reports heavy memory losses.
I have attached reproducable example which is a slightly modified iothub_client_sample_mqtt.c
[main.cpp.zip](https://github.com/Azure/azure-iot-sdk-c/files/760205/main.cpp.zip)

Steps done by me
1. Make sure network connection to IoT HUb is ok
2. Run attached sample application with your custom connection string within valgrind
3. Observe for some minutes that IoT Hub receives messages from sample application
4. "Break" network connection ( i used command: iptables -A OUTPUT -p tcp --dport 8883 -j DROP)
5. Let  sample application run many hours (15 hours on my side)

Results (memory losses) on my side:
crt_abstractions.c:683 (might be fixed meanwhile on master)
tlsio_openssl.c:799
tlsio_openssl.c:864
tlsio_openssl.c:870 (might be fixed meanwhile on master)
iothub_message.c:65

Full stack traces:
433,950 bytes in 2,921 blocks are definitely lost in loss record 885 of 909
  in mallocAndStrcpy_s in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/crt_abstractions.c:683
  1: malloc in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so
  2: mallocAndStrcpy_s in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/crt_abstractions.c:683
  3: cloneMqttOptions in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_client.c:453
  4: mqtt_client_connect in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_client.c:875
  5: SendMqttConnectMsg in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransport_mqtt_common.c:1596
  6: InitializeConnection in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransport_mqtt_common.c:1637
  7: IoTHubTransport_MQTT_Common_DoWork in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransport_mqtt_common.c:2371
  8: IoTHubTransportMqtt_DoWork in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransportmqtt.c:95
  9: IoTHubClient_LL_DoWork in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothub_client_ll.c:950
  10: iothub_client_sample_mqtt_run() in /home/mm/eclipse/workspace/DataAgent/Source/ptxproj/tests/MemoryChecks/Test2_iothub_client_sample_mqtt/main.cpp:186
  11: main in /home/mm/eclipse/workspace/DataAgent/Source/ptxproj/tests/MemoryChecks/Test2_iothub_client_sample_mqtt/main.cpp:218

  
1,450,422 (9,856 direct, 1,440,566 indirect) bytes in 308 blocks are definitely lost in loss record 899 of 909
  in create_openssl_instance in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/tlsio_openssl.c:799
  1: malloc in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so
  2: CRYPTO_malloc in /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
  3: sk_new in /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
  4: X509_STORE_new in /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
  5: SSL_CTX_new in /lib/x86_64-linux-gnu/libssl.so.1.0.0
  6: create_openssl_instance in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/tlsio_openssl.c:799
  7: tlsio_openssl_open in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/tlsio_openssl.c:1045
  8: xio_open in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/xio.c:87
  9: mqtt_client_connect in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_client.c:881
  10: SendMqttConnectMsg in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransport_mqtt_common.c:1596
  11: InitializeConnection in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransport_mqtt_common.c:1637
  12: IoTHubTransport_MQTT_Common_DoWork in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransport_mqtt_common.c:2371
  13: IoTHubTransportMqtt_DoWork in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransportmqtt.c:95
  14: IoTHubClient_LL_DoWork in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothub_client_ll.c:950
  15: iothub_client_sample_mqtt_run() in /home/mm/eclipse/workspace/DataAgent/Source/ptxproj/tests/MemoryChecks/Test2_iothub_client_sample_mqtt/main.cpp:186
  16: main in /home/mm/eclipse/workspace/DataAgent/Source/ptxproj/tests/MemoryChecks/Test2_iothub_client_sample_mqtt/main.cpp:218

3,883,052 (26,368 direct, 3,856,684 indirect) bytes in 824 blocks are definitely lost in loss record 906 of 909
  in create_openssl_instance in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/tlsio_openssl.c:864
  1: malloc in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so
  2: CRYPTO_malloc in /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
  3: X509_LOOKUP_new in /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
  4: X509_STORE_add_lookup in /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
  5: X509_STORE_set_default_paths in /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
  6: create_openssl_instance in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/tlsio_openssl.c:864
  7: tlsio_openssl_open in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/tlsio_openssl.c:1045
  8: xio_open in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/xio.c:87
  9: mqtt_client_connect in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_client.c:881
  10: SendMqttConnectMsg in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransport_mqtt_common.c:1596
  11: InitializeConnection in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransport_mqtt_common.c:1637
  12: IoTHubTransport_MQTT_Common_DoWork in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransport_mqtt_common.c:2371
  13: IoTHubTransportMqtt_DoWork in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransportmqtt.c:95
  14: IoTHubClient_LL_DoWork in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothub_client_ll.c:950
  15: iothub_client_sample_mqtt_run() in /home/mm/eclipse/workspace/DataAgent/Source/ptxproj/tests/MemoryChecks/Test2_iothub_client_sample_mqtt/main.cpp:186
  16: main in /home/mm/eclipse/workspace/DataAgent/Source/ptxproj/tests/MemoryChecks/Test2_iothub_client_sample_mqtt/main.cpp:218

24,533,786 (2,356,936 direct, 22,176,850 indirect) bytes in 2,917 blocks are definitely lost in loss record 909 of 909
  in create_openssl_instance in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/tlsio_openssl.c:870
  1: malloc in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so
  2: CRYPTO_malloc in /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
  3: SSL_new in /lib/x86_64-linux-gnu/libssl.so.1.0.0
  4: create_openssl_instance in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/tlsio_openssl.c:870
  5: tlsio_openssl_open in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/tlsio_openssl.c:1045
  6: xio_open in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/xio.c:87
  7: mqtt_client_connect in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_client.c:881
  8: SendMqttConnectMsg in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransport_mqtt_common.c:1596
  9: InitializeConnection in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransport_mqtt_common.c:1637
  10: IoTHubTransport_MQTT_Common_DoWork in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransport_mqtt_common.c:2371
  11: IoTHubTransportMqtt_DoWork in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransportmqtt.c:95
  12: IoTHubClient_LL_DoWork in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothub_client_ll.c:950
  13: iothub_client_sample_mqtt_run() in /home/mm/eclipse/workspace/DataAgent/Source/ptxproj/tests/MemoryChecks/Test2_iothub_client_sample_mqtt/main.cpp:186
  14: main in /home/mm/eclipse/workspace/DataAgent/Source/ptxproj/tests/MemoryChecks/Test2_iothub_client_sample_mqtt/main.cpp:218

9,507,907 (332,800 direct, 9,175,107 indirect) bytes in 8,320 blocks are definitely lost in loss record 908 of 909
  in IoTHubMessage_CreateFromByteArray in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothub_message.c:65
  1: malloc in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so
  2: IoTHubMessage_CreateFromByteArray in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothub_message.c:65
  3: iothub_client_sample_mqtt_run() in /home/mm/eclipse/workspace/DataAgent/Source/ptxproj/tests/MemoryChecks/Test2_iothub_client_sample_mqtt/main.cpp:160
  4: main in /home/mm/eclipse/workspace/DataAgent/Source/ptxproj/tests/MemoryChecks/Test2_iothub_client_sample_mqtt/main.cpp:218

**Comment by anporumb** [comment] 2017-02-08 19:22
Hello @mm-ark ,

We have recently (since the release you are using) fixed some leaks in that area. It would be great if you could help us by taking the master HEAD SHA and quickly see if it still reproes.

Thank you.

Best Regards,
Andrei Porumb

**Comment by mm-imr** [comment] 2017-02-09 13:53
Hi there,
I cloned master c861ec3 from 2017-02-09.

The problems are still there, especially the issues with tlsio_openssl.

Best,

Ingo

**Comment by anporumb** [comment] 2017-02-09 19:23
Hello @mm-imr , @mm-ark,

Thank you for your report. We shall absolutely look at it.

Much appreciated.

Best Regards,
Andrei Porumb

**Comment by zolvarga** [comment] 2017-02-16 23:28
Hello @mm-ark ,

Could you please let us know what is the environment you are using?
OS version, OpenSSL version etc...
Valgrind has issues to run with certain OpenSSL versions and I want to be sure we are using the same environment.

Best Regards,
Zoltan

**Comment by mm-ark** [comment] 2017-02-17 06:59
Hey Zoltan,

My OS is LinuxMint-17.3-xfce-64bit. It it based on Ubuntu 14.04 as i remember
mm@lvm ~ $ uname -a
Linux lvm 3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

OpenSSL version is: 1.0.1f-1ubuntu2.15
libcurl version is: 7.35.0-1ubuntu2.10

Best regards
Anatolij

**Comment by zolvarga** [comment] 2017-02-28 22:21
Hi Anatolij,

I found an issue with the main.cpp you provided. Valgrind was completely unhappy with it. I am attaching the modified version, please take a look at it and try to run with the latest SDK. 
I am running it longhaul and did not found any issue yet.

Thanks,
Zoltan

[main.cpp.zip](https://github.com/Azure/azure-iot-sdk-c/files/809116/main.cpp.zip)

**Comment by mm-ark** [comment] 2017-03-02 08:47
Hi Zoltan,

Thank you, happy to hear that something is going on with this issue...
The release of our solution is currently blocked (postponed) due to this and other issues (55, 64) we have reported here. They arre very critical and urgent. Could you please high prioritize these issues within your team? I ask because the architecture of our solution is designed with a fallback to other IoT platform than Microsoft Azure. Our management knows that and might very soon decide other way...

Nearly 100% of the main.cpp i attached originate from iothub_client_sample_mqtt.c within the SDK. If the case your main.cpp is better, than please update it within the SDK accordingly.

I am not sure if we are allowed to test this issue within the latest SDK 4th time.

**Comment by mm-ark** [comment] 2017-03-02 13:57
Hi Zoltan,

I tried latest code from c SDK, commit 392f105ea50a9a145d82e681c33080fd67519931
With `while (runsCounter <  5)` in main.cpp and the 5 steps from above i still get memory loss within about 15 minutes.

296,244 (21,816 direct, 274,428 indirect) bytes in 27 blocks are definitely lost in loss record 82 of 82
  in create_openssl_instance in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/tlsio_openssl.c:869
  1: malloc in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so
  2: CRYPTO_malloc in /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
  3: SSL_new in /lib/x86_64-linux-gnu/libssl.so.1.0.0
  4: create_openssl_instance in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/tlsio_openssl.c:869
  5: tlsio_openssl_open in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/tlsio_openssl.c:1044
  6: xio_open in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/c-utility/src/xio.c:88
  7: mqtt_client_connect in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/umqtt/src/mqtt_client.c:892
  8: SendMqttConnectMsg in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransport_mqtt_common.c:1668
  9: InitializeConnection in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransport_mqtt_common.c:1709
  10: IoTHubTransport_MQTT_Common_DoWork in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransport_mqtt_common.c:2443
  11: IoTHubTransportMqtt_DoWork in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothubtransportmqtt.c:102
  12: IoTHubClient_LL_DoWork in /home/mm/wago/ptxproj-2.5.23/local_src/azure-iot-sdks-master/c/iothub_client/src/iothub_client_ll.c:1087
  13: iothub_client_sample_mqtt_run() in /home/mm/eclipse/workspace/DataAgent/Source/ptxproj/tests/MemoryChecks/Test2_iothub_client_sample_mqtt/main.cpp:188
  14: main in /home/mm/eclipse/workspace/DataAgent/Source/ptxproj/tests/MemoryChecks/Test2_iothub_client_sample_mqtt/main.cpp:221

**Comment by anporumb** [comment] 2017-03-02 19:32
Hello @mm-ark,

We're really having issues reproducing your error here. 

We have two questions: 
1) Are you pressing CTRL+C to stop the application or sending "quit" in a message to the device?

2) Can you please enable tracing in your application?
```c
bool traceOn = true;
IoTHubClient_SetOption(iotHubClientHandle1, "logtrace", &traceOn);
```
and paste here that log? [or upload as a zip]. 

Thank you.

Best Regards,
Andrei Porumb

**Comment by mm-ark** [comment] 2017-03-03 10:44
Hey guys,

Do you "break" the network connection in step 4?

I can reproduce the issues over and over again (short 10 minutes run, 15 hours run over night)...
1) No, i do not stop my application. It stops by itself when loop in main function gets left.
2) I attached tracelog outputs of my 10 minutes run


[AzureSDK-C-Memcheck-15-hours.zip](https://github.com/Azure/azure-iot-sdk-c/files/816518/AzureSDK-C-Memcheck-15-hours.zip)
[AzureSDK-C-Memcheck-10-minutes.zip](https://github.com/Azure/azure-iot-sdk-c/files/816520/AzureSDK-C-Memcheck-10-minutes.zip)
[QTCreator_maincpp.zip](https://github.com/Azure/azure-iot-sdk-c/files/816521/QTCreator_maincpp.zip)

Best Regards
Anatolij

**Comment by zolvarga** [comment] 2017-03-07 20:40
Hi Anatolij,

Thanks for the code, finally we got a repro here with the call stack below. (It is the same call stack you got.)
We are working on the fix ad will let you know...

Best Regards,
Zoltan

==390== 338,128 (23,072 direct, 315,056 indirect) bytes in 28 blocks are definitely lost in loss record 75 of 75
==390==    at 0x4C2DBB6: malloc (vg_replace_malloc.c:299)
==390==    by 0x5373E77: CRYPTO_malloc (in /lib/x86_64-linux-gnu/libcrypto.so.1.0.0)
==390==    by 0x50E811F: SSL_new (in /lib/x86_64-linux-gnu/libssl.so.1.0.0)
==390==    by 0x432C73: create_openssl_instance (in /EDrive/GitRepos/azure-iot-sdk-c/cmake/iotsdk_linux/iothub_client/samples/iothub_client_sample_mqtt/iothub_client_sample_mqtt)
==390==    by 0x433270: tlsio_openssl_open (in /EDrive/GitRepos/azure-iot-sdk-c/cmake/iotsdk_linux/iothub_client/samples/iothub_client_sample_mqtt/iothub_client_sample_mqtt)
==390==    by 0x425F51: xio_open (in /EDrive/GitRepos/azure-iot-sdk-c/cmake/iotsdk_linux/iothub_client/samples/iothub_client_sample_mqtt/iothub_client_sample_mqtt)
==390==    by 0x420644: mqtt_client_connect (in /EDrive/GitRepos/azure-iot-sdk-c/cmake/iotsdk_linux/iothub_client/samples/iothub_client_sample_mqtt/iothub_client_sample_mqtt)
==390==    by 0x41B48E: SendMqttConnectMsg (in /EDrive/GitRepos/azure-iot-sdk-c/cmake/iotsdk_linux/iothub_client/samples/iothub_client_sample_mqtt/iothub_client_sample_mqtt)
==390==    by 0x41B63B: InitializeConnection (in /EDrive/GitRepos/azure-iot-sdk-c/cmake/iotsdk_linux/iothub_client/samples/iothub_client_sample_mqtt/iothub_client_sample_mqtt)
==390==    by 0x41D2B1: IoTHubTransport_MQTT_Common_DoWork (in /EDrive/GitRepos/azure-iot-sdk-c/cmake/iotsdk_linux/iothub_client/samples/iothub_client_sample_mqtt/iothub_client_sample_mqtt)
==390==    by 0x4113A7: IoTHubTransportMqtt_DoWork (in /EDrive/GitRepos/azure-iot-sdk-c/cmake/iotsdk_linux/iothub_client/samples/iothub_client_sample_mqtt/iothub_client_sample_mqtt)
==390==    by 0x40D4AD: IoTHubClient_LL_DoWork (in /EDrive/GitRepos/azure-iot-sdk-c/cmake/iotsdk_linux/iothub_client/samples/iothub_client_sample_mqtt/iothub_client_sample_mqtt)
==390==
==390== LEAK SUMMARY:
==390==    definitely lost: 23,072 bytes in 28 blocks
==390==    indirectly lost: 315,056 bytes in 3,836 blocks
==390==      possibly lost: 0 bytes in 0 blocks
==390==    still reachable: 0 bytes in 0 blocks
==390==         suppressed: 0 bytes in 0 blocks

**Comment by zolvarga** [comment] 2017-03-08 19:44
Hi Anatolij,

The fix has bee checked in to azure-c-shared-utility:
https://github.com/Azure/azure-c-shared-utility/commit/d8d3cc7032fb929014b76f3e80cdc094dcc8123d

Could you please confirm if the fix works?

Best Regards,
Zoltan

**Comment by mm-ark** [comment] 2017-03-08 22:02
Hi Zoltan,  thank you very much! 😀 ok, i will check .
There is newly entered issue #87 which also critical for us. Please give it a high prio as well :-)
Best Regards 
Anatolij

**Comment by zolvarga** [comment] 2017-03-08 22:26
Hi Anatolij,

The master branch is updated to the latest submodules. You can just use the latest master branch for your verification.

Best Regards,
Zoltan

**Comment by mm-ark** [comment] 2017-03-09 15:30
Hi Zoltan, do you know when the next Release/Tag of the C-SDK planned? Should be tomorrow, right?

**Comment by zolvarga** [comment] 2017-03-09 16:57
Hi Anatolij,

Yes, we start the release process tomorrow.

Best Regards,
Zoltan

**Closed** 2017-03-13 18:05 UTC
Labels: fix checked in
