### ISSUE TITLE
Cannot invoke direct methods after IoT-HUB hang up and reconnect

### ISSUE THREAD

**Issue by RomanSchneider** [Azure/azure-iot-sdk-c#717] opened 2018-11-20 14:58 UTC
- **Linux**  Linux 4.14.40-rt30+ SMP PREEMPT RT on ARM Cortex A9

- **SDK version used:** 2018-10-03

# Description of the issue:

Our devices use Device Provisioning Service (TPM as Mechanism) to authenticate prior to connect to IOT HUB.  If the authentication at DPS and connection attempt to IoT HUB is successful everything works fine. We're able to **send device telemetry** and we are able to **invoke direct methods** on the devices.

After some time (about 1h) the IOT-HUB hangs up the connection, at the device we get: 

`azure_connection_callback:  IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED, reason: IOTHUB_CLIENT_CONNECTION_OK`

SDK is configured to do `retryPolicy: IOTHUB_CLIENT_RETRY_INTERVAL` with `retryTimeoutLimitInSeconds: 120`

So the SDK tries to reestablish connection, which is successful:

`azure_connection_callback: IOTHUB_CLIENT_CONNECTION_AUTHENTICATED, reason: IOTHUB_CLIENT_CONNECTION_OK`

The application starts sending device telemetry again, which is also successful (confirmed with SDK connection callbacks and we see the data at IOT-HUB)

**Problem: We cannot invoke direct methods anymore. We get:**

`{"message":"{\"Message\":\"  
  {\\\"errorCode\\\":504101,\\\"trackingId\\\":\\\"c4e1c10683ff487fbc4201b481570a32-G:18- 
  TimeStamp:11/20/2018 14:36:31\\\",\\\"message\\\":\\\"Timed out waiting for the response from 
  device.\\\",\\\"info\\\":{\\\"timeout\\\":\\\"00:00:10\\\"},\\\"timestampUtc\\\":\\\"2018-11- 
  20T14:36:31.9097791Z\\\"}\",\"ExceptionMessage\":\"\"}"}`

although the device is connected with IoT HUB. 

We see the IoT-Hub is not informed about current connection state of the connected device. 

# Questions/Issues:

* Why does the IoT HUB hang up the connection after some time? We send telemetry data at least every second. 
* We're not able to invoke direct messages after reconnect although we're able to send telemetry data

**Comment by RomanSchneider** [comment] 2018-11-27 18:31
Attached a source code example. We can reproduce the issue on ARM an x64_86 Debian GNU/Linux 9.

First, everything is OK. If we call a direct method from azure portal we get:
```$ /home/at0rsc/work/platform/firmware/.deploy/festo_native_iotgw/staging/usr/bin/simplect -p 60 -t
...
msg_confirmation_callback: result: IOTHUB_CLIENT_CONFIRMATION_OK for id 0
<- [TRANSFER]* {7,1,<34 F2 AA A0 C3 26 27 43 84 21 87 F4 0E 13 4B 1D>,0,true,false,NULL,NULL,NULL,NULL,false}
-> [DISPOSITION]* {true,1,1,true,* {}}
method_invocation_callback: testMethod payload_len = 2
-> [TRANSFER]* {7,2,<01 00 00 00>,0,false,false}
<- [DISPOSITION]* {true,2,NULL,true,* {},NULL}
sendMessage: with id 1 (recconnect_cnt = 1) 
-> [TRANSFER]* {2,3,<02 00 00 00>,2147563264,false,false}
<- [DISPOSITION]* {true,3,NULL,true,* {},NULL}
msg_confirmation_callback: result: IOTHUB_CLIENT_CONFIRMATION_OK for id 1
...
```

After about **5 hours** (recconnect_cnt = 5) the direct methods are not working anymore, we get:
```
...
sendMessage: with id 324 (recconnect_cnt = 5) 
-> [TRANSFER]* {2,333,<40 00 00 00>,2147563264,false,false}
<- [DISPOSITION]* {true,333,NULL,true,* {},NULL}
msg_confirmation_callback: result: IOTHUB_CLIENT_CONFIRMATION_OK for id 324
...
```
We see at the trace: There is no `<- [TRANSFER] .. ` anymore. 
* Direct methods **are not working**
* Cloud To Device messages **are working**
* Device To Cloud messages **are working**



source code: simplect.c
```C
/*
 * simplect.c
 *
 *  Created on: Nov 26, 2018
 *      Author: Roman Schneider
 */

// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// CAVEAT: This sample is to demonstrate azure IoT client concepts only and is not a guide design principles or style
// Checking of return codes and error values shall be omitted for brevity.  Please practice sound engineering practices
// when writing production code.

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <signal.h>
#include <getopt.h>

#include "azureiot/iothub.h"
#include "azureiot/iothub_client.h"
#include "azureiot/iothub_client_options.h"
#include "azureiot/iothub_client_version.h"
#include "azureiot/iothubtransportamqp_websockets.h"

#include "azure_c_shared_utility/shared_util_options.h"
#include "azure_c_shared_utility/http_proxy_io.h"
#include "azure_c_shared_utility/threadapi.h"

#include "azure_prov_client/prov_device_client.h"
#include "azure_prov_client/prov_security_factory.h"
#include "azure_prov_client/prov_transport_amqp_ws_client.h"
#include "azure_prov_client/prov_transport_http_client.h"

#define UNUSED(expr) do { (void)(expr); } while (0)

DEFINE_ENUM_STRINGS(PROV_DEVICE_RESULT, PROV_DEVICE_RESULT_VALUE);
DEFINE_ENUM_STRINGS(PROV_DEVICE_REG_STATUS, PROV_DEVICE_REG_STATUS_VALUES);

static bool g_registration_complete = false;
static bool g_connection_complete = false;
static bool g_use_proxy = false;
static const char* PROXY_ADDRESS = "127.0.0.1";

#define PROXY_PORT                  8888
#define MESSAGES_TO_SEND            2
#define TIME_BETWEEN_MESSAGES       2

static char* g_iothub_uri;
static char* g_device_id;

static size_t g_messageTrackingId;

static bool g_sending;

static size_t g_reconnect_cnt = 0;

static void msg_confirmation_callback(IOTHUB_CLIENT_CONFIRMATION_RESULT result,
        void* data)
{
    size_t id = (size_t) data;

    UNUSED(data);
    printf("%s: result: %s for id %zd\n", __func__,
            ENUM_TO_STRING(IOTHUB_CLIENT_CONFIRMATION_RESULT, result), id);
}

int method_invocation_callback(const char* method_name,
    const unsigned char* payload, size_t size, unsigned char** response,
    size_t* response_size, void* user_context) {

    UNUSED(user_context);

    printf("%s: %s payload_len = %zd\n", __func__, method_name, size);

    *response = (unsigned char*) malloc(size);
    *response_size = size;
    memcpy(*response, payload, size);

    return 0;
}

IOTHUBMESSAGE_DISPOSITION_RESULT msg_receive_callback(
    IOTHUB_MESSAGE_HANDLE message, void* user_context)
{

    UNUSED(user_context);

    IOTHUB_MESSAGE_RESULT msg_ret = IOTHUB_MESSAGE_OK;
    const char* buf;
    size_t buf_size = 0;
    int cb_result = IOTHUB_CLIENT_IOTHUB_METHOD_STATUS_ERROR;

    IOTHUBMESSAGE_CONTENT_TYPE payload_type =
        IoTHubMessage_GetContentType(message);

    switch (payload_type) {
    case IOTHUBMESSAGE_BYTEARRAY:
        msg_ret = IoTHubMessage_GetByteArray(
            message, (const unsigned char**)&buf, &buf_size);
        if (msg_ret != IOTHUB_MESSAGE_OK) {
            printf("%s: binary message parsing failed!\n", __func__);
        }
        break;
    case IOTHUBMESSAGE_STRING:
        buf = IoTHubMessage_GetString(message);
        if (buf != NULL) {
            buf_size = strlen(buf);
        } else {
            printf("%s: string message parsing failed!\n", __func__);
        }
        break;
    case IOTHUBMESSAGE_UNKNOWN:
    default:
        printf("%s: Unknown Message content type!\n", __func__);
    }

    if (buf != NULL) {
        printf("%s: received: %s\n", __func__, buf);
        cb_result = IOTHUB_CLIENT_IOTHUB_METHOD_STATUS_SUCCESS;
    }

    return cb_result;
}

static void connection_callback(IOTHUB_CLIENT_CONNECTION_STATUS result,
        IOTHUB_CLIENT_CONNECTION_STATUS_REASON reason, void* user_context)
{
    UNUSED(user_context);

    printf("%s: %s, reason: %s\n", __func__,
        ENUM_TO_STRING(IOTHUB_CLIENT_CONNECTION_STATUS, result),
        ENUM_TO_STRING(IOTHUB_CLIENT_CONNECTION_STATUS_REASON, reason));

    if (result == IOTHUB_CLIENT_CONNECTION_AUTHENTICATED) {
        g_connection_complete = true;
        g_reconnect_cnt++;
    } else {
        g_connection_complete = false;
    }
}

static void registation_status_callback(PROV_DEVICE_REG_STATUS reg_status, void* user_context)
{
    UNUSED(user_context);

    printf("%s: Provisioning Status: %s\n", __func__,
            ENUM_TO_STRING(PROV_DEVICE_REG_STATUS, reg_status));
}

static void register_device_callback(PROV_DEVICE_RESULT register_result,
        const char* iothub_uri, const char* device_id, void* user_context)
{
    UNUSED(user_context);

    if (register_result == PROV_DEVICE_RESULT_OK) {
        printf("%s: Registration Information received from service: %s, deviceId: %s\n",
                __func__, iothub_uri, device_id);

        g_iothub_uri = strdup(iothub_uri);
        g_device_id = strdup(device_id);

        g_registration_complete = true;

    } else {
        (void) printf("%s: Failure registering device: %s\n", __func__,
                ENUM_TO_STRING(PROV_DEVICE_RESULT, register_result));
    }
}

static void sendMessage(IOTHUB_CLIENT_HANDLE iotHubClientHandle)
{
    char payload[32];

    snprintf(payload, sizeof(payload), "%zd", g_messageTrackingId);

    IOTHUB_MESSAGE_HANDLE messageHandle = IoTHubMessage_CreateFromByteArray(
            (unsigned char*) payload, strlen(payload));

    if (messageHandle == NULL) {
        printf("%s: unable to create a new IoTHubMessage\n", __func__);
    } else {
        if (IoTHubClient_SendEventAsync(iotHubClientHandle, messageHandle,
                msg_confirmation_callback, (void*) g_messageTrackingId)
                == IOTHUB_CLIENT_OK) {
            printf("%s: with id %zd (recconnect_cnt = %zd) \n", __func__,
                    g_messageTrackingId, g_reconnect_cnt);
        }
        IoTHubMessage_Destroy(messageHandle);
    }
    g_messageTrackingId++;
}

static void sig_handler(int signo)
{
    if (signo == SIGINT) {
        printf("\nreceived SIGINT - terminating\n");
        g_sending = false;
    } else if (signo == SIGTERM) {
        printf("\nreceived SIGTERM - terminating\n");
        g_sending = false;
    } else {
        printf("\nreceived unknown signal - ignoring\n");
        return;
    }
}

static void print_help(void)
{
    char *txt = ""
            "Usage: simplect[OPTIONS]\n"
            "simple azure iot test framework\n\n"
            "Options:\n"
            "-t, --traceon      activate Azure IoT SDK traces\n"
            "-p, --period       period in seconds (example: -p 60)\n"
            "-s, --scope        DPS scope (example: -s 0ne0001205C)\n"
            "-h, --help         this\n\n";

    printf("%s", txt);
}

int main(int argc, char* argv[])
{
    int c;
    size_t period_sec = 2;

    char* prov_uri = "global.azure-devices-provisioning.net";
    char* id_scope = "0ne0001205C";

    bool traceOn = false;

    SECURE_DEVICE_TYPE hsm_type;
    hsm_type = SECURE_DEVICE_TYPE_TPM;

    HTTP_PROXY_OPTIONS http_proxy;
    PROV_DEVICE_TRANSPORT_PROVIDER_FUNCTION prov_transport;

    IOTHUB_CLIENT_HANDLE iothubclient;

    while (1) {
        static struct option long_options[] =
            {
                { "traceon", no_argument, 0, 't' },
                { "scope", required_argument, 0, 's' },
                { "period", required_argument, 0, 'p' },
                { "help", no_argument, 0, 'h' },
                { 0, 0, 0, 0 } };

        /* getopt_long stores the option index here. */
        int option_index = 0;

        c = getopt_long(argc, argv, "ts:p:h", long_options, &option_index);

        /* Detect the end of the options. */
        if (c == -1)
            break;

        switch (c) {
            case 0:
                /* If this option set a flag, do nothing else now. */
                if (long_options[option_index].flag != 0)
                    break;
                printf("option %s", long_options[option_index].name);
                if (optarg)
                    printf(" with arg %s", optarg);
                printf("\n");
                break;

            case 's':
                id_scope = optarg;
                break;

            case 'p':
                period_sec = atoi(optarg);
                break;

            case 't':
                traceOn = true;
                break;

            case 'h':
                print_help();
                return EXIT_SUCCESS;

            case '?':
                /* getopt_long already printed an error message. */
                break;

            default:
                abort();
        }
    }

    // Used to initialize IoTHub SDK subsystem
    (void) IoTHub_Init();
    (void) prov_dev_security_init(hsm_type);

    memset(&http_proxy, 0, sizeof(HTTP_PROXY_OPTIONS));

    prov_transport = Prov_Device_HTTP_Protocol;

    printf(" Provisioning API Version: %s\n", Prov_Device_GetVersionString());
    printf("   IOT HUB Client Version: %s\n", IoTHubClient_GetVersionString());
    printf("         Provisioning URI: %s\n", prov_uri);
    printf("       Provisioning Scope: %s\n", id_scope);
    printf("Message interval (period): %zd\n", period_sec);

    if (g_use_proxy) {
        http_proxy.host_address = PROXY_ADDRESS;
        http_proxy.port = PROXY_PORT;
    }

    PROV_DEVICE_RESULT prov_device_result;
    PROV_DEVICE_HANDLE prov_device_handle;

    if ((prov_device_handle = Prov_Device_Create(prov_uri, id_scope,
            prov_transport)) == NULL) {

        printf("failed calling Prov_Device_Create\n");

    } else {

        if (http_proxy.host_address != NULL) {
            Prov_Device_SetOption(prov_device_handle, OPTION_HTTP_PROXY,
                    &http_proxy);
        }

        Prov_Device_SetOption(prov_device_handle, PROV_OPTION_LOG_TRACE,
                &traceOn);

        prov_device_result = Prov_Device_Register_Device(prov_device_handle,
                register_device_callback, NULL, registation_status_callback,
                NULL);

        if (prov_device_result != PROV_DEVICE_RESULT_OK) {
            printf("FATAL: Prov_Device_Register_Device failed\n");
            return EXIT_FAILURE;
        }

        printf("Registering Device ...\n");

        do {
            ThreadAPI_Sleep(1000);
        }
        while (!g_registration_complete);

        Prov_Device_Destroy(prov_device_handle);

        iothubclient = IoTHubClient_CreateFromDeviceAuth(g_iothub_uri,
                g_device_id, AMQP_Protocol_over_WebSocketsTls);

        if (iothubclient == NULL) {
            printf("FATAL: can't IoTHubClient_CreateFromDeviceAuth.\n");
            return 1;
        }

        if (IoTHubClient_SetOption(iothubclient, OPTION_LOG_TRACE, &traceOn)
                != IOTHUB_CLIENT_OK) {
            printf("IoTHubClient_SetOption OPTION_LOG_TRACE failed.\n");
        }

        if (IoTHubClient_SetOption(iothubclient, OPTION_SAS_TOKEN_REFRESH_TIME,
                "300") != IOTHUB_CLIENT_OK) {
            printf("IoTHubClient_SetOption OPTION_SAS_TOKEN_REFRESH_TIME failed.\n");
        }

        if (IoTHubClient_SetRetryPolicy(iothubclient,
                IOTHUB_CLIENT_RETRY_INTERVAL, 120) != IOTHUB_CLIENT_OK) {
            printf("IoTHubClient_SetRetryPolicy failed.\n");
        }

        if (IoTHubClient_SetConnectionStatusCallback(iothubclient,
                connection_callback, 0) != IOTHUB_CLIENT_OK) {
            printf("IoTHubClient_SetConnectionStatusCallback failed.\n");
        }

        if (IoTHubClient_SetMessageCallback(iothubclient, msg_receive_callback,
                0) != IOTHUB_CLIENT_OK) {
            printf("IoTHubClient_SetMessageCallback failed.\n");
        }

        if (IoTHubClient_SetDeviceMethodCallback(iothubclient,
                method_invocation_callback, 0) != IOTHUB_CLIENT_OK) {
            printf("IoTHubClient_SetDeviceMethodCallback failed.\n");
        }

        printf("Waiting for Authentication ... \n");

        do {
            ThreadAPI_Sleep(1000);
        }
        while (!g_connection_complete);

        signal(SIGINT, sig_handler);
        signal(SIGTERM, sig_handler);

        g_sending = true;

        do {
            sendMessage(iothubclient);
            ThreadAPI_Sleep(1000 * period_sec);

        }
        while (g_sending);

        IoTHubClient_Destroy(iothubclient);

        free(g_iothub_uri);
        free(g_device_id);
    }
    prov_dev_security_deinit();

    // Free all the sdk subsystem
    IoTHub_Deinit();

    return 0;
}
 ```

**Comment by az-iot-builder-01** [comment] 2018-11-27 18:31
@RomanSchneider, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by truschival** [comment] 2018-12-03 14:42
I can reproduce the issue on both Linux ARM and Linux x86_64 build with transport ``AMQP_Protocol_over_WebSocketsTls``.

Running above sample program on Linux x86_64 with ``MQTT_WebSocket_Protocol``  so far didn't show the symptoms. After 4 hrs the device still receives direct method calls from the cloud.

**Comment by truschival** [comment] 2018-12-20 12:00
MQTT over websockets definitely performs better. Running above program with 17 reconnects (ca. 18h) we still can invoke direct messages. 
Using AMQP over websockets I managed to invoke direct messages after 3 reconnects at most.  It seems the bug does not manifest itself on every reconnect.

**Comment by yzhong94** [comment] 2019-01-18 01:01
@truschival @RomanSchneider Sorry about the delay on getting back to you.  We are looking at this issue now and will have a response by EoD Monday.

**Comment by truschival** [comment] 2019-01-23 09:37
@yzhong94 have you been able to reproduce the issue? Do you need more info? 
I slightly modified @RomanSchneider's simplect to allow for choosing the transport protocol at runtime: https://gist.github.com/truschival/b9667a37f818d2b52ece15d3f7dbf887#file-simplect-c 

Call it with either `-x MQTT_WEBSOCKETS` for MQTT over websockets or `-x AMQP_WEBSOCKETS` (default)

**Comment by yzhong94** [comment] 2019-01-28 18:15
Hi @truschival , @jebrando is still looking into this

**Comment by truschival** [comment] 2019-01-29 11:54
I just ran tests this morning using the above gist (https://github.com/Azure/azure-iot-sdk-c/issues/717#issuecomment-456733783) with ``simplect -P -x AMQP_WEBSOCKETS -p 30 -d``
I called direct methods using the IoT-Hub webfrontend on portal.azure.com sporadically.

Direct methods worked for 3 hours, it then failed with 
```
{"message":"{\"Message\":\"{\\\"errorCode\\\":504101,\\\"trackingId\\\":\\\"43d7154f6fb742ec85acc457cd8588b5-G:18-TimeStamp:01/29/2019
 11:39:53\\\",\\\"message\\\":\\\"Timed out waiting for the response 
from device.\\\",\\\"info\\\":{\\\"timeout\\\":\\\"00:00:10\\\"},\\\"timestampUtc\\\":\\\"2019-01-29T11:39:53.2278127Z\\\"}\",\"ExceptionMessage\":\"\"}"}
```

The messages on the wire are hard to trace, I haven't set up a HTTPS decrypt infrastructure yet to look into the packages. Looking at the packet stream using wireshark my hunch is **the issue may be on the IoT-hub cloud side**:  Calling methods with a payload I was able to observe packets of different size than regular Device-To-Cloud messages and their confirmations.  
**When the method calls start to fail, these packet (sizes) do not appear in wireshark traces anymore.**

**Comment by truschival** [comment] 2019-02-04 11:50
I cannot verify if release 2019-01-31 fixed the issue.  The program above now produces tons of error log messages 
`iothub_client/src/iothubtransport_amqp_cbs_auth.c Func:verify_sas_token_refresh_timeout Line:119 Failed Getting SasToken Expiry ` 

The setup I used for testing is the same as before: x86_64 Debian with Software TPM simulator. Am I missing something? Is it now mandatory to set options for sas-token refresh timeouts?

**Comment by truschival** [comment] 2019-02-04 12:54
To avoid the error messages setting the `OPTION_SAS_TOKEN_REFRESH_TIME ` is mandatory e.g.:
`IoTHubClient_SetOption(iothubclient, OPTION_SAS_TOKEN_REFRESH_TIME , "somevalue")`

**Comment by jebrando** [comment] 2019-02-05 00:52
@truschival This is odd, the Sas Token refresh time defaults to 3600 and so it should never be 0.  I'm running your sample and have not gotten that error yet.  I don't see how it could be set to 0, unless it being set in the user app.  Now that you mention it, we probably need to not let it be set it to some floor value.  I'll add that, but I'm curious to see why it's 0 for you.

**Comment by massand** [comment] 2019-03-12 06:58
@truschival - have you been able to validate the issue is fixed on 1.2.14 release? #857 should prevent the SAS token refresh time value from being set to an unreasonable value (i.e. zero) by default or through the app. Thanks in advance for following up.

**Comment by truschival** [comment] 2019-03-14 14:56
@massand - We didn't upgrade to 1.2.14 at the moment, I didn't try to verify the issue since the above workaround (https://github.com/Azure/azure-iot-sdk-c/issues/717#issuecomment-460239393) solved the problem and didn't affect any other features. IMHO this issue (#717) can be closed.

**Comment by ewertons** [comment] 2019-03-14 18:32
Hi @truschival ,
thanks for confirming. Please let us know if you need any further follow up on this.
Thanks,
Azure IoT Team

**Closed by ewertons** 2019-03-14 18:32 UTC
Labels: investigation-required

**Comment by jimoneil** [comment] 2019-04-03 22:54
I am trying to follow the comments here to determine if we are seeing something similar in a Node environment.  To clarify, was the original bug (cannot call direct method) resolved when EXPLICITLY setting OPTION_SAS_TOKEN_REFRESH_TIME?  Or were these two different behaviors?

**Comment by truschival** [comment] 2019-04-08 07:14
@jimoneil these were different issues. The original issue (direct method calls) was resolved end of January with release 2019-01-31. The fix introduced the issue that required explicitly setting  `OPTION_SAS_TOKEN_REFRESH_TIME`.
I haven't experienced issues with direct method calls any more.

**Comment by lexguy20** [comment] 2019-12-03 16:03
I am using DeviceClient version 1.16.0, release date February 28, 2019. I am using Java to create DeviceClient. It is running fine to send and receive any message to IoT hub.
When I call a Direct method from Azure IoT portal hub after ~10 sec it displayed a response message as:
**{"message":"{\"Message\":\"{\\\"errorCode\\\":504101,\\\"trackingId\\\":\\\"40a7dd98fc2d4836b1c045996665b23d-G:9-TimeStamp:12/03/2019 15:00:09-G:11-TimeStamp:12/03/2019 15:00:09\\\",\\\"message\\\":\\\"Timed out waiting for the response from device.\\\",\\\"info\\\":{},\\\"timestampUtc\\\":\\\"2019-12-03T15:00:09.0082523Z\\\"}\",\"ExceptionMessage\":\"\"}"}
Failed to invoke device method: {"message":"{\"Message\":\"{\\\"errorCode\\\":504101,\\\"trackingId\\\":\\\"40a7dd98fc2d4836b1c045996665b23d-G:9-TimeStamp:12/03/2019 15:00:09-G:11-TimeStamp:12/03/2019 15:00:09\\\",\\\"message\\\":\\\"Timed out waiting for the response from device.\\\",\\\"info\\\":{},\\\"timestampUtc\\\":\\\"2019-12-03T15:00:09.0082523Z\\\"}\",\"ExceptionMessage\":\"\"}"}**


I tried: **setOption("SetSASTokenExpiryTime" , new Long(300))** as mentioned in this thread but no help.

Interestingly, if I check logs on my app(IoT-Application), I can see the the method is successfully called from IoT hub, its looks like IoT hub has failed to received the response from my App. Am I missing something here?
Any help will be greatly appreciated, thanks

Following is my simple App code:
`public class IoT-Application
{
   private static DeviceClient client = null;
   private static DeviceMethodStatusCallBack deviceMethodStatusCallBack = null;

   public IoT-Application()
   {
      deviceMethodStatusCallBack = new DeviceMethodStatusCallBack();
   }

   /**
    * Send message to iot hub
    */
   private static void sendMessage(JSONObject content, String type)
   {
      content.put("iotDeviceId", client.getConfig().getDeviceId());
      Message message = new Message(content.toString());
      message.setProperty("type", type);
      client.sendEventAsync(message, deviceMethodStatusCallBack, null);
   }

   /**
    * Hub event callback that just echos status.
    */
   protected static class DeviceMethodStatusCallBack implements IotHubEventCallback
   {
      @Override
      public void execute(IotHubStatusCode status, Object context)
      {
         Activator.getLog().debug(" IotHubEventCallback execute method called with status::" + status.name());
      }
   }

   /**
    * Message callback that just echos the message received.
    */
   private static MessageCallback messageCallback = (message, context) -> {
      Activator.getLog().debug(" MessageCallback received message: " + new String(message.getBytes(), StandardCharsets.UTF_8));
      return IotHubMessageResult.COMPLETE;
   };

   /**
    * Direct method callback handler.
    */
   private static class DirectMethodCallback implements DeviceMethodCallback
   {

      /**
       * Executes the specified direct method.
       *
       * @param methodName	The name of the method.
       *           
       * @param methodData	The method body (JSON).
       *           
       * @param context	The context in which the method was called.       
       *           
       * @return The status of the method result.
       */
      @Override
      public DeviceMethodData call(String methodName, Object methodData, Object context)
      {

         Activator.getLog().debug(" Incoming method: " + methodName);
         return new DeviceMethodData(200, "StringData");
      }
   }

   @Override
   public void init()
   {

      Thread t = new Thread(() -> {
         try
         {
        	 
		client = new DeviceClient("<My-Connection-String>", 
                IotHubClientProtocol.MQTT_WS);
		client.open();
		client.setMessageCallback(messageCallback, new HashMap<>());
		client.subscribeToDeviceMethod(new DirectMethodCallback(), null, 
                deviceMethodStatusCallBack, null);
		Long sasTime = new Long(300);
		client.setOption("SetSASTokenExpiryTime", sasTime);
         }
         catch (URISyntaxException syntaxException)
         {
            Activator.getLog().info("Invalid URI syntax");
         }
         catch (Throwable tr)
         {
            tr.printStackTrace();
         }
      });
      t.setName("IoT-device-thread");
      t.start();
   }
}
`
