### ISSUE TITLE
X.509 certificate custom hsm

### ISSUE THREAD

**Issue by patrickzgubic** [Azure/azure-iot-sdk-c#2260] opened 2022-03-13 09:56 UTC
hello,
I'm trying to work through the following example (provision multiple X.509 devices with hsm):
https://docs.microsoft.com/en-us/azure/iot-dps/tutorial-custom-hsm-enrollment-group-x509

When i try to build the solution , the following error message appears:
LNK1104: cannot open file '\d\azure-iot-sdk-c\cmake\provisioning_client\samples\custom_hsm_example\Debug\custom_hsm_example.obj'

I am working with Visual Studio 2019 on Windows 10

**Comment by momuno** [comment] 2022-03-14 16:17
Hi @patrickzgubic. Can you please confirm you have the correct permissions set for the file and that the shown path is its true location?

**Comment by patrickzgubic** [comment] 2022-03-14 16:29
The Debug folder in custom_hsm_example does not exist and i cannot find the custom_hsm_example.obj file on my filesystem

**Comment by momuno** [comment] 2022-03-14 16:32
Which release are you using so I can try to reproduce?

**Comment by patrickzgubic** [comment] 2022-03-14 16:43
LTS_01_2022_Ref01

**Comment by momuno** [comment] 2022-03-14 17:07
I have not run into that issue, but am finding a different one.  
In Windows 11, I am using the Git Bash shell.  Instructions ask to use either that or the command prompt.

https://docs.microsoft.com/en-us/azure/iot-dps/tutorial-custom-hsm-enrollment-group-x509#prepare-the-azure-iot-c-sdk-development-environment , 
 
 I cloned my azure-iot-sdk-c into the C drive, so my -Dhsm_customlib path I use is `/c/azure-iot-sdk-c/cmake/provisioning_client/samples/custom_hsm_example/Debug/custom_hsm_example.lib`.  

Once I run the cmake generation step, an `azure-iot-sdk-c.sln` is generated at the root of the `azure-iot-sdk-c/cmake` directory.  Upon opening that `sln` file, and building the Provision_Samples/custom_hsm_example, everything builds and a `Debug/` driectory will appear under `azure-iot-sdk-c/cmake/provisioning_client/samples/custom_hsm_example`, containing `custom_hsm_example.lib.`  I run into an error attempting to start the lib program.

What environment are you using to create the `obj` file?

**Comment by patrickzgubic** [comment] 2022-03-14 17:28
Ok, I have used the developer powershell of Visual Studio

**Comment by momuno** [comment] 2022-03-14 17:32
I will try that as well.

**Comment by patrickzgubic** [comment] 2022-03-14 18:17
No, the issue is still there.

I am working on C, so the cmake command is: cmake -Duse_prov_client:BOOL=ON -Dhsm_custom_lib=/c/azure-iot-sdk-c/cmake/provisioning_client/samples/custom_hsm_example/Debug/custom_hsm_example.lib ..  (Debug folder is not there)

Then I have set custom_hsm_example as startup project > Build > Debug folder with custom_hsm_example.lib appears.

Then I have set prov_dev_client_sample as startup project > Build > same error as before and custom_hsm_example.obj does not exist.

**Comment by momuno** [comment] 2022-03-14 19:12
@patrickzgubic I'm curious to see what the Visual Studio lists as the additional dependencies for the prov_dev_client_sample.  Trying to figure out where this obj instead of lib expectation is coming from.  

With the azure_iot_sdks.sln open, can you please right-click on `prov_dev_client_sample` under Provision Samples, and select `Properties`.  From there go to `Linker->Input`, and open up the `Additional Dependencies`.  Mine only lists `.lib` files, including `..\custom_hsm_example\Debug\custom_hsm_example.lib`.  Is your custom_hsm_example file listed as a `.obj` file? or `.lib` there?

**Comment by momuno** [comment] 2022-03-14 19:31
The only way so far I am able to reproduce the issue is if I set the build flag during the cmake step to use `custom_hsm_example.obj` instead of `custom_hsm_example.lib`:
`-Dhsm_custom_lib=/d/azure-iot-sdk-c/cmake/provisioning_client/samples/custom_hsm_example/Debug/custom_hsm_example.obj`

Could you please retry deleting your current cmake directory and create a new one?  Sometimes cached values will hang around if it's not a clean new build.

**Comment by CIPop** [comment] 2022-03-14 19:42
@patrickzgubic it's uncommon on Windows to use a custom HSM. If you just want to use X509 certificates with DPS, please see the new feature we've added to C-SDK here: https://github.com/Azure/azure-iot-sdk-c/tree/main/provisioning_client/samples/prov_dev_client_ll_x509_sample .

This works for both individual and group X509 DPS registrations.

**Comment by momuno** [comment] 2022-03-21 21:34
@patrickzgubic Did @CIPop's suggestion help you accomplish your goal?  Or, have you been able to resolve the possible linker issue?

**Comment by gino-1557** [comment] 2022-03-21 22:14
No, I was not able to solve the linker issue.  @CIPop's suggestion helped me achieve half the goal. The final goal is to use X509 certificates with DPS, stored in a hsm/tpm on linux. Now I am working on windows, because I want to use the debugger of visual studio for the development.

**Comment by patrickzgubic** [comment] 2022-03-23 11:05
Yes, it helped me. The example works, but i don't want to place my certificate hardcoded in the code.  I want to store my certificate securly in hsm (not only on windows, also on linux). I'm working on this point right now.  No, I didn't try to solve the linker problem anymore

**Comment by momuno** [comment] 2022-03-24 22:58
@patrickzgubic, HSM is a new area for me. Upon digging into the code, it does look like the setOptions call `Prov_Device_LL_SetOption([PROV_DEVICE_LL_HANDLE handle], OPTION_X509_CERT, [const void* value_x509certificate])` is what you use to set the hsm x509 certificate, but to use this the CMake flag `-Dhsm_type_x509=ON` must be set. It is not yet clear to me how this stored cert gets used by the sample, nor do I know enough about hsm cert storage to recommend a best practice for storing and retrieving to be used by the application.  (I do see in the sample it currently has the cert hard-coded in.) @CIPop is there any more info you could share with us on how include the cert from the hsm and not coded directly into the application? Thanks.

**Comment by CIPop** [comment] 2022-03-28 18:01
@momuno the meaning of `-Dhsm_type_x509=ON` changed with the latest feature and it now works the same way for DPS and IoT Hub Clients. Previously, as you've pointed out, it was using DICE/RIOT which can now be used with `-Dhsm_type_riot=ON`.

 > how include the cert from the hsm and not coded directly into the application?

There are many ways that depend on the HSM:

- OpenSSL ENGINE: https://github.com/Azure/azure-iot-sdk-c/blob/main/provisioning_client/devdoc/using_provisioning_client.md#x509-certificates
- Custom HSM (requires the developer to write the adapter): https://github.com/Azure/azure-iot-sdk-c/blob/main/provisioning_client/devdoc/using_custom_hsm.md

Running on Linux, if the HSM driver already has an OpenSSL ENGINE, we recommend the first option. The second option is useful for non-standard configurations or TLS stacks other than OpenSSL.

**Comment by momuno** [comment] 2022-04-04 19:43
@patrickzgubic checking in to see if the information provided has helped you accomplish your goal, or if you have any other questions.

**Comment by patrickzgubic** [comment] 2022-04-07 20:38
All right for me thanks

**Comment by momuno** [comment] 2022-04-15 22:00
@patrickzgubic I will close this issue.  Please reopen, or open a new issue, if you run into any other obstacles.  Thank you!

**Closed by momuno** 2022-04-15 22:00 UTC
Labels: IoTSDK
