### ISSUE TITLE
DPS + X509 issue

### ISSUE THREAD

**Issue by neotrip** [Azure/azure-iot-sdk-c#1782] opened 2020-12-08 13:17 UTC
Hi SDK team,

I have noticed DPS+X509  may be implemented via HSM framework ，like [code](https://github.com/Azure/azure-iot-sdk-c/blob/master/provisioning_client/samples/custom_hsm_example/custom_hsm_example.c)

Is there any example for DPS + X509 without HSM interface?

Thanks

**Comment by danewalton** [comment] 2021-02-02 19:14
@neotrip I don't believe so. I set the cert via the options and I get an error that the cert is already set. Is this the behavior you are seeing?

**Comment by neotrip** [comment] 2021-02-03 06:24
@danewalton,

Actually I have no idea how to set DPS+x509 cert info via kinds of options.  

The configuration way in following links works, but is not friend to APP designer, in my opinion:
https://github.com/Azure/azure-iot-sdk-c/blob/master/provisioning_client/samples/custom_hsm_example/custom_hsm_example.c

It will be better to provide option-setting APIs.

**Comment by danewalton** [comment] 2021-02-03 20:46
I just confirmed that we do not currently support explicitly setting the cert and key as options. You can use the custom hsm sample that we have to set the cert and key. I have a quick blurb from another issue here to hopefully help you out:
https://github.com/Azure/azure-iot-sdk-c/issues/1643#issuecomment-686191481

**Comment by danewalton** [comment] 2021-02-08 18:09
I'm going to go ahead and close this since the original question seems to be answered. If not feel free to ask to have this reopened or open another issue.

**Closed by danewalton** 2021-02-08 18:09 UTC
Labels: IoTSDK, question

**Comment by ArnasTeltonika** [comment] 2022-07-04 09:20
My colleague has managed to configure azure_iothub for DPS + x509 to work without HSM, however we seem to be not able to do the same with Plug and Play device registration. Have any ideas?
