### ISSUE TITLE
socketio error when using mbedtls adapter

### ISSUE THREAD

**Issue by alexmrtn** [Azure/azure-iot-sdk-c#1040] opened 2019-06-06 10:17 UTC
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**

Ubuntu 18.04 using GCC 7.4.0
libmbedtls 2.8.0

**SDK Version (Please Give Commit SHA if Manually Compiling)**

Release 2019-05-19

**Protocol**

MQTT and MQTT_WS

**Describe the Bug**

I was trying to use the the new support of mbedtls layer of the SDK and I encounter some errors: 

- When using MQTT protocol, the device can connect and send messages but there is some error logs from socketio_berkeley.c

- When using MQTT_WS the device can not send the connect packet and error from uws_client.c  is triggered

**[MCVE](https://stackoverflow.com/help/mcve)**

iothub_ll_telemetry_sample in the sample folder of the iothub_client

**Console Logs**

While using MQTT:
```
Creating IoTHub Device handle
Sending message 1 to IoTHub
-> 11:53:11 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 192 | USERNAME: XXXXX.azure-devices.net/XXXXX/?api-version=2017-11-08-preview&DeviceClientType=iothubclient%2f1.3.3%20(native%3b%20Linux%3b%20x86_64) | PWD: XXXX | CLEAN: 0
Sending message 2 to IoTHub
Sending message 3 to IoTHub
Sending message 4 to IoTHub
Sending message 5 to IoTHub
<- 11:53:12 CONNACK | SESSION_PRESENT: true | RETURN_CODE: 0x0
The device client is connected to iothub
-> 11:53:12 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/alexis/messages/events/property_key=property_value | PACKET_ID: 2 | PAYLOAD_LEN: 12
-> 11:53:12 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/alexis/messages/events/property_key=property_value | PACKET_ID: 3 | PAYLOAD_LEN: 12
-> 11:53:12 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/alexis/messages/events/property_key=property_value | PACKET_ID: 4 | PAYLOAD_LEN: 12
-> 11:53:12 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/alexis/messages/events/property_key=property_value | PACKET_ID: 5 | PAYLOAD_LEN: 12
-> 11:53:12 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/alexis/messages/events/property_key=property_value | PACKET_ID: 6 | PAYLOAD_LEN: 12
<- 11:53:12 PUBACK | PACKET_ID: 2
Confirmation callback received for message 1 with result IOTHUB_CLIENT_CONFIRMATION_OK
<- 11:53:12 PUBACK | PACKET_ID: 3
Confirmation callback received for message 2 with result IOTHUB_CLIENT_CONFIRMATION_OK
<- 11:53:12 PUBACK | PACKET_ID: 4
Confirmation callback received for message 3 with result IOTHUB_CLIENT_CONFIRMATION_OK
<- 11:53:12 PUBACK | PACKET_ID: 5
Confirmation callback received for message 4 with result IOTHUB_CLIENT_CONFIRMATION_OK
<- 11:53:12 PUBACK | PACKET_ID: 6
Confirmation callback received for message 5 with result IOTHUB_CLIENT_CONFIRMATION_OK
Error: Time:Thu Jun  6 11:53:12 2019 File:/tmp/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_send Line:844 Failure: socket state is not opened.
-> 11:53:12 DISCONNECT
Error: Time:Thu Jun  6 11:53:12 2019 File:/tmp/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_send Line:844 Failure: socket state is not opened.
Press any key to continue

```

While using MQTT_WS:
```
Creating IoTHub Device handle
Sending message 1 to IoTHub
Sending message 2 to IoTHub
Sending message 3 to IoTHub
Sending message 4 to IoTHub
Sending message 5 to IoTHub
-> 11:53:32 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 192 | USERNAME: XXXXX.azure-devices.net/XXXXX/?api-version=2017-11-08-preview&DeviceClientType=iothubclient%2f1.3.3%20(native%3b%20Linux%3b%20x86_64) | PWD: XXXX | CLEAN: 0
Error: Time:Thu Jun  6 11:53:32 2019 File:/tmp/azure-iot-sdk-c/c-utility/src/uws_client.c Func:on_underlying_io_send_complete Line:1897 Failing getting singlylinkedlist_item_get_value on_underlying_io_send_complete
Error: Time:Thu Jun  6 11:53:32 2019 File:/tmp/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_dowork Line:998 Socketio_Failure: Receiving data from endpoint: errno=104.
Error: Time:Thu Jun  6 11:53:32 2019 File:/tmp/azure-iot-sdk-c/c-utility/src/wsio.c Func:on_underlying_ws_error Line:451 on_underlying_ws_error called with error code 3
The device client has been disconnected
Error: Time:Thu Jun  6 11:53:32 2019 File:/tmp/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_send Line:844 Failure: socket state is not opened.
Error: Time:Thu Jun  6 11:53:32 2019 File:/tmp/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_send Line:844 Failure: socket state is not opened.
-> 11:53:33 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 192 | USERNAME: edge-ih-test.azure-devices.net/alexis/?api-version=2017-11-08-preview&DeviceClientType=iothubclient%2f1.3.3%20(native%3b%20Linux%3b%20x86_64) | PWD: XXXX | CLEAN: 0
Error: Time:Thu Jun  6 11:53:33 2019 File:/tmp/azure-iot-sdk-c/c-utility/src/uws_client.c Func:on_underlying_io_send_complete Line:1897 Failing getting singlylinkedlist_item_get_value on_underlying_io_send_complete
Error: Time:Thu Jun  6 11:53:33 2019 File:/tmp/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_dowork Line:998 Socketio_Failure: Receiving data from endpoint: errno=104.
Error: Time:Thu Jun  6 11:53:33 2019 File:/tmp/azure-iot-sdk-c/c-utility/src/wsio.c Func:on_underlying_ws_error Line:451 on_underlying_ws_error called with error code 3
The device client has been disconnected
Error: Time:Thu Jun  6 11:53:33 2019 File:/tmp/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_send Line:844 Failure: socket state is not opened.
Error: Time:Thu Jun  6 11:53:33 2019 File:/tmp/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_send Line:844 Failure: socket state is not opened.

```

**Comment by massand** [comment] 2019-06-11 22:20
@jebrando - this is a previously reported issue in c-shared-utility repo

**Comment by jebrando** [comment] 2019-07-03 23:47
@massand The First error is due to a timing error in mbedtls when closing.  I will update this to fix it.  The second error is more elusive, I will investigate and talk to our Web socket team and get a resolution.

**Comment by jebrando** [comment] 2019-07-30 16:08
Update: The Failure at disconnect is fixed, but the web socket failure is still happening.  I am working towards a solution, but I still have some information to gather.

**Comment by MatthieuLefebvre** [comment] 2019-07-30 18:02
Thx Jelani for this update.

Please keep me in the loop when they will be some progress on it.


Matthieu Lefebvre
Cloud Solution Architect
(1) 857 333 9067
Microsoft Corporation
5 Wayside Road | Burlington, MA 01803
[cid:image001.jpg@01D546DC.A65A8FC0]

Matthieu

**Comment by alexmrtn** [comment] 2019-07-31 08:18
Thanks @jebrando !

Can you confirm me which version of mbedtls you are using for validation ? I still see the Failure at disconnect when using MQTT  (no WS).

Is your fix integrated in the last release from yesterday ( 2019-07-01, tag: 1.3.4) ?

**Comment by jebrando** [comment] 2019-08-01 00:24
I'm using the mbedtls apt package version 2.8.0-1.

I've ran through the error and got a WireShark trace.  The issue is after the client makes the initial TLS connection to the server and the TLS handshack is going on, the mbedtls library fails to decode the server communication and issues an "Encrypted Alert 21" (decryption_failed you can read a little more about the error [here](https://support.symantec.com/us/en/article.tech243043.html) ).  I have not found a fix for this yet and will try to reach out to mbed to see if there is recourse for this error.  I did not check in the fix for the disconnect failure because I was trying to get this WebSocket fix in with the same check in, but I will push the disconnect fix in now (it will take a day or so to propagate through the system) and continue working the TLS failure.

**Comment by alexmrtn** [comment] 2019-08-19 09:11
Hi @jebrando 

Thanks for the update! Did you find something on this issue? Let me know if I can help or if there is a branch I can test on new changes.

**Comment by hihigupt** [comment] 2019-08-19 18:21
Hi @alexmrtn  

Can you please add following line in the [tlsio_mbedtls.c:mbedtls_init](https://github.com/Azure/azure-c-shared-utility/blob/1f3fd807c8c47b6607d349469301afb64643aa89/adapters/tlsio_mbedtls.c#L426) function and let me know if it fixes issue for you.

_mbedtls_ssl_conf_renegotiation(&tls_io_instance->config, 1);_ 


Thanks,
Himanshu

**Comment by alexmrtn** [comment] 2019-08-20 09:47
Hi, I applied the patch on the master commit and both MQTT and MQTT/WS are working!

**Comment by rafilho** [comment] 2019-08-20 17:38
Great to hear, @alexmrtn. Please use that as a workaround for now. We will submit a fix to only enable renegotiation for MQTT/WS. But at least you should be unblocked for now. Thanks.

**Comment by rafilho** [comment] 2019-09-06 22:41
This should be now fixed and propagated to master. Please reopen otherwise. Thanks.

**Comment by az-iot-builder-01** [comment] 2019-09-06 22:41
@massand, @jebrando, @hihigupt, @rafilho, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed** 2019-09-06 22:41 UTC
Labels: bug

**Comment by maskimthedog** [comment] 2019-09-09 14:44
I ran into this last fall and fixed it by adding the above mentioned call to mbedtls_ssl_conf_renegotiation().  Slipped my mind to issue a ticket.  My apologies.

**Comment by alexmrtn** [comment] 2019-09-13 07:46
Hi, I tested everything few days ago and all is working good, thanks! Just waiting the fix to be integrated into the next release :)
