### ISSUE TITLE
Is there a way to avoid serializing the full set of reported properties when dirty?

### ISSUE THREAD

**Issue by ukluk** [Azure/azure-iot-sdk-c#957] opened 2019-04-17 03:33 UTC
The function `SERIALIZE_REPORTED_PROPERTIES` expects the entire model or a  list of properties. The issue is that is not conducive to add the Dirty properties with a conditional statement. 
What is the recommendation to avoid serializing the reported properties subset when a single desired property changes?

**Comment by ewertons** [comment] 2019-04-18 17:51
By design, you twin document MUST match the serializer model.
There is no way to avoid serializing part o the properties.

**Comment by ewertons** [comment] 2019-04-23 16:50
Hi @ukluk, we will close this issue, but please feel free to reopen it if you would like to follow up.

Thanks,
Azure IoT SDK Team

**Comment by az-iot-builder-01** [comment] 2019-04-23 16:50
@ukluk, @ewertons, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed** 2019-04-23 16:50 UTC
Labels: question
