### ISSUE TITLE
[vcpkg] Cannot using vcpkg with CMAKE_TOOL_CHAIN on windows

### ISSUE THREAD

**Issue by adashen** [Azure/azure-iot-sdk-c#906] opened 2019-03-11 07:03 UTC
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**

windows 1809, cmake, vcpkg

**SDK Version (Please Give Commit SHA if Manually Compiling**

Latest SDK installed with vcpkg. (x86-windows)

**Describe the Bug**
Create a cmake file to compile my app code through CMAKE_TOOL_CHAIN. It seems find_package() cannot get the sdk.

    cmake .. -DCMAKE_TOOLCHAIN_FILE=${vcpkgpath}\scripts\buildsystems\vcpkg.cmake

There is error shown:
CMake Error at D:/repo/vcpkg/installed/x86-windows/share/cmake/azure_iot_sdks/azure_iot_sdksConfig.cmake:15 (include):
  include could not find load file:
    D:/repo/vcpkg/installed/x86-windows/share/cmake/azure_iot_sdks/azure_iot_sdksFunctions.cmake
Issue in vcpkg of azure-iot-sdk to work with vcpkg build system

**Comment by massand** [comment] 2019-03-11 18:12
@bikamani , please try the steps written by @massand and if needed talk to @markrad for guidance on tool-chain compilation.
Steps are here: https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/setting_up_vcpkg.md

**Comment by bikamani** [comment] 2019-03-12 15:55
Hi @adashen ,

I see you are using the command https://github.com/Azure/azure-iot-sdk-c/blame/master/doc/setting_up_vcpkg.md#L91

**Comment by YoDaMa** [comment] 2019-03-15 22:38
tagging with this, I was able to repro in Linux. Looks like vcpkg is not copying over our cmake functions file. Try copying from our repo into the VCPkg area:

```
cp ~/Source/azure-iot-sdk-c/configs/azure_iot_sdksFunctions.cmake ~/Source/vcpkg/installed/x86-windows/share/cmake/azure_iot_sdks/azure_iot_sdksFunctions.cmake
``` 
This got things patched when I tested it in Linux.

**Comment by adashen** [comment] 2019-03-29 02:28
Besides, we would like to build with CMake on windows. Will we fix the packaging issue and make it work on windows/cmake?

**Comment by YoDaMa** [comment] 2019-04-01 21:43
@adashen it looks like when vcpkg is pulling down our sdk, it's not setting up the references to the cmake folders correctly. I'm still in the process of debugging, but running the following lines in powershell added the proper vcpkg folders to the environment so they could be found: 

```
$ENV:CMAKE_PREFIX_PATH+="C:\GitRepos\vcpkg\installed\x86-windows\share\cmake\azure_iot_sdks;C:\GitRepos\vcpkg\installed\x86-windows\share\unofficial-parson;C:\GitRepos\vcpkg\installed\x86-windows\share\uamqp;C:\GitRepos\vcpkg\installed\x86-windows\share\umqtt;C:\GitRepos\vcpkg\installed\x86-windows\share\umqtt;"
$ENV:CMAKE_PREFIX_PATH+="C:\GitRepos\vcpkg\installed\x86-windows\share\azure_c_shared_utility"
$ENV:CMAKE_PREFIX_PATH+="C:\GitRepos\vcpkg\installed\x86-windows\share\uhttp"
```

Although after doing this I now am getting a cmake error:

```
CMake Error at CMakeLists.txt:11 (find_package):
  Found package configuration file:

    C:/GitRepos/vcpkg/installed/x86-windows/share/azure_iot_sdks/azure_iot_sdksConfig.cmake

  but it set azure_iot_sdks_FOUND to FALSE so package "azure_iot_sdks" is
  considered to be NOT FOUND.  Reason given by package:

  The following imported targets are referenced, but are missing:
  hsm_security_client prov_auth_client
```

So I'm looking more into what's causing this.

**Comment by YoDaMa** [comment] 2019-04-03 15:34
One issue we've found in the our CMakeLists.txt files has been that our `install(EXPORT ...` command for `azure_iot_sdksFunctions.cmake` is correct sometimes, incorrect other times. This matters with vcpkg and so we are ending up with half of the files in the correct vcpkg folder (`shared/azure_iot_sdks`) and some in the incorrect folder (`shared/cmake/azure_iot_sdks`).

**Comment by YoDaMa** [comment] 2019-04-22 18:34
I am going to change this from investigation-required to bug, since we know the cause is a combination of changes in the vcpkg architecture and also issues with how our cmakes install to targets.

**Comment by sagar448** [comment] 2019-07-19 22:32
Hey, has someone figured this out yet?

 I also get the "The following imported targets are referenced, but are missing:
  hsm_security_client prov_auth_client"  

Im trying to get visual studio code to work with this SDK for the esp32 ESP-IDF. Thanks!

**Comment by massand** [comment] 2019-08-22 22:33
@sagar448 Your best bet of obtaining the right libs for esp32 is the official Espressif repo.  https://github.com/espressif/esp-azure

Package managers (vcpkg, apt-get) are used for desktop builds. 

I am closing this issue, since the issue has been resolved by recent vcpkg PRs.

**Comment by az-iot-builder-01** [comment] 2019-08-22 22:33
@massand, @bikamani, @YoDaMa, @adashen, @sagar448, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed** 2019-08-22 22:33 UTC
Labels: bug
