### ISSUE TITLE
Question: Use proxy settings for create connection to IoT Hub

### ISSUE THREAD

**Issue by dehng** [Azure/azure-iot-sdk-c#346] opened 2018-01-06 15:30 UTC
- **OS and version used:** Windows Compact 2013

- **SDK version used:** Release 2017-11-17

# Description of the issue:
Hello,
is there a way to specify a proxy server (name, user, password, port)?
My IoT client is behind a firewall and must first log on to the proxy in order to establish a connection.

Currently I'm using the example 'iothub_client_sample_http' and 'iothub_client_sample_mqtt'.

Thanks.

**Comment by ewertons** [comment] 2018-01-08 22:14
Hi @dehng ,
please take a look at this sample:
https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_client_sample_upload_to_blob/iothub_client_sample_upload_to_blob.c#L63

You can set the user and password as well on that structure.
https://github.com/Azure/azure-c-shared-utility/blob/41861a7f3b6c023eda22a7ad07cc9b8489999b14/inc/azure_c_shared_utility/shared_util_options.h#L12

As the name suggests, this option is for HTTP proxy. That can be leveraged if you use our HTTP transport or any of the WebSockets-based transports ([AMQP-WS](https://github.com/Azure/azure-iot-sdk-c/tree/master/iothub_client/samples/iothub_client_sample_amqp_websockets) or [MQTT-WS](https://github.com/Azure/azure-iot-sdk-c/tree/master/iothub_client/samples/iothub_client_sample_mqtt_websockets)).

I would suggest you try using either AMQP over Websockets or MQTT over websockets if you have a client behind a firewall.

**Comment by ewertons** [comment] 2018-01-09 17:01
Oh, you are using Windows Compact 2013. I overlooked that.
I need to check our support for that version.

**Comment by dehng** [comment] 2018-01-12 06:19
Hi @ewertons,
do you have information for me?

**Comment by ewertons** [comment] 2018-01-12 19:08
Hi @dehng ,
I confirmed, and we do support the version of Windows Compact you are using.
However, proxy configuration is not implemented for that version of OS ([httpapi_wince.c](https://github.com/Azure/azure-c-shared-utility/blob/5db432502576db9f953764346298405c6a6d51b8/adapters/httpapi_wince.c)).
That would be an improvement needed to the SDK.

**Comment by dehng** [comment] 2018-01-13 13:57
Hi @everton
Is there an appointment, when the SDK supports the proxy function for http protocol?
What must be done for the AMQP-WS or MQTT-WS protocols to work under WinCE?
I need a connection to the azure over a firewall.

Thanks

**Comment by ewertons** [comment] 2018-01-16 17:35
Traditionally the alternative way to getting the websockets-based protocols to work on a system where we do not implement HTTP proxy setting in code is to configure the HTTP proxy directly on the OS.

**Comment by dehng** [comment] 2018-01-18 09:41
@ewertons.
I asked the OS Image manufacturer if this is possible. He says that this is not a problem of the OS, but should be solved in azure sdk.
Link: [https://www.toradex.com/community/questions/18696/set.proxy-settings-in-windows-compact-2013-for-use.html?childToView=18967#comment-18967](url)

Can you help me?

**Comment by jspaith** [comment] 2018-01-19 23:56
Hi @dehng - Because our CE implementation uses sockets directly and not a wrapper like Wininet, adding proxy support isn’t practical.  The only tested configuration is HTTPS for WEC 2013.  Currently there are no plans to support protocols like MQTT and AMQP, either.

One alternative can be to go with Windows IoT Core which has broader support in Azure IoT SDK. 

Sorry we don’t have a better story for you here. -- John

**Comment by dehng** [comment] 2018-01-26 14:45
Hi @jspaith ,
I looked at the file 'httpapi_wininet.c' and rebuilt it for testing so I can connect through a proxy server.
Now my connection to the cloud works.

How can I install proxy support to be 'correct'?

Call in the client:
`HTTP_PROXY_OPTIONS m_httpProxyOptions;
m_httpProxyOptions.host_address = "proxy.myAddress.com";
m_httpProxyOptions.port = 8080;
m_httpProxyOptions.username = "MyUserName";
m_httpProxyOptions.password = "MyPasswort";

resultIoClient = IoTHubClient_SetOption(m_iothubClientMainHandle, OPTION_HTTP_PROXY, &m_httpProxyOptions);`


Extension in the file httpapi_wininet.c:
`/////////////////////////////////////////
// File httpapi_wininet.c
/////////////////////////////////////////
typedef struct HTTP_HANDLE_DATA_TAG
{
    HINTERNET SessionHandle;
    HINTERNET ConnectionHandle;
	HTTP_PROXY_OPTIONS MyProxyOptions;	// new setting
} HTTP_HANDLE_DATA;

/////////////////////////////////////////
// File httpapi_wininet.c, new functions
/////////////////////////////////////////
HTTPAPI_RESULT HTTPAPI_SetOption(HTTP_HANDLE handle, const char* optionName, const void* value)
{
	HTTPAPI_RESULT result;
	if (strcmp(optionName, OPTION_HTTP_PROXY) == 0)
	{
		HTTP_PROXY_OPTIONS* proxy_options = (HTTP_PROXY_OPTIONS *)value;
		...
		result = HTTPAPI_OK;
	}
	...
}

HTTPAPI_RESULT HTTPAPI_CloneOption(const char* optionName, const void* value, const void** savedValue)
{
	HTTPAPI_RESULT result;
	if (strcmp(optionName, OPTION_HTTP_PROXY) == 0)
	{
		HTTP_PROXY_OPTIONS* proxy_options = (HTTP_PROXY_OPTIONS *)value;
		...
		result = HTTPAPI_OK;
	}
	...
}`

Is this the right way or does the option have to be set in another file?
Thanks

**Comment by jspaith** [comment] 2018-02-01 17:08
You're correct - the SetOption & CloneOption are the places you need to wire up to make this work. 

Were you having issues with this (it sounds like no?) or were you just double checking, in which case all should be well.

**Comment by jspaith** [comment] 2018-02-08 18:45
@dehng  - since this thread has been quiet for a bit, I'm going to close it but as always if there's more to discuss by all means re-open it or create a new one.

**Closed by jspaith** 2018-02-08 18:45 UTC
Labels: question

**Comment by mohamedibrahimabdelrahman33** [comment] 2018-05-20 13:28
hey guys, i want to ask you a question, how to use "http_proxy_io" with "httpapi_compact"?
currently i'm using HTTP protocol to send and receive, and i want to use proxy configuration.

**Comment by dehng** [comment] 2018-06-05 08:19
Hi @mohamedibrahimabdelrahman33,
I replaced the file httpapi_wince with the file httpapi_wininet.
In this file I have added the extensions for access with a proxy server.

``

**Comment by rkathire** [comment] 2018-06-26 20:15
We are trying to do the same. Is there a sample for windows?

**Comment by dehng** [comment] 2018-06-27 05:27
@rkathire, i used the the standard api for using wininet and use it on windows compact.

**Comment by ewertons** [comment] 2018-06-28 20:30
Parson doesn't have nugets published, however we pack it in our nugets for now.
If you search under your solution folder, look for a "packages" folder. Inside that, look for parson.lib.

All you need in VS is to add the path to parson.lib into the Linker additional libraries:
<project> / Properties / Linker / Input / Additional Dependencies

**Comment by mohamedibrahimabdelrahman33** [comment] 2018-07-01 07:56
Thanks @dehng for your effort, but actually i'm using "httpapi_compact" not "httpapi_wince".
currently i'm working on STM32F7 platform.
