### ISSUE TITLE
Downstream device connects to IoTHub instead of IoT Edge gateway

### ISSUE THREAD

**Issue by wickste** [Azure/azure-iot-sdk-c#865] opened 2019-02-13 17:52 UTC
- **OS and version used:** Ubuntu 18.04 

- **SDK version used:** https://github.com/Azure/azure-iot-sdk-c/releases/tag/2019-01-31 

# Description of the issue:

I am trying to connect a downstream device to my IoT Edge gateway. I am using this guide: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-connect-downstream-device#use-certificates-with-azure-iot-sdks

My starting point is the iotedge_downstream_device_sample sample from the C-SDK:
https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iotedge_downstream_device_sample/iotedge_downstream_device_sample.c

## Problem  
The C SDK/Sample happily reports “The device client is connected to IoT Edge” and the messages are sent out fine –however: the device actually connects to my IoTHub instead of the configured IoT Edge gateway. Even if I supply a bad cert, or configure a non-existing GatewayHostname I don’t get any errors, and the device just sends data to the IoTHub directly.

# Code sample exhibiting the issue:

The issue can be reproduced with the iotedge_downstream_device_sample from this SDK. No additional code needed.

# Console log of the issue:

```
This sample will send 20 messages and wait for any C2D messages.
Press the enter key to end the sample

Creating IoTHub handle

Sending message 1 to Edge Hub
Sending message 2 to Edge Hub
Sending message 3 to Edge Hub
Sending message 4 to Edge Hub
Sending message 5 to Edge Hub
Sending message 6 to Edge Hub
Sending message 7 to Edge Hub
Sending message 8 to Edge Hub
Sending message 9 to Edge Hub
Sending message 10 to Edge Hub
Sending message 11 to Edge Hub
Sending message 12 to Edge Hub
Sending message 13 to Edge Hub
Sending message 14 to Edge Hub
Sending message 15 to Edge Hub
Sending message 16 to Edge Hub
Sending message 17 to Edge Hub
Sending message 18 to Edge Hub
Sending message 19 to Edge Hub
Sending message 20 to Edge Hub

Press any key to continue
-> 20:30:03 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 192 | USERNAME: [IoTHubName].azure-devices.net/[DeviceId]/?api-version=2017-11-08-preview&DeviceClientType=iothubclient%2f1.2.13%20(native%3b%20Linux%3b%20x86_64) | PWD: XXXX | CLEAN: 0
<- 20:30:03 CONNACK | SESSION_PRESENT: true | RETURN_CODE: 0x0
The device client is connected to IoT Edge
-> 20:30:03 SUBSCRIBE | PACKET_ID: 2 | TOPIC_NAME: devices/LeafLinux/messages/devicebound/# | QOS: 1
-> 20:30:03 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/LeafLinux/messages/events/property_key=property_value&%24.cid=CORE_ID&%24.mid=MSG_ID&%24.ct=application%2fjson&%24.ce=utf-8 | PACKET_ID: 3 | PAYLOAD_LEN: 12
-> 20:30:03 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/LeafLinux/messages/events/property_key=property_value&%24.cid=CORE_ID&%24.mid=MSG_ID&%24.ct=application%2fjson&%24.ce=utf-8 | PACKET_ID: 4 | PAYLOAD_LEN: 12
-> 20:30:03 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/LeafLinux/messages/events/property_key=property_value&%24.cid=CORE_ID&%24.mid=MSG_ID&%24.ct=application%2fjson&%24.ce=utf-8 | PACKET_ID: 5 | PAYLOAD_LEN: 12
-> 20:30:03 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/LeafLinux/messages/events/property_key=property_value&%24.cid=CORE_ID&%24.mid=MSG_ID&%24.ct=application%2fjson&%24.ce=utf-8 | PACKET_ID: 6 | PAYLOAD_LEN: 12
-> 20:30:03 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/LeafLinux/messages/events/property_key=property_value&%24.cid=CORE_ID&%24.mid=MSG_ID&%24.ct=application%2fjson&%24.ce=utf-8 | PACKET_ID: 7 | PAYLOAD_LEN: 12
-> 20:30:03 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/LeafLinux/messages/events/property_key=property_value&%24.cid=CORE_ID&%24.mid=MSG_ID&%24.ct=application%2fjson&%24.ce=utf-8 | PACKET_ID: 8 | PAYLOAD_LEN: 12
-> 20:30:03 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/LeafLinux/messages/events/property_key=property_value&%24.cid=CORE_ID&%24.mid=MSG_ID&%24.ct=application%2fjson&%24.ce=utf-8 | PACKET_ID: 9 | PAYLOAD_LEN: 12
-> 20:30:03 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/LeafLinux/messages/events/property_key=property_value&%24.cid=CORE_ID&%24.mid=MSG_ID&%24.ct=application%2fjson&%24.ce=utf-8 | PACKET_ID: 10 | PAYLOAD_LEN: 12
-> 20:30:03 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/LeafLinux/messages/events/property_key=property_value&%24.cid=CORE_ID&%24.mid=MSG_ID&%24.ct=application%2fjson&%24.ce=utf-8 | PACKET_ID: 11 | PAYLOAD_LEN: 12
-> 20:30:03 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/LeafLinux/messages/events/property_key=property_value&%24.cid=CORE_ID&%24.mid=MSG_ID&%24.ct=application%2fjson&%24.ce=utf-8 | PACKET_ID: 12 | PAYLOAD_LEN: 12
-> 20:30:03 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/LeafLinux/messages/events/property_key=property_value&%24.cid=CORE_ID&%24.mid=MSG_ID&%24.ct=application%2fjson&%24.ce=utf-8 | PACKET_ID: 13 | PAYLOAD_LEN: 12
-> 20:30:03 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/LeafLinux/messages/events/property_key=property_value&%24.cid=CORE_ID&%24.mid=MSG_ID&%24.ct=application%2fjson&%24.ce=utf-8 | PACKET_ID: 14 | PAYLOAD_LEN: 12
-> 20:30:03 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/LeafLinux/messages/events/property_key=property_value&%24.cid=CORE_ID&%24.mid=MSG_ID&%24.ct=application%2fjson&%24.ce=utf-8 | PACKET_ID: 15 | PAYLOAD_LEN: 12
-> 20:30:03 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/LeafLinux/messages/events/property_key=property_value&%24.cid=CORE_ID&%24.mid=MSG_ID&%24.ct=application%2fjson&%24.ce=utf-8 | PACKET_ID: 16 | PAYLOAD_LEN: 12
-> 20:30:03 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/LeafLinux/messages/events/property_key=property_value&%24.cid=CORE_ID&%24.mid=MSG_ID&%24.ct=application%2fjson&%24.ce=utf-8 | PACKET_ID: 17 | PAYLOAD_LEN: 12
-> 20:30:03 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/LeafLinux/messages/events/property_key=property_value&%24.cid=CORE_ID&%24.mid=MSG_ID&%24.ct=application%2fjson&%24.ce=utf-8 | PACKET_ID: 18 | PAYLOAD_LEN: 12
-> 20:30:03 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/LeafLinux/messages/events/property_key=property_value&%24.cid=CORE_ID&%24.mid=MSG_ID&%24.ct=application%2fjson&%24.ce=utf-8 | PACKET_ID: 19 | PAYLOAD_LEN: 12
-> 20:30:03 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/LeafLinux/messages/events/property_key=property_value&%24.cid=CORE_ID&%24.mid=MSG_ID&%24.ct=application%2fjson&%24.ce=utf-8 | PACKET_ID: 20 | PAYLOAD_LEN: 12
-> 20:30:03 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/LeafLinux/messages/events/property_key=property_value&%24.cid=CORE_ID&%24.mid=MSG_ID&%24.ct=application%2fjson&%24.ce=utf-8 | PACKET_ID: 21 | PAYLOAD_LEN: 12
-> 20:30:03 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/LeafLinux/messages/events/property_key=property_value&%24.cid=CORE_ID&%24.mid=MSG_ID&%24.ct=application%2fjson&%24.ce=utf-8 | PACKET_ID: 22 | PAYLOAD_LEN: 12
<- 20:30:03 SUBACK | PACKET_ID: 2 | RETURN_CODE: 1
<- 20:30:03 PUBACK | PACKET_ID: 3
Confirmation callback received for message 1 with result IOTHUB_CLIENT_CONFIRMATION_OK
<- 20:30:03 PUBACK | PACKET_ID: 4
Confirmation callback received for message 2 with result IOTHUB_CLIENT_CONFIRMATION_OK
<- 20:30:03 PUBACK | PACKET_ID: 5
Confirmation callback received for message 3 with result IOTHUB_CLIENT_CONFIRMATION_OK
<- 20:30:03 PUBACK | PACKET_ID: 6
Confirmation callback received for message 4 with result IOTHUB_CLIENT_CONFIRMATION_OK
<- 20:30:03 PUBACK | PACKET_ID: 7
Confirmation callback received for message 5 with result IOTHUB_CLIENT_CONFIRMATION_OK
<- 20:30:03 PUBACK | PACKET_ID: 8
Confirmation callback received for message 6 with result IOTHUB_CLIENT_CONFIRMATION_OK
<- 20:30:03 PUBACK | PACKET_ID: 9
Confirmation callback received for message 7 with result IOTHUB_CLIENT_CONFIRMATION_OK
<- 20:30:03 PUBACK | PACKET_ID: 10
Confirmation callback received for message 8 with result IOTHUB_CLIENT_CONFIRMATION_OK
<- 20:30:03 PUBACK | PACKET_ID: 11
Confirmation callback received for message 9 with result IOTHUB_CLIENT_CONFIRMATION_OK
<- 20:30:03 PUBACK | PACKET_ID: 12
Confirmation callback received for message 10 with result IOTHUB_CLIENT_CONFIRMATION_OK
<- 20:30:03 PUBACK | PACKET_ID: 13
Confirmation callback received for message 11 with result IOTHUB_CLIENT_CONFIRMATION_OK
<- 20:30:04 PUBACK | PACKET_ID: 14
Confirmation callback received for message 12 with result IOTHUB_CLIENT_CONFIRMATION_OK
<- 20:30:04 PUBACK | PACKET_ID: 15
Confirmation callback received for message 13 with result IOTHUB_CLIENT_CONFIRMATION_OK
<- 20:30:04 PUBACK | PACKET_ID: 16
Confirmation callback received for message 14 with result IOTHUB_CLIENT_CONFIRMATION_OK
<- 20:30:04 PUBACK | PACKET_ID: 17
Confirmation callback received for message 15 with result IOTHUB_CLIENT_CONFIRMATION_OK
<- 20:30:04 PUBACK | PACKET_ID: 18
Confirmation callback received for message 16 with result IOTHUB_CLIENT_CONFIRMATION_OK
<- 20:30:04 PUBACK | PACKET_ID: 19
Confirmation callback received for message 17 with result IOTHUB_CLIENT_CONFIRMATION_OK
<- 20:30:04 PUBACK | PACKET_ID: 20
Confirmation callback received for message 18 with result IOTHUB_CLIENT_CONFIRMATION_OK
<- 20:30:04 PUBACK | PACKET_ID: 21
Confirmation callback received for message 19 with result IOTHUB_CLIENT_CONFIRMATION_OK
<- 20:30:04 PUBACK | PACKET_ID: 22
Confirmation callback received for message 20 with result IOTHUB_CLIENT_CONFIRMATION_OK
-> 20:30:19 DISCONNECT


```

**Comment by jspaith** [comment] 2019-02-15 17:48
You have GatewayHostname, but the correct value is GatewayHostName – note the capital ‘N’ in name.  This is why the argument is ignored and you’re always hitting the hub.

In the perfect world I’d make the client just fail if it doesn’t recognize a value, but thanks to back-compat I’m afraid to do that.  We could argue whether it should be a stricmp() instead of strcmp(), but again my fear would be someone did what you’re doing and has a happily working system of ‘n’, not ‘N’. And then they push updated SDK and we accept the ‘n’ and it turns out the gateway all of a sudden we start parsing is bogus and breaks stuff.

I think what we should do though is LogError() when we don’t recognize output (along with a note that the error is going to be ignored and we'll keep on parsing).

If anyone in community has any thoughts, feel free to jump onto this thread.

**Comment by jspaith** [comment] 2019-03-06 23:21
I'm resolving this, because we've understood root cause (case sensitivity) and added the log error (d6aca1f0c1533a6ac06371a12652206470324e15).

**Comment by az-iot-builder-01** [comment] 2019-03-06 23:21
@wickste, @jspaith, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed** 2019-03-06 23:21 UTC
Labels: investigation-required
