### ISSUE TITLE
c2d sample repeatedly disconnects when switched to x509 certs

### ISSUE THREAD

**Issue by larsonmpdx** [Azure/azure-iot-sdk-c#1827] opened 2021-01-14 18:23 UTC
**Development Machine, OS, Compiler (and Other Relevant Toolchain Info)**

ubuntu 16.04 64-bit PC

**SDK Version (Please Give Commit SHA if Manually Compiling)**

Release 2020-12-09

**Protocol**

MQTT

**Describe the Bug**

The ll_c2d sample works fine with a symmetric key in the connection string, but switching it to x509 (by copying lines from the ll_client_x509 sample) causes it to disconnect right after subscribing.  The sample then quickly connects/disconnects as fast as dowork() is called.  iot hub logs show something like this (see picture) for each disconnect, I think this means it's a client side disconnect?  But I'm not sure, a huge variety of mqtt errors cause a sudden disconnect on the server side with little info given, so it could be that.

my x509 key/test setup works fine if I turn off c2d message reception (by commenting out the SetMessageCallback() lines in this sample).  in that case the sample will just connect and then loop and do nothing (and not disconnect)

![image](https://user-images.githubusercontent.com/12436438/104631423-146d9e00-5651-11eb-84a5-d0a5d7509400.png)

**[MCVE](https://stackoverflow.com/help/mcve)**

see my diff here, this is the ll_c2d sample with a few lines brought in from the ll_client_x509 sample
https://github.com/Azure/azure-iot-sdk-c/compare/master...larsonmpdx:c2d_x509_problem

**Console Logs**

~/azure-iot-sdk-c/cmake-build$ ./iothub_client/samples/iothub_ll_c2d_sample/iothub_ll_c2d_sample 
Creating IoTHub Device handle
Waiting for message to be sent to device (will quit after 3 messages)
-> 09:51:32 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 128 | USERNAME: hub-name.azure-devices.net/ee6a91e0-616a-11e9-a9fa-f94afb08b3d1/?api-version=2020-09-30&DeviceClientType=iothubclient%2f1.5.0%20(native%3b%20Linux%3b%20x86_64) | CLEAN: 0
<- 09:51:32 CONNACK | SESSION_PRESENT: true | RETURN_CODE: 0x0
-> 09:51:32 SUBSCRIBE | PACKET_ID: 2 | TOPIC_NAME: devices/ee6a91e0-616a-11e9-a9fa-f94afb08b3d1/messages/devicebound/# | QOS: 1
-> 09:51:32 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 128 | USERNAME: hub-name.azure-devices.net/ee6a91e0-616a-11e9-a9fa-f94afb08b3d1/?api-version=2020-09-30&DeviceClientType=iothubclient%2f1.5.0%20(native%3b%20Linux%3b%20x86_64) | CLEAN: 0
<- 09:51:32 CONNACK | SESSION_PRESENT: true | RETURN_CODE: 0x0
-> 09:51:32 SUBSCRIBE | PACKET_ID: 3 | TOPIC_NAME: devices/ee6a91e0-616a-11e9-a9fa-f94afb08b3d1/messages/devicebound/# | QOS: 1
-> 09:51:32 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 128 | USERNAME: hub-name.azure-devices.net/ee6a91e0-616a-11e9-a9fa-f94afb08b3d1/?api-version=2020-09-30&DeviceClientType=iothubclient%2f1.5.0%20(native%3b%20Linux%3b%20x86_64) | CLEAN: 0
<- 09:51:33 CONNACK | SESSION_PRESENT: true | RETURN_CODE: 0x0
-> 09:51:33 SUBSCRIBE | PACKET_ID: 4 | TOPIC_NAME: devices/ee6a91e0-616a-11e9-a9fa-f94afb08b3d1/messages/devicebound/# | QOS: 1
-> 09:51:33 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 128 | USERNAME: hub-name.azure-devices.net/ee6a91e0-616a-11e9-a9fa-f94afb08b3d1/?api-version=2020-09-30&DeviceClientType=iothubclient%2f1.5.0%20(native%3b%20Linux%3b%20x86_64) | CLEAN: 0
<- 09:51:33 CONNACK | SESSION_PRESENT: true | RETURN_CODE: 0x0

etc...

connect/disconnect repeats quickly, I didn't add the connection callback to the demo but when I tested it the disconnect reason was IOTHUB_CLIENT_CONNECTION_NO_NETWORK

**Comment by danewalton** [comment] 2021-01-14 18:43
At quick glance, I do notice in your sample that the necessary connection string for x509 auth is not correct. Line 48 should be something like
```c
static const char* connectionString = "HostName=<host_name>;DeviceId=<device_id>;x509=true";
```
but its currently
```c
static const char* connectionString = "[device connection string]";
```

**Comment by larsonmpdx** [comment] 2021-01-14 19:19
that's a demo string.  it's correct when I run it.  it wouldn't do to put my private info into the sample

**Comment by danewalton** [comment] 2021-01-15 01:42
Could you take a look at the docs here and let me know if any of the causes sound familiar?
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-troubleshoot-error-409002-linkcreationconflict#:~:text=In%20the%20most%20common%20case,%20a%20separate%20issue,previous%20connection%20and%20logs%20this%20error.%20Cause%202

**Comment by larsonmpdx** [comment] 2021-01-15 02:09
It doesn't look like iot hub is detecting multiple connections, I don't see error 409002 in my logs.  It looks like it cleanly closes each connection even though there are a few per second once it gets into a failing loop

Reproducing this should be something like, make an iot hub, standard tier so it includes c2d messages. Create a self-signed x509 key/certificate. Add a device to iot hub and associate the certificate (I think you put in the cert signature? I can get you some examples.)  Set up my sample on linux and get it building. Paste your key/cert/connection string into my example and build and test.

**Comment by danewalton** [comment] 2021-01-15 19:08
Ahh I linked the wrong doc sorry. Here is the one I meant:
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-troubleshoot-error-404104-deviceconnectionclosedremotely

Relevant causes could be:
>Some possibilities include:
> - The device lost underlying network connectivity longer than the MQTT keep-alive, resulting in a remote idle timeout. The MQTT keep-alive setting can be different per device.
> - The device sent a TCP/IP-level reset but didn't send an application-level MQTT DISCONNECT. Basically, the device abruptly closed the underlying socket connection. Sometimes, this issue is caused by bugs in older versions of the Azure IoT SDK.
> - The device side application crashed.

I did try to repro and I don't seem to be hitting the same problem. I have an S1 hub with a self-signed cert device able to connect and receive C2D messages. Do any of the above causes ring true?

**Comment by danewalton** [comment] 2021-01-15 19:55
Interesting so looking at the logs, the subscribe seems like it's getting rejected here:
![customer](https://user-images.githubusercontent.com/36710865/104772520-6a614500-5728-11eb-82d9-591eaf93b683.png)

Compared to mine which looks like this:
![mine](https://user-images.githubusercontent.com/36710865/104772522-6af9db80-5728-11eb-84bc-d26f4dd582ce.png)

Let me ask around and see why this might be happening

**Comment by ericwol-msft** [comment] 2021-01-15 22:08
Can you try deleting the device from the hub and re-add it?

**Comment by larsonmpdx** [comment] 2021-01-21 20:50
ok I tried deleting and recreating, no change

**Comment by danewalton** [comment] 2021-04-02 01:40
long shot but can you pull the latest and take on this change:
https://github.com/Azure/azure-iot-sdk-c/pull/1894

I don't think this will have an effect since the MQTT connection looks to be going through but since I don't have much else right now curious if it helps.

**Comment by danewalton** [comment] 2021-04-12 23:29
Hey @larsonmpdx I'm going to go ahead and close this for now. Please let us know if you would like it reopened

**Closed by danewalton** 2021-04-12 23:29 UTC
Labels: IoTSDK, waiting-for-author-feedback
