### ISSUE TITLE
Cannot find -lparson

### ISSUE THREAD

**Issue by zambranohally** [Azure/azure-iot-sdk-c#2487] opened 2023-05-23 17:08 UTC
I have a cross platform project that will use iothub in c++.
I am using Visual Studio 2022 together cmake and vcpkg.
install the latest release for vcpkg.
Below are my steps in installing the azure-iot-sdk-c.

```
- ./vcpkg install azure-iot-sdk-c:x64-linux

- After the installation I updated the cmakelists.txt and add the following
find_package(azure_iot_sdks CONFIG REQUIRED)
target_link_libraries(vianad PRIVATE iothub_client serializer prov_auth_client hsm_security_client)

- Below is the screenshot of the cmake generation.
![image](https://github.com/Azure/azure-iot-sdk-c/assets/63218980/9d2046be-5c8d-42bd-b6d0-3a48835011d3)

- When I build the code, I got this error
![image](https://github.com/Azure/azure-iot-sdk-c/assets/63218980/05d3906d-ee1a-4d66-8f21-c4641531938a)

```

**Comment by ericwol-msft** [comment] 2023-05-23 17:53
You need to install the parson vcpkg package.

```
C:\Repos\vcpkg>vcpkg search parson
parson                   2022-11-13       a lightweight json library written in C
```

**Comment by zambranohally** [comment] 2023-05-24 02:54
@ericwol-msft Thank you for your reply.
I did install parson and also added it to cmakelists.txt but still the error persist.

**Comment by ericwol-msft** [comment] 2023-05-24 22:32
dump your linker paths and see what is going on.

**Comment by zambranohally** [comment] 2023-05-25 15:14
@ericwol-msft 
I am using cmake all of my other libraries are working except azure iot.

**Comment by ericwol-msft** [comment] 2023-05-25 19:01
You can use cmake options-`-debug-output` and `--trace ` to debug your cmake.

**Comment by zambranohally** [comment] 2023-05-26 17:19
@ericwol-msft 
This is what I got.
![image](https://github.com/Azure/azure-iot-sdk-c/assets/63218980/fd5b2132-a0f8-4cd9-92a6-c4af982b2aee)

**Comment by zambranohally** [comment] 2023-05-31 03:52
@ericwol-msft sorry for my previous post but that was already solve. I mistakenly paste the wrong screenshot.
Please can you help me what is wrong, what am I lacking. I already added parson in cmakelists still the error persist. 

`root@xxx:/mnt/e/c++/xxx# cmake --build /root/.vs/xxx/out/build/linux-debug --target xxx--config Debug --verbose
[1/1] : && /usr/bin/g++ -g  CMakeFiles/xxx.dir/sources/xxx.cpp.o CMakeFiles/vianad.dir/sources/db_config.cpp.o CMakeFiles/vianad.dir/sources/api.cpp.o CMakeFiles/xxx.dir/sources/options.cpp.o CMakeFiles/xxx.dir/sources/cli.cpp.o CMakeFiles/xxx.dir/sources/m_device.cpp.o CMakeFiles/xxx.dir/sources/heartbeat.cpp.o CMakeFiles/xxx.dir/sources/m_heartbeat.cpp.o CMakeFiles/xxx.dir/sources/device.cpp.o CMakeFiles/xxx.dir/sources/camera.cpp.o CMakeFiles/xxx.dir/sources/m_camera.cpp.o CMakeFiles/xxx.dir/sources/m_rss_payload.cpp.o CMakeFiles/xxx.dir/sources/mqtt.cpp.o CMakeFiles/xxx.dir/sources/mqtt_callback.cpp.o CMakeFiles/xxx.dir/sources/command_queue.cpp.o CMakeFiles/xxx.dir/sources/command_consumer.cpp.o -o xxx /mnt/e/vcpkg/installed/x64-linux/debug/lib/libiothub_client.a  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libserializer.a  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libprov_auth_client.a  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libhsm_security_client.a  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libboost_program_options.a  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libspdlogd.a  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libpaho-mqttpp3.a  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libpaho-mqtt3as.a  -luuid  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libuhttp.a  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libiothub_client_http_transport.a  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libiothub_client_amqp_transport.a  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libiothub_client_amqp_ws_transport.a  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libuamqp.a  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libssl.a  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libcrypto.a  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libiothub_client_mqtt_transport.a  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libiothub_client_mqtt_ws_transport.a  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libumqtt.a  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libaziotsharedutil.a  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libcurl-d.a  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libz.a  -lm  -lparson  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libfmtd.a  -lstdc++  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libpaho-mqtt3cs.a  -lc  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libssl.a  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libcrypto.a  -lpthread  -ldl  -lpthread  -lrt  -lanl && :
FAILED: xxx
: && /usr/bin/g++ -g  CMakeFiles/xxx.dir/sources/vianad.cpp.o CMakeFiles/xxx.dir/sources/db_config.cpp.o CMakeFiles/xxx.dir/sources/api.cpp.o CMakeFiles/vianad.dir/sources/options.cpp.o CMakeFiles/vianad.dir/sources/cli.cpp.o CMakeFiles/xxx.dir/sources/m_device.cpp.o CMakeFiles/xxx.dir/sources/heartbeat.cpp.o CMakeFiles/xxx.dir/sources/m_heartbeat.cpp.o CMakeFiles/xxx.dir/sources/device.cpp.o CMakeFiles/xxx.dir/sources/camera.cpp.o CMakeFiles/xxx.dir/sources/m_camera.cpp.o CMakeFiles/xxx.dir/sources/m_rss_payload.cpp.o CMakeFiles/xxx.dir/sources/mqtt.cpp.o CMakeFiles/xxx.dir/sources/mqtt_callback.cpp.o CMakeFiles/xxx.dir/sources/command_queue.cpp.o CMakeFiles/xxx.dir/sources/command_consumer.cpp.o -o xxx /mnt/e/vcpkg/installed/x64-linux/debug/lib/libiothub_client.a  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libserializer.a  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libprov_auth_client.a  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libhsm_security_client.a  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libboost_program_options.a  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libspdlogd.a  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libpaho-mqttpp3.a  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libpaho-mqtt3as.a  -luuid  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libuhttp.a  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libiothub_client_http_transport.a  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libiothub_client_amqp_transport.a  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libiothub_client_amqp_ws_transport.a  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libuamqp.a  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libssl.a  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libcrypto.a  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libiothub_client_mqtt_transport.a  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libiothub_client_mqtt_ws_transport.a  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libumqtt.a  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libaziotsharedutil.a  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libcurl-d.a  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libz.a  -lm  -lparson  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libfmtd.a  -lstdc++  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libpaho-mqtt3cs.a  -lc  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libssl.a  /mnt/e/vcpkg/installed/x64-linux/debug/lib/libcrypto.a  -lpthread  -ldl  -lpthread  -lrt  -lanl && :
/usr/bin/ld: cannot find -lparson
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.`

**Comment by CIPop** [comment] 2023-08-04 23:50
@RLeclair, @vaavva and I looked at this today. The issue is that cmake does not detect the path: `-lparson` instead of something on the lines of 
`/mnt/e/vcpkg/installed/x64-linux/debug/lib/libparson.a`.

We couldn't find anything that changed in our library. My suspicion is that https://github.com/microsoft/vcpkg/pull/27885 might have changed something that we need to update on our side.

**Comment by dg0yt** [comment] 2023-08-06 08:10
> We couldn't find anything that changed in our library. My suspicion is that [microsoft/vcpkg#27885](https://github.com/microsoft/vcpkg/pull/27885) might have changed something that we need to update on our side.

What [microsoft/vcpkg#27885](https://github.com/microsoft/vcpkg/pull/27885) changed is that instead of creating `parson` as an alias target for vcpkg's proprietary `unofficial::parson::parson`, it now relies on parson's official cmake config which provides an imported target `parson::parson`.

So in vcpkg, azure-iot-sdk-c's use of `target_link_libraries(... parson::parson)` is no longer backed by a target with location properties. And due to absence of a `namespace::`, CMake can't offer good diagnostics but must pass `parson` as namespec to the linker (`-lparson`). Which may or may not find some matching lib, and not necessarily at the location provided by `find_package(parson CONFIG REQUIRED)`.

So the bug is here, indeed, and you need to update how the projects links to parson in CMake, in this and other spots:
https://github.com/Azure/azure-iot-sdk-c/blob/97fef570416467598100b782ef27ceadad9ca796/serializer/CMakeLists.txt#L71
should become
~~~cmake
target_link_libraries(serializer parson::parson) 
~~~
(And maybe it would be good to start using the `PUBLIC`/`PRIVATE`/`INTERFACE` keywords, but this has a larger scope.)

**Comment by CIPop** [comment] 2023-08-10 22:34
Thank you @dg0yt for your detailed answer and the fix in VCPKG!

In the future, we plan to add VCPKG support within the library itself (instead of maintaining .patch files in VCPKG) as well as a CI step that uses VCPKG (to detect issues faster instead of just during our release workflow).

@zambranohally this issue should be fixed within [LTS_08_2023](https://github.com/Azure/azure-iot-sdk-c/releases/tag/LTS_08_2023)

**Closed by CIPop** 2023-08-10 22:34 UTC
Labels: IoTSDK, waiting-for-author-feedback
