### ISSUE TITLE
SDK doesn't reconnect after connection loss over MQTT protocol

### ISSUE THREAD

**Issue by Morozov-5F** [Azure/azure-iot-sdk-c#213] opened 2017-08-18 15:16 UTC
- **OS and version used:** Linux OpenWrt 3.18.29 mips GNU/Linux 

- **SDK version used:** IoT Hub SDK for C, version 1.1.21

# Description of the issue:
I've updated to latest Azure IoT SDK on my device from 1.1.14 to 1.1.21 and experienced the following issue: it looks like IoT Hub SDK for C is unable to reconnect after connection loss over MQTT protocol, for example, when it loses Internet access.  

For instance, if SDK loses connection to Azure servers due to Internet connection problem, when Internet access is back again, it cannot establish a connection to servers -- SDK returns `IOTHUB_CLIENT_CONNECTION_DEVICE_DISABLED` as a connection status. Also, it keeps trying to reconnect, but with no success. 

I'm using x509 authentification, 60s MQTT keepAlive ping and `IOTHUB_CLIENT_RETRY_INTERVAL` retry policy without a maximum limit. The device is connected to the internet over Wi-Fi. It sends JSON messages and updates properties using device twin.

# Code sample exhibiting the issue:
I will provide only the most important parts of code: 

- [Azure SDK initialization](https://gist.github.com/Morozov-5F/fa6c90f32c73da9c8d7aa840447f8354)
- [Connection status management](https://gist.github.com/Morozov-5F/fffd9c750d9ba070798293435a6fcc96)

I'm not sure if this is enough, so let me know if more information needed.

# Console log of the issue:
The full log is available by link:
- [Azure log](https://gist.github.com/Morozov-5F/d5f9b098e536fc3f870952c1f54242b0)

Please note that I've included timings when Internet connection has been lost in file [internet_timings.txt](https://gist.github.com/Morozov-5F/d5f9b098e536fc3f870952c1f54242b0#file-internet_timings-txt).

**Comment by sarangkalbande** [comment] 2017-08-24 15:58
Guys, I faced these issue many times and solving one issue gives birth to another.
I never faced any issues with Ethernet connectivity since its very stable but wifi and cellular
I faced lots of similar issues.
The workaround for this whenever connectivity goes down or if there are no send confirmations for continuous 4-5 messages for some time then It's better to reset the connection handle and things starts to work again as expected.

**Comment by Morozov-5F** [comment] 2017-08-25 08:38
@sarangkalbande thanks for pointing that out. Currently, I use an older version of SDK and I'm waiting for this issue to be fixed. I tried to find out what was happening in order to fix this issue by myself, but I couldn't find a problem reason.

**Comment by ewertons** [comment] 2017-09-29 22:52
Hi @Morozov-5F,

I just verified the reconnection using MQTT transport and X509 certs for device authentication, and it is working as expected. Tested on a Linux Ubuntu system.

Thanks for the complete traces and extra details!
Just to confirm, did you modify the logs to hide the actual values of host_name, device_id?

Your logs shows that the client tried to reconnect and was able to establish a TLS connection, but it failed to authenticate the device:

Error: Time:Fri Aug 18 14:47:35 2017 File:azure_sdk/iothub_client/src/iothubtransport_mqtt_common.c Func:mqtt_operation_complete_callback Line:1161 Connection Not Accepted: 0x5: Not Authorized

After this failure, did you try:
1. killing the sample, and
2. Running it again using the same authentication info (connection string and cert)
?

To verify if the certificate was still good?

We will need some extra info to dig into this.

**Comment by kiranpradeep** [comment] 2017-10-10 11:25
@ewertons With iothub_client_sample_mqtt([1](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_client_sample_mqtt/iothub_client_sample_mqtt.c)), we could reproduce this issue even on Ethernet on Ubuntu Linux LTS.  But if the network disconnection is for a short duration of time( say 10 minutes to 2 hours ), the mqtt reconnection happens quickly.

When we try extending the network disconnection period to around 15 hours( disconnected ethernet cable for 15 hours and then reconnected ),  and in order to reconnect, it takes around 2 hours( after which `SendConfirmationCallback` return success ). Please let know if I could share any logs which could help. I use the iothub_client_sample_mqtt([1](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_client_sample_mqtt/iothub_client_sample_mqtt.c)) and modified it to publish messages every 5 minutes.

**Comment by ewertons** [comment] 2017-10-10 16:12
@kiranpradeep , this is a good additional piece of information.
So it doesn't mean that you don't get reconnected at all, it means it takes a lot of time to reconnect?

Are you aware that the IoTHubClient has a feature called Retry Policy? The default retry policy is EXPONENTIAL_BACKOFF_WITH_JITTER. It means that if there is a disconnection, the client will retry connecting within 1 second, then 2 secs, 4, 8, ... eventually taking a long time (hours) if the connection has been disrupted for too long. 
The exponential retry policy is not recommended for connections that stay offline for too long (several minutes). 

You can control the retry policy by using this [API function](https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/inc/iothub_client_ll.h#L375).

Could you try setting it to a more aggressive retry policy (IOTHUB_CLIENT_RETRY_INTERVAL or IOTHUB_CLIENT_RETRY_IMMEDIATE) and see if the issue gets resolved?

**Comment by ewertons** [comment] 2017-10-10 16:34
@Morozov-5F , could you verify if the issue you are experiencing relates to the retry policy as well please?

**Comment by taroyutao** [comment] 2017-10-17 06:03
I faced these issue too, does this issue can been fixed in next release？

**Comment by taroyutao** [comment] 2017-10-17 06:05
I faced these issue too, does this issue can been fixed in next Version？

**Comment by ewertons** [comment] 2017-11-09 21:46
Hi @Morozov-5F and @taroyutao ,
this was confirmed as an issue and fixed some time ago.
By the last time I replied I was not aware of the fix, sorry for that.

On a Linux machine I got a repro of the issue using Azure IoT C SDK version 1.1.21 (same as your original post):

```bash
Starting the IoTHub client sample x509...
Info: IoT Hub SDK for C, version 1.1.21
...
Error: Time:Thu Nov  9 13:33:47 2017 File:/home/ewerton/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:tlsio_openssl_open Line:1202 Failed opening the underlying I/O.
Error: Time:Thu Nov  9 13:33:47 2017 File:/home/ewerton/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:974 Error: io_open failed
Error: Time:Thu Nov  9 13:33:47 2017 File:/home/ewerton/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:1519 failure connecting to address iot-sdks-test.azure-devices.net.
-> 13:33:52 CONNECT | VER: 4 | KEEPALIVE: 60 | FLAGS: 128 | USERNAME: iot-sdks-test.azure-devices.net/ewertons-x509-3/api-version=2016-11-14&DeviceClientType=iothubclient%2f1.1.21%20(Linux%3b%20i686) | CLEAN: 0
<- 13:33:52 CONNACK | SESSION_PRESENT: false | RETURN_CODE: 0x5
Error: Time:Thu Nov  9 13:33:52 2017 File:/home/ewerton/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:mqtt_operation_complete_callback Line:1161 Connection Not Accepted: 0x5: Not Authorized
```

But upon verifying on the latest version, the reconnection is working fine:

```bash
Starting the IoTHub client sample x509...
Info: IoT Hub SDK for C, version 1.1.27
...
Info: Closing tlsio from a state other than TLSIO_STATE_EXT_OPEN or TLSIO_STATE_EXT_ERROR
Error: Time:Thu Nov  9 11:12:57 2017 File:/home/ewerton/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:on_underlying_io_open_complete Line:688 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Thu Nov  9 11:12:57 2017 File:/home/ewerton/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:tlsio_openssl_open Line:1202 Failed opening the underlying I/O.
Error: Time:Thu Nov  9 11:12:57 2017 File:/home/ewerton/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:971 Error: io_open failed
Error: Time:Thu Nov  9 11:12:57 2017 File:/home/ewerton/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:1777 failure connecting to address iot-sdks-test.azure-devices.net.
-> 11:13:02 CONNECT | VER: 4 | KEEPALIVE: 60 | FLAGS: 128 | USERNAME: iot-sdks-test.azure-devices.net/ewertons-x509-3/api-version=2016-11-14&DeviceClientType=iothubclient%2f1.1.27%20(Linux%3b%20i686) | CLEAN: 0
<- 11:13:02 CONNACK | SESSION_PRESENT: true | RETURN_CODE: 0x0
-> 11:13:02 SUBSCRIBE | PACKET_ID: 8 | TOPIC_NAME: devices/ewertons-x509-3/messages/devicebound/# | QOS: 1
<- 11:13:02 SUBACK | PACKET_ID: 8 | RETURN_CODE: 1
-> 11:13:52 PINGREQ
<- 11:13:52 PINGRESP
```

We had a bug that was preventing re-applying the existing configuration (including X509 certs) to the new connections when reconnections were triggered.
That is why you were getting the "Connection Not Accepted: 0x5: Not Authorized" errors.

If possible, please validate the fix from your side using the latest version of the SDK.

**Comment by Morozov-5F** [comment] 2017-11-10 07:01
Hi @ewertons. Yes, I can confirm that everything works fine with latest Azure SDK. Thank you!

**Comment by ewertons** [comment] 2017-11-10 17:13
Thank you @Morozov-5F .
We will close this issue, but please feel free to reopen it if needed.
Thanks for contributing to the Azure IoT SDK.

**Closed by ewertons** 2017-11-10 17:13 UTC
Labels: bug, fix checked in

**Comment by chirazment** [comment] 2019-02-05 13:32
i work  with ther version 1.2.13 in the iot hub and 1.0.6 in iot edge and when i try to make the connection between my gatway and the downstreamdevice i got error "the client has been disconnected " for the first time , i'm working with Ethernet
