### ISSUE TITLE
Blop upload failure on Linux but not on windows (space in name)

### ISSUE THREAD

**Issue by lmussier** [Azure/azure-iot-sdk-c#186] opened 2017-07-28 10:20 UTC
- **OS and version used:** 
Windows 10 & Ubuntu 16.04LTS

- **SDK version used:** <VERSION> 
2017-06-30

# Description of the issue:

Perform a blob upload (use the sample) with a remote name containing  a space.
```
if (IoTHubClient_LL_UploadToBlob(iotHubClientHandle, "hello world.txt", (const unsigned char*)HELLO_WORLD, sizeof(HELLO_WORLD) - 1) != IOTHUB_CLIENT_OK)
                {
                    (void)printf("hello world failed to upload\n");
                }
                else
                {
                    (void)printf("hello world has been created\n");
                }
```

The upload is successful on windows, not on Linux.
# Console log of the issue:
```
[09:45:29.460][ERROR]{httpapi_curl.c:594}               Failure in HTTP communication: server reply code is 404
[09:45:29.460][INFO ]{httpapi_curl.c:596}               HTTP Response:﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>ResourceNotFound</Code><Message>The specified resource does not exist.
RequestId:dc9843f8-0001-0097-2686-07b8bc000000
Time:2017-07-28T09:45:29.8156617Z</Message></Error>
[09:45:29.578][ERROR]{httpapi_curl.c:594}               Failure in HTTP communication: server reply code is 400
[09:45:29.578][INFO ]{httpapi_curl.c:596}               HTTP Response:{"Message":"{\"errorCode\":400019,\"trackingId\":\"1cc5f05db135418b9c9723df871d7839-G:3-TimeStamp:07/28/2017 09:45:29\",\"message\":\"File upload completion status is invalid\",\"timestampUtc\":\"2017-07-28T09:45:29.8114185Z\"}","ExceptionMessage":""}
[09:45:29.578][ERROR]{iothub_client_ll_uploadtoblob.c:} HTTP code was 400
[09:45:29.578][ERROR]{iothub_client_ll_uploadtoblob.c:} IoTHubClient_LL_UploadToBlob_step3 failed
[09:45:29.583][ERROR]{iothub_client.c:1771}             unable to IoTHubClient_LL_UploadToBlob


```

**Comment by markrad** [comment] 2017-08-28 18:38
Hi @lmussier,

I have been able to reproduce this. I'm in the process of debugging it. 

_Mark Radbourne MSFT_

**Comment by markrad** [comment] 2017-09-01 20:29
Hi @lmussier,

The problem is caused by the cloud returning a URL in response to the initial request to upload a file which still contains the blank. Unfortunately this is not as easy as simply URL encoding the string because portions of it have already been URL encoded. I have proposed that this should be fixed in the cloud since it is returning a malformed URL. I will update this issue when I have more information.

_Mark Radbourne MSFT_

**Comment by markrad** [comment] 2017-09-05 19:47
Hi @lmussier,

The product group are considering how this issue is to be addressed. I'll update this thread when I have more information.

_Mark Radbourne MSFT_

**Comment by lmussier** [comment] 2017-09-06 05:00
Ok, thanks for the update.

**Comment by markrad** [comment] 2017-09-07 23:47
Hi @lmussier,

I don't know if this issue is blocking you. If so you can use the branch mrblankfix. This addresses the problem. I still need to fix the unit tests before I can integrate the change.

_Mark Radbourne MSFT_

**Comment by alexmrtn** [comment] 2017-09-13 14:00
Hi @markgar,

I'm taking over the work of @lmussier. Thanks for the update, this problem is not blocking us right now but we will need this fix eventually. We can use the branch mrblankfix until the change is merged.

**Comment by markrad** [comment] 2017-09-21 20:06
Hi @alexmrtn,

The fix will be going for code review today.

_Mark Radbourne MSFT_

**Comment by markrad** [comment] 2017-10-03 00:20
Hi @alexmrtn,

A fix to address this issue has been integrated into the master branch. 

_Mark Radbourne MSFT_

**Closed by markrad** 2017-10-03 00:20 UTC
Labels: CSS, investigation-required
