### ISSUE TITLE
Issues when running the 'simplesample_http' sample

### ISSUE THREAD

**Issue by awanti** [Azure/azure-iot-sdk-c#89] opened 2017-03-13 12:51 UTC
Hello
       We have build and installed the latest azure iot sdk c, version 1.1.8 in openwrt platform. When we run the sample from  serializer/samples/simplesample_http/  i.e "simplesample_http". The same sample we are able to run in azure iot sdk c, version 1.0.14.

we are getting the following errors.

` Error: Time:Wed Mar  8 11:39:27 2017 File:/home/abhishek/openwrt/sdk/OpenWrt-SDK-ramips-mt7688_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/azure-iot-sdk-c/c-utility/src/vector.c Func:VECTOR_find_if Line:292 invalid argument - handle((nil)), pred(0x418554)`

And when we send the message to device from hub it is unable to receive the message nor receive the event from device.

But we can able to run the sample from iothub_client/samples/iothub_client_sample_http/ i.e. 'iothub_client_sample_http'.

Thank you

**Comment by anporumb** [comment] 2017-03-13 18:15
Hello @awanti ,

We will look at this in March.

Best Regards,
Andrei Porumb

**Comment by anporumb** [comment] 2017-03-16 17:08
Hello @awanti ,

I have checked in master branch code that will squelch the error message you were seeing.

However, I am not able to reproduce your problem where you are reporting that the device is not sending data to IoTHub.

How do I repro your problem?

Best Regards,
Andrei Porumb

**Comment by awanti** [comment] 2017-03-17 05:02
![screenshot](https://cloud.githubusercontent.com/assets/26381833/24029519/b991835a-0afc-11e7-929c-dac04e19213b.png)

**Comment by ewertons** [comment] 2017-03-17 15:20
@awanti , did you get the latest version of the azure-iot-sdk-c with @anporumb 's fix?

As you stated above, the version you are running is 1.1.8, but the current version in master is 1.1.9.

https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/inc/iothub_client_version.h

**Comment by anporumb** [comment] 2017-03-20 18:21
Helo @awanti ,

I have checked in a fix for this overzealous printing of that error. Can you please confirm it from the master branch? Thank you.

Best Regards,
Andrei Porumb

**Comment by awanti** [comment] 2017-03-24 05:50
Hi,
The latest master branch fixes the above error.
Thanks for your support.

**Closed** 2017-03-27 18:09 UTC
Labels: fix checked in
