### ISSUE TITLE
Endless loop with high CPU consumption after amqp:internal-error

### ISSUE THREAD

**Issue by RomanSchneider** [Azure/azure-iot-sdk-c#108] opened 2017-04-05 08:40 UTC
- **OS and version used:**  Debian GNU/Linux 8
- **SDK version used:**  IoT Hub SDK for C, version 1.1.10

# Description of the issue:

- Connect to IoT Hub using AMQP (x509=true)
- Sending 3 Messages
- Get Confimation for the three messages
- Do nothing for 240 seconds (DEFAULT_CONNECTION_IDLE_TIMEOUT?)
- AMQP connection closes with amqp:internal-error,No frame received for the idle timeout
- **Endless Loop with high CPU consumption**
  - Reconnect possible, although
  - No connection status callback

# Console log of the issue:
fcloudd[19868]: starting ...
fcloudd[19868]: HostName=IoTHubTesthub.azure-devices.net;DeviceId=AUTOTEST;x509=true
fcloudd[19868]: Successfully connected with client
Info: IoT Hub SDK for C, version 1.1.10
fcloudd[19868]: IoTHubClient_GetRetryPolicy: 5 0
fcloudd[19868]: MSG[0]: accepted for transmission
fcloudd[19868]: MSG[1]: accepted for transmission
-> Header (AMQP 0.1.0.0)
<- Header (AMQP 0.1.0.0)
-> [OPEN]* {76df2d26-53c4-4d2f-bf63-0c731e5a7f04,IoTHubTesthub.azure-devices.net,4294967295,65535,240000}
fcloudd[19868]: MSG[2]: accepted for transmission
<- [OPEN]* {DeviceGateway_a089c8b6c69f4957be43f84678bc39cc,10.0.0.25,65536,8191,240000,NULL,NULL,NULL,NULL,NULL}
-> [BEGIN]* {NULL,0,4294967295,100,4294967295}
<- [BEGIN]* {0,1,100,5000,262143,NULL,NULL,NULL}
-> [ATTACH]* {link-snd-AUTOTEST-182ee15e-dbfa-406c-b78d-4bfc1e3f2c0d,0,false,0,0,* {link-snd-AUTOTEST-182ee15e-dbfa-406c-b78d-4bfc1e3f2c0d-source},* {amqps://IoTHubTesthub.azure-devices.net/devices/AUTOTEST/messages/events},NULL,NULL,0,18446744073709551615,NULL,NULL,{[com.microsoft:client-version:iothubclient/1.1.10]}}
<- [ATTACH]* {link-snd-AUTOTEST-182ee15e-dbfa-406c-b78d-4bfc1e3f2c0d,0,true,0,NULL,* {link-snd-AUTOTEST-182ee15e-dbfa-406c-b78d-4bfc1e3f2c0d-source,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL},* {amqps://IoTHubTesthub.azure-devices.net/devices/AUTOTEST/messages/events,NULL,NULL,NULL,NULL,NULL,NULL},NULL,NULL,NULL,1048576,NULL,NULL,{[com.microsoft:client-version:iothubclient/1.1.10]}}
-> [ATTACH]* {link-rcv-AUTOTEST-bc40512f-92f4-45f3-b717-20a72d98d4be,1,true,0,0,* {amqps://IoTHubTesthub.azure-devices.net/devices/AUTOTEST/messages/devicebound},* {link-rcv-AUTOTEST-bc40512f-92f4-45f3-b717-20a72d98d4be-target},NULL,NULL,NULL,65536,NULL,NULL,{[com.microsoft:client-version:iothubclient/1.1.10]}}
fcloudd[19868]: ConnectionCallback: 0 6
fcloudd[19868]: client disconnected
<- [FLOW]* {0,100,1,5000,0,0,1000,0,NULL,false,NULL}
-> [TRANSFER]* {0,0,<01 00 00 00>,0,false,false}
-> [TRANSFER]* {0,1,<02 00 00 00>,0,false,false}
-> [TRANSFER]* {0,2,<03 00 00 00>,0,false,false}
<- [ATTACH]* {link-rcv-AUTOTEST-bc40512f-92f4-45f3-b717-20a72d98d4be,1,false,0,0,* {amqps://IoTHubTesthub.azure-devices.net/devices/AUTOTEST/messages/devicebound,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL},* {link-rcv-AUTOTEST-bc40512f-92f4-45f3-b717-20a72d98d4be-target,NULL,NULL,NULL,NULL,NULL,NULL},NULL,NULL,0,65536,NULL,NULL,{[com.microsoft:client-version:iothubclient/1.1.10]}}
-> [FLOW]* {1,4294967295,3,97,1,0,10000}
<- [DISPOSITION]* {true,0,NULL,true,* {},NULL}
fcloudd[19868]: MSG[0]: Conf_CB[0] : IOTHUB_CLIENT_CONFIRMATION_OK
<- [DISPOSITION]* {true,1,2,true,* {},NULL}
fcloudd[19868]: MSG[1]: Conf_CB[1] : IOTHUB_CLIENT_CONFIRMATION_OK
fcloudd[19868]: MSG[2]: Conf_CB[2] : IOTHUB_CLIENT_CONFIRMATION_OK

...
240 Seconds Idle
...

-> [CLOSE]* {* {amqp:internal-error,No frame received for the idle timeout}}
-> [CLOSE]* {* {amqp:internal-error,No frame received for the idle timeout}}
-> [CLOSE]* {* {amqp:internal-error,No frame received for the idle timeout}}
-> [CLOSE]* {* {amqp:internal-error,No frame received for the idle timeout}}
-> [CLOSE]* {* {amqp:internal-error,No frame received for the idle timeout}}
-> [CLOSE]* {* {amqp:internal-error,No frame received for the idle timeout}}
-> [CLOSE]* {* {amqp:internal-error,No frame received for the idle timeout}}
-> [CLOSE]* {* {amqp:internal-error,No frame received for the idle timeout}}
-> [CLOSE]* {* {amqp:internal-error,No frame received for the idle timeout}}
-> [CLOSE]* {* {amqp:internal-error,No frame received for the idle timeout}}
-> [CLOSE]* {* {amqp:internal-error,No frame received for the idle timeout}}
...

Endless loop with high CPU consumption

**Comment by ewertons** [comment] 2017-04-06 01:08
Hi @RomanSchneider ,
I tried the sample iothub_client_sample_x509 on a Ubuntu machine, simulating a keep alive timeout, but I saw no issues with the reconnection.

```c
-> [CLOSE]* {* {amqp:internal-error,No frame received for the idle timeout}}
Info: Preparing transport for re-connection
Error: Time:Wed Apr  5 17:38:37 2017 File:/home/ewertons/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:tlsio_openssl_send Line:1236 Invalid tlsio_state. Expected state is TLSIO_STATE_OPEN.
Error: Time:Wed Apr  5 17:38:37 2017 File:/home/ewertons/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:tlsio_openssl_close Line:1195 Invalid tlsio_state. Expected state is TLSIO_STATE_NOT_OPEN or TLSIO_STATE_CLOSING.
-> [CLOSE]* {}
Error: Time:Wed Apr  5 17:38:37 2017 File:/home/ewertons/azure-iot-sdk-c/c-utility/src/tlsio_openssl.c Func:tlsio_openssl_close Line:1195 Invalid tlsio_state. Expected state is TLSIO_STATE_NOT_OPEN or TLSIO_STATE_CLOSING.
Info: Transport state changed from AMQP_TRANSPORT_STATE_RECONNECTION_REQUIRED to AMQP_TRANSPORT_STATE_READY_FOR_RECONNECTION
Info: Transport state changed from AMQP_TRANSPORT_STATE_READY_FOR_RECONNECTION to AMQP_TRANSPORT_STATE_RECONNECTING
Info: Transport state changed from AMQP_TRANSPORT_STATE_RECONNECTING to AMQP_TRANSPORT_STATE_CONNECTED
```

So I will attempt the same in a Debian GNU to investigate it further.

However, do you have a way to verify if the device didn't loose network connection?

Also, which sample did you run? Did you make any changes?

**Comment by RomanSchneider** [comment] 2017-04-06 10:18
Hi @ewertons, 

my code is almost the iothub_client_sample_x509 (except not using the _LL_ API).  For verification I tried the original iothub_client_sample_x509 on my Debian and on the ARM Target (cross-compiled). 

- On the Debian machine same behavior compared to my code (endless loop - see log attached)
- On the ARM Board it does work, but i see there kind of keep alive in the logs during the idle period:
- Don't think network is down. both clients operate on same subnet. 

```
<- [DISPOSITION]* {true,0,NULL,true,* {},NULL}
  Confirmation[4] received for message tracking id = 0 with result = IOTHUB_CLIENT_CONFIRMATION_OK
  <- Empty frame
  -> Empty frame
  <- Empty frame
  -> Empty frame
  <- Empty frame
  -> Empty frame
  <- Empty frame

```

- On the not working x86_64 Debian i don't see these keep alives (no incomming), there's only:

```
  <- [DISPOSITION]* {true,0,NULL,true,* {},NULL}
  Confirmation[4] received for message tracking id = 0 with result = IOTHUB_CLIENT_CONFIRMATION_OK
  -> Empty frame
  -> Empty frame
  -> [CLOSE]* {* {amqp:internal-error,No frame received for the idle timeout}}

```
## Log from original iothub_client_sample_x509 on Debian 

iothub_client_sample_x509 
Starting the IoTHub client sample x509...
Info: IoT Hub SDK for C, version 1.1.10
IoTHubClient_LL_SetMessageCallback...successful.
IoTHubClient_LL_SendEventAsync accepted message [0] for transmission to IoT Hub.
IoTHubClient_LL_SendEventAsync accepted message [1] for transmission to IoT Hub.
IoTHubClient_LL_SendEventAsync accepted message [2] for transmission to IoT Hub.
IoTHubClient_LL_SendEventAsync accepted message [3] for transmission to IoT Hub.
IoTHubClient_LL_SendEventAsync accepted message [4] for transmission to IoT Hub.
-> Header (AMQP 0.1.0.0)
<- Header (AMQP 0.1.0.0)
-> [OPEN]* {c1bade21-28ed-474f-a3a9-a49647a15806,IoTHubTesthub.azure-devices.net,4294967295,65535,240000}
<- [OPEN]* {DeviceGateway_9400452bf76e48e7b421f2df1683aee3,10.0.0.24,65536,8191,240000,NULL,NULL,NULL,NULL,NULL}
-> [BEGIN]* {NULL,0,4294967295,100,4294967295}
<- [BEGIN]* {0,1,100,5000,262143,NULL,NULL,NULL}
-> [ATTACH]* {link-snd-AUTOTEST-00e2f331-f00c-4107-abb1-a359c4cc24f6,0,false,0,0,* {link-snd-AUTOTEST-00e2f331-f00c-4107-abb1-a359c4cc24f6-source},* {amqps://IoTHubTesthub.azure-devices.net/devices/AUTOTEST/messages/events},NULL,NULL,0,18446744073709551615,NULL,NULL,{[com.microsoft:client-version:iothubclient/1.1.10]}}
<- [ATTACH]* {link-snd-AUTOTEST-00e2f331-f00c-4107-abb1-a359c4cc24f6,0,true,0,NULL,* {link-snd-AUTOTEST-00e2f331-f00c-4107-abb1-a359c4cc24f6-source,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL},* {amqps://IoTHubTesthub.azure-devices.net/devices/AUTOTEST/messages/events,NULL,NULL,NULL,NULL,NULL,NULL},NULL,NULL,NULL,1048576,NULL,NULL,{[com.microsoft:client-version:iothubclient/1.1.10]}}
-> [ATTACH]* {link-rcv-AUTOTEST-79adced3-b3f8-4664-b712-877f46b35fbf,1,true,0,0,* {amqps://IoTHubTesthub.azure-devices.net/devices/AUTOTEST/messages/devicebound},* {link-rcv-AUTOTEST-79adced3-b3f8-4664-b712-877f46b35fbf-target},NULL,NULL,NULL,65536,NULL,NULL,{[com.microsoft:client-version:iothubclient/1.1.10]}}
<- [FLOW]* {0,100,1,5000,0,0,1000,0,NULL,false,NULL}
-> [TRANSFER]* {0,0,<01 00 00 00>,0,false,false}
-> [TRANSFER]* {0,1,<02 00 00 00>,0,false,false}
-> [TRANSFER]* {0,2,<03 00 00 00>,0,false,false}
-> [TRANSFER]* {0,3,<04 00 00 00>,0,false,false}
-> [TRANSFER]* {0,4,<05 00 00 00>,0,false,false}
<- [ATTACH]* {link-rcv-AUTOTEST-79adced3-b3f8-4664-b712-877f46b35fbf,1,false,0,0,* {amqps://IoTHubTesthub.azure-devices.net/devices/AUTOTEST/messages/devicebound,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL},* {link-rcv-AUTOTEST-79adced3-b3f8-4664-b712-877f46b35fbf-target,NULL,NULL,NULL,NULL,NULL,NULL},NULL,NULL,0,65536,NULL,NULL,{[com.microsoft:client-version:iothubclient/1.1.10]}}
-> [FLOW]* {1,4294967295,5,95,1,0,10000}
<- [DISPOSITION]* {true,1,2,true,* {},NULL}
Confirmation[0] received for message tracking id = 1 with result = IOTHUB_CLIENT_CONFIRMATION_OK
Confirmation[1] received for message tracking id = 2 with result = IOTHUB_CLIENT_CONFIRMATION_OK
<- [DISPOSITION]* {true,3,NULL,true,* {},NULL}
Confirmation[2] received for message tracking id = 3 with result = IOTHUB_CLIENT_CONFIRMATION_OK
<- [DISPOSITION]* {true,4,NULL,true,* {},NULL}
Confirmation[3] received for message tracking id = 4 with result = IOTHUB_CLIENT_CONFIRMATION_OK
<- [DISPOSITION]* {true,0,NULL,true,* {},NULL}
Confirmation[4] received for message tracking id = 0 with result = IOTHUB_CLIENT_CONFIRMATION_OK
-> Empty frame
-> Empty frame
-> [CLOSE]* {* {amqp:internal-error,No frame received for the idle timeout}}
-> [CLOSE]* {* {amqp:internal-error,No frame received for the idle timeout}}
...

**Comment by markrad** [comment] 2017-04-20 20:57
Hi @RomanSchneider,

We have recently checked in many fixes in this area of the code. Can you clone the latest version from GitHub and see if it still reproduces please?

Thanks.

_Mark Radbourne MSFT_

**Comment by markrad** [comment] 2017-04-27 17:57
Hi @RomanSchneider,

Are you still seeing this issue with the latest SDK?

_Mark Radbourne MSFT_

**Comment by markrad** [comment] 2017-05-05 20:40
Hi @RomanSchneider,

Since there has been no response to my questions for fifteen days I am closing this issue. Please reopen it if you still require assistance.

_Mark Radbourne MSFT_

**Closed by markrad** 2017-05-05 20:40 UTC
Labels: investigation-required
