### ISSUE TITLE
Cannot build application linking against libiothub_client.so

### ISSUE THREAD

**Issue by syedelec** [Azure/azure-iot-sdk-c#569] opened 2018-07-19 23:02 UTC
- **OS and version used:** <VERSION> 
Ubuntu 16.04
- **SDK version used:** <VERSION> 
1.2.8

# Description of the issue:

I recently updated from 1.2.3 and I am now using version 1.2.8 of Azure C SDK
Linking any program (that was working great with 1.2.3) against libiothub_client.so generates this error logs :

```
//usr/local/lib/libiothub_client.so: undefined reference to `IoTHubClientCore_LL_SetInputMessageCallback'
//usr/local/lib/libiothub_client.so: undefined reference to `IoTHubClientCore_LL_SendEventToOutputAsync'
//usr/local/lib/libiothub_client.so: undefined reference to `IoTHubClientCore_LL_SetInputMessageCallbackEx'
collect2: error: ld returned 1 exit status
```

I built azure using these flags :

```
cmake ../ -Dbuild_as_dynamic:BOOL=ON -Ddont_use_uploadtoblob:BOOL=ON -Duse_http:BOOL=OFF -Duse_mqtt:BOOL=OFF -Duse_amqp:BOOL=ON -Duse_prov_client:BOOL=ON -Duse_sample_trusted_cert:BOOL=OFF -Dskip_samples:BOOL=ON -Duse_sample_trusted_cert:BOOL=OFF
```

# Code sample exhibiting the issue:

An example of not working code:

```
#include <azure_c_shared_utility/platform.h>

#include <stdio.h>

int main( void ){
    if ( platform_init() == 0 )
    {
        printf("platform_init() function call worked\n");
    }
    printf("calling platform_deinit\n");
    platform_deinit();
    return 0;
}
```

CMakeLists.txt to build :

```
set(example_src example.c)
add_executable(example ${example_src})
target_link_libraries(example iothub_client)
```

# Console log of the issue:

```
//usr/local/lib/libiothub_client.so: undefined reference to `IoTHubClientCore_LL_SetInputMessageCallback'
//usr/local/lib/libiothub_client.so: undefined reference to `IoTHubClientCore_LL_SendEventToOutputAsync'
//usr/local/lib/libiothub_client.so: undefined reference to `IoTHubClientCore_LL_SetInputMessageCallbackEx'
collect2: error: ld returned 1 exit status
```

**Comment by jspaith** [comment] 2018-07-20 23:43
I can confirm that this repros for me too when using the dynamic flag.  

We'll look into this asap next week.  In meantime you may be able to remove the `build_as_dynamic:BOOL=ON` as a (gross) workaround.

Sorry you've hit this.  We've had some problems with dynamic flag on Windows too and added tests to our gates for Win.  We'll add gate checks for Linux, too.

**Comment by jspaith** [comment] 2018-07-23 19:34
The root problem here is a pretty simple typo that we didn't catch since we don't build that much with `Ddont_use_uploadtoblob:BOOL=ON`.  In the #ifdef [here](https://github.com/Azure/azure-iot-sdk-c/blob/1f3e5bff4f04428943b0eab3f35df56cade7d7e3/iothub_client/src/iothub_client_core_ll.c#L2511), the `DONT_USE_UPLOADTOBLOB` ends up capturing pretty much the rest of the file.  A change at the end of `IoTHubClientCore_LL_UploadMultipleBlocksToBlobEx` to put the #endif there and not at bottom of file got things linking.

The fix along with a more thorough test of cmake flags on Linux general (it would've caught this) is ready on my dev box and I'll get submitted to gates soon.

There's some more data here which may or may not hit you at somepoint.  After reproing this last week, today I took an update to my Linux box (Ubuntu 18.04).  Somehow the cmake apt-get provided me hit some sort of problems.  It was generating files that it could not itself parse out for dynamic linking.   This was on cmake 3.10.2.  I manually installed cmake 3.12 and got things working again.

**Comment by jspaith** [comment] 2018-07-23 22:50
Fix is in c7cb248d7e8933a252715f38d3490148e0e6891d.  Thanks again for calling this to our attention and apologies you had to in 1st place.

**Comment by az-iot-builder-01** [comment] 2018-07-23 22:50
@syedelec, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/DesignPage.aspx#FormId=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu&Token=af48ed4ed02842bea21e0d3933b78fac)

**Closed by jspaith** 2018-07-23 22:50 UTC

**Comment by syedelec** [comment] 2018-07-23 23:09
@jspaith thank you for the fix :+1:
