### ISSUE TITLE
Connection intermittant

### ISSUE THREAD

**Issue by STEPHER2** [Azure/azure-iot-sdk-c#1] opened 2016-11-17 09:49 UTC
Having an issue in that initial connection to the Iot Hub is intermittent, it seems to sometimes hang whenever it reaches:

``        /*Codes_SRS_IOTHUBCLIENT_LL_02_021: [Otherwise, IoTHubClient_LL_DoWork shall invoke the underlaying layer's _DoWork function.]*/
handleData->IoTHubTransport_DoWork(handleData->transportHandle, iotHubClientHandle);``

inside iothub_client_II.c @ line 766

Im using the mBed platform and cant follow the code because i cant breakpoint where inside the function pointer it specifically holds up?

**Comment by markrad** [comment] 2016-12-05 21:59
Hi @STEPHER2,

Am I correct is suggesting that you are using the low level code, that is the functions with _LL_ in their name?

I did encounter this myself once but I found that converting the code to use the high level function addressed the problem. Since this is what my customer wanted anyway, I did not pursue this any further and assumed it was just a quirk on my system. 

I will attempt to reproduce this again and debug it. In the meantime you might try the high level API and see if it resolves the issue for you too.

_Mark Radbourne MSFT_

**Comment by STEPHER2** [comment] 2016-12-08 15:35
Hi @markrad 

Thanks for the reply, i am seeing other intermittent connection issues where it tries to connect and cant (assume the server is holding a connection open and the device is trying to reconnect to it again?) which then produces one of the following reasons:

Failed to initialize the platform
Error io_open failed
Failure sending control packet

If any of these errors occur and i try sending a message to the hub i get:

sys_init error

and the device just sits spinning its wheels doing nothing except from flashing the on board red LED. Tried to find where this is happening byt it is impossible.

Have you seen any of these errors?

Many thanks

Ryan

**Comment by markrad** [comment] 2016-12-08 20:54
Hi @STEPHER2,

Yes. As it happens I was debugging this just yesterday. Though I can't be certain that you are hitting the same issue I was able to cause the sys_init error by calling the EthernetInterface::init function twice. This causes a second call to tcpip_init. The sad truth is that the quality of the code in EthernetInterface is very poor. It doesn't check return codes and it fails to expose the network connected/disconnected events. Furthermore I found it very difficult to implement network recovery in the code and resorted to forcing a hard reset. You can view my code here: https://developer.mbed.org/users/markrad/code/FXOS8700CQ_To_Azure_IoT/.
Please change the connection string if you choose to test it.

_Mark Radbourne MSFT_

**Comment by markrad** [comment] 2016-12-27 21:13
Hi @STEPHER2,

Since I didn't hear back from you I am closing this issue. Hopefully the code I provided was some assistance to you in recovering the network connection. You are welcome to reopen this issue if the problem persists. 

_Mark Radbourne MSFT_

**Closed by markrad** 2016-12-27 21:13 UTC
Labels: CSS, help wanted
