### ISSUE TITLE
Network transport layer error handling issues

### ISSUE THREAD

**Issue by tameraw** [Azure/azure-iot-sdk-c#63] opened 2017-02-09 21:20 UTC
_From @GrantEdwards on February 8, 2017 16:42_

I've been testing on Linux with the "simulated device" sample app that
simulates two BLE temperatures sensors. So far I've tried three
different transports: HTTP/curl, AMQT and MQTT.

All appear to have error handling problems.

 * **HTTP/curl**

   Failure to open a connection (CA failure, auth failure, etc.)
   generates a handlful of error messages (typically 4-6 messages). It
   then spins in a loop retrying as fast as possible.  This burns up
   all available CPU time and log space.

   The usual way to handle errors like this is to delay before
   retrying -- often with a truncated binary exponential backoff.

    https://en.wikipedia.org/wiki/Exponential_backoff#Binary_exponential_backoff

 * **AMQP & MQTT**

   Failure to open a connection (similar causes as above) fails
   silently. The TCP connection stays open, but there is no activity
   on the connection until the gateway is shut down -- which causes
   the TCP connection to be closed.

Has nobody else run into these problems?

IMO, transport layer failures like I mentioned need to generate an
intelligible log message (one log message per failure is enough) and
should then retry _with a delay_.

_Copied from original issue: Azure/azure-iot-gateway-sdk#126_

**Comment by tameraw** [comment] 2017-02-09 21:20
_From @damonbarry on February 9, 2017 19:13_

There are disparities in the [device SDK](https://github.com/Azure/azure-iot-sdk-c) between the protocols regarding retry algorithms and error handling. The device SDK team is working to make these consistent over time.

I'll move this issue into the device SDK repo, where you can track the status...

**Comment by mm-mhr** [comment] 2017-02-10 06:00
@GrantEdwards 
I am pretty sure that you are not the only one running into this issues.

Basically we realized some time ago that we can choose between killing our single core thing with HTTP knowing why - or surviving with MQTT without knowing why.
We decided some month ago to stick with MQTT and do not follow the progress in SDK for the other transports. But we had to learn that MQTT leads to acceptance problems with our users because port 8883 needs to be opened which is a challenge for managed networks. So we'd prefer some firewall friendly transport...

I am very happy to hear that the SDK team is working on this. 
This will help to get acceptance for our IoT solutions.

**Comment by anporumb** [comment] 2017-02-10 19:12
We are working on alignment requirements for retry across protocols and languages. 

Best Regards,
Andrei Porumb

**Comment by GrantEdwards** [comment] 2017-02-10 19:26
The problem is that Microsoft IoT Hub marketing and product management
are selling this SDK to people as something that's ready to to deploy
in real-world, industrial applications.

It looks to me like it's a long way from that.  Only in the most
recent conference call I was in did somebody from Microsoft start
walking-back claims they had been making for the OPC/UA client module
that they'd been pitching to us.  Now it's apparently not something
you'd want to use in a real product, and if you want OPC/UA you'd
better write your own module.

Are they going to start saying that for the other modules too?

**Comment by olivierbloch** [comment] 2017-03-01 19:01
Hi @GrantEdwards 
Our device and service SDKs for Azure IoT Hub are definitely intended to be used in production and many customers have actual deployments in production already.
The development team is closely monitoring not only GitHub but also other discussion forums to help solve issues faced by customers and improve not only the stability and robustness of the SDKs but also bring in the right level of functionality.
Regarding the protocols/language/features disparity, the gaps are closing as the team is working full steam on alignment and you can see progress in the bi-weekly release notes. We expect to be on parity soon ensuring all SDKs offer the same level of feature support for each protocol.
We appreciate your feedback and want to support users as much as we can.
On the very particular issue of error handling and auto-reconnect, we have made the decision to add smart support to the SDKs only recently based on users demand (originally we had more simple logic and left it to the user to implement their own retry logic). This is one of the top concern for the dev team and I really hope we'll have a consistent and efficient mechanism in place in all SDKs real soon.
Thanks
Olivier

**Closed** 2017-03-06 16:53 UTC

**Comment by GrantEdwards** [comment] 2017-08-23 14:46
So, was there ever any fix for these network retry problems?  Or are you still "working on alignment requirements"?
