### ISSUE TITLE
a head file is lost 

### ISSUE THREAD

**Issue by v-limliu** [Azure/azure-iot-sdk-c#113] opened 2017-04-07 09:35 UTC
- **OS and version used: Windows 7 
- **SDK version used:1.1.12

a head file is lost :iothub_client_authorization.h. when add this file ,it  is will be ok

**Comment by tameraw** [comment] 2017-04-07 18:30
@v-limliu - From the above we are unable to understand what the issue is. Please provide more details and a repro of the problem. Thanks.

**Comment by v-limliu** [comment] 2017-04-10 02:53
azure-iot-sdk-c  release 1.12  does not have iothub_client_authorization.h , I should copy one  so it can work well

**Comment by ewertons** [comment] 2017-04-10 16:40
Hi @v-limliu ,
unfortunately the package 1.1.12 indeed had the issue you are describing.

We immediately released a new package which contains the missing header. Please verify it on version **1.1.13**
https://www.nuget.org/packages/Microsoft.Azure.IoTHub.IoTHubClient/

We apologize for the disruption.

**Comment by zolvarga** [comment] 2017-04-10 17:38
@v-limliu 

The issue has been fixed in our latest release. (2017_04_07)
Thanks for using our SDK!

Best Regards,
Zoltan

**Closed** 2017-04-12 17:24 UTC
Labels: bug, fix checked in
