### ISSUE TITLE
[MQTT] ConnectionStatus / EventConfirmation callback behaviors are not consistent when network is disconnected

### ISSUE THREAD

**Issue by yphuangms** [Azure/azure-iot-sdk-c#19] opened 2017-01-10 10:50 UTC
In the release of "2016-11-17", when running the test cases to disconnect/resume network, the callback behaviors could be different, hence making the program to use Azure IoT device SDK become difficult to manage network situations.

Usually we expect "ConnectionStatus" callback will report connection status once the connection status is changed. However when disconnect/resume network manually, we'll found it's not true always. If the program starts with network disconnected, "ConnectionStatus" callback might not be called, and this might happened maybe 7 times out of 10 tries, and there are 3 times the ConnectionStatus callback will be called when doing the first call to "IoTHubClient_LL_DoWork()". This kind of behavior make it difficult to detect network disconnection, if the program is waiting for C2D message from IoT Hub.

"EventConfirmation" callback for "IoTHubClient_LL_SendEventAsync()" is also inconsistent. If the network disconnection is detected during the time trying to send the message, "EventConfirmation" will get a error callback, and this message is then aborted/dropped, hence a message level retry could be handled within this callback. If network is not resumed, then for the next message, "EventConfirmation" callback will never be called (if "messageTimeout" is not set) to reflect network error.

So the message sent callback might have two different result in corresponding to network disconnection, one is callback with error, the other is no callback or a callback with timeout error.

Please help to make the behavior consistent, so to avoid potential defects.

**Comment by BertKleewein** [comment] 2017-01-13 22:30
Hi @yphuangms , can you please tell me what platform you're using and if you've changed the default socket and SSL adapters?  Specifically, I'm asking if you changed your build configuration to link different socket and SSL adapter .c files under azure-iot-sdk-c/c-utility.

**Comment by BertKleewein** [comment] 2017-01-17 17:42
Also, can you be more specific about what "network disconnection" means?  I have a few ideas and I want to make sure I cover all cases.  On Ethernet, for example, there is "cable is not plugged in", "cable is plugged in, but network is not connected (e.g. no DHCP response)", "network is connected, but server is not visible (eg. no DNS mapping for server)", "network is connected, and server is visible, but doesn't accept responses".  I can imagine similar scenarios for WiFi and cellular networks, though I'm not sure if there are more specific failures I need to make sure to cover.  Even if the code path is the same in some of these cases, I still want to verify for all scenarios when possible.

**Comment by yphuangms** [comment] 2017-01-18 09:28
The "network disconnection" refers to any physical network issue or network configuration issue, such as "cable is not plugged", or some where in the network route is disconnected so the device cannot get access to internet.

The applicaiton need these condition callbacks so it could report the network error as an alert. System administrator could pay attention to these alerts and have the problems resolved.

The test is running on Windows 8.1 (x86), and using the sample program "iothub_client_sample_mqtt" with the modification to enable ConnectionStatus callback.

The azure iot device sdk source code is from "2016-11-17" release version. 
Default socket and SSL adapters is used since we don't do any modification on build script or configuration at all.

The network conditions could be generated by disable the network interface, and then enable it again.

If the mqtt sample program is started under the condition that the network is unavalible, no ConnectionStatus callback will be called, as well as no EventConfirmation callback is called for such network error .

The test log is pasted below:

## Start program when network is disconnected

**Log:**
^^^^^^^^^^^^
Info: IoT Hub SDK for C, version 1.1.0
**IoTHubClient_LL_SendEventAsync accepted message [0] for transmission to IoT Hub.**

Error: Time:Wed Jan 18 15:17:44 2017 File:D:\gitroot\azure-iot-sdks\c\c-utility\
adapters\socketio_win32.c Func:_socketio_open Line:299 Failure: getaddrinfo fail
ure 11001.
Error: Time:Wed Jan 18 15:17:44 2017 File:D:\gitroot\azure-iot-sdks\c\umqtt\src\
mqtt_client.c Func:_mqtt_client_connect Line:885 Error: io_open failed
Error: Time:Wed Jan 18 15:17:44 2017 File:D:\gitroot\azure-iot-sdks\c\iothub_cli
ent\src\iothubtransport_mqtt_common.c Func:_SendMqttConnectMsg Line:1556 failure
 connecting to address xxx.azure-devices.net:0.
Error: Time:Wed Jan 18 15:17:49 2017 File:D:\gitroot\azure-iot-sdks\c\c-utility\
adapters\socketio_win32.c Func:_socketio_open Line:299 Failure: getaddrinfo fail
ure 11001.
Error: Time:Wed Jan 18 15:17:49 2017 File:D:\gitroot\azure-iot-sdks\c\umqtt\src\
mqtt_client.c Func:_mqtt_client_connect Line:885 Error: io_open failed
Error: Time:Wed Jan 18 15:17:49 2017 File:D:\gitroot\azure-iot-sdks\c\iothub_cli
ent\src\iothubtransport_mqtt_common.c Func:_SendMqttConnectMsg Line:1556 failure
 connecting to address xxx.azure-devices.net:0.
Error: Time:Wed Jan 18 15:17:54 2017 File:D:\gitroot\azure-iot-sdks\c\c-utility\
adapters\socketio_win32.c Func:_socketio_open Line:299 Failure: getaddrinfo fail
ure 11001.
Error: Time:Wed Jan 18 15:17:54 2017 File:D:\gitroot\azure-iot-sdks\c\umqtt\src\
mqtt_client.c Func:_mqtt_client_connect Line:885 Error: io_open failed
Error: Time:Wed Jan 18 15:17:54 2017 File:D:\gitroot\azure-iot-sdks\c\iothub_cli
ent\src\iothubtransport_mqtt_common.c Func:_SendMqttConnectMsg Line:1556 failure
 connecting to address xxx.azure-devices.net:0.
Error: Time:Wed Jan 18 15:17:59 2017 File:D:\gitroot\azure-iot-sdks\c\c-utility\
adapters\socketio_win32.c Func:_socketio_open Line:299 Failure: getaddrinfo fail
ure 11001.
Error: Time:Wed Jan 18 15:17:59 2017 File:D:\gitroot\azure-iot-sdks\c\umqtt\src\
mqtt_client.c Func:_mqtt_client_connect Line:885 Error: io_open failed
Error: Time:Wed Jan 18 15:17:59 2017 File:D:\gitroot\azure-iot-sdks\c\iothub_cli
ent\src\iothubtransport_mqtt_common.c Func:_SendMqttConnectMsg Line:1556 failure
 connecting to address xxx.azure-devices.net:0.
^^^^^^^^^^^^

## Resume network
In above logs, the last two error messages will  repeat for the network connection failure at the time DOWORK is called.
When network interface is enabled again, the DOWORK will try to send the message[0] again, and this time it suceeds.

**Log:**
^^^^^^^^^^^^
-> 15:19:39 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 192 | USERNAME: xxx.azure-devices.net/Device000/api-version=2016-11-14&DeviceClientType=iothu
bclient%2F1.1.0 | PWD: XXXX | CLEAN: 0
<- 15:19:39 CONNACK | SESSION_PRESENT: true | RETURN_CODE: 0x0
**ConnectionStatus Changed (status: 0, reason: 5)**
-> 15:19:46 SUBSCRIBE | PACKET_ID: 2 | TOPIC_NAME: devices/Device000/messages/de
vicebound/# | QOS: 1
-> 15:19:46 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | T
OPIC_NAME: devices/Device000/messages/events/PropName=PropMsg_0 | PACKET_ID: 3 |
 PAYLOAD_LEN: 46
<- 15:19:46 SUBACK | PACKET_ID: 2 | RETURN_CODE: 1
<- 15:19:46 PUBACK | PACKET_ID: 3
**Confirmation[0] received for message tracking id = 0 with result = IOTHUB_CLIENT
_CONFIRMATION_OK**
^^^^^^^^^^^^

## Disconnect network again

We set a user interaction point after a EventConfirmation callback is returned. This will help us to control the network condition. 

**Log:**
^^^^^^^^^^^^
INFO: press <ENTER> to send...
^^^^^^^^^^^^

When the program is waiting for a keypress from user, we'll again disable the network interface, and press <ENTER> to let program continue to send message[1].  By doing so, you'll see how the SDK reacting to a network disconnection when network condition is from connected to disconnected. Both ConnectionStatus callback and EventConfirmation callback are called, and SentEvent is aborted with error. Such behavior is different from the behavoir when network is not available from the start of the test program. 

**Log:**
^^^^^^^^^^^^
IoTHubClient_LL_SendEventAsync accepted message [1] for transmission to IoT Hub.

**ConnectionStatus Changed (status: 1, reason: 4)**
Error: Time:Wed Jan 18 15:23:24 2017 File:D:\gitroot\azure-iot-sdks\c\c-utility\
adapters\socketio_win32.c Func:_socketio_send Line:425 Failure: sending socket f
ailed 10054.
Error: Time:Wed Jan 18 15:23:24 2017 File:D:\gitroot\azure-iot-sdks\c\umqtt\src\
mqtt_client.c Func:_sendPacketItem Line:321 997: Failure sending control packet
data
Error: Time:Wed Jan 18 15:23:24 2017 File:D:\gitroot\azure-iot-sdks\c\umqtt\src\
mqtt_client.c Func:_mqtt_client_publish Line:936 Error: mqtt_client_publish send
 failed
**Confirmation[1] received for message tracking id = 1 with result = IOTHUB_CLIENT
_CONFIRMATION_ERROR**
^^^^^^^^^^^^

**Comment by yphuangms** [comment] 2017-01-18 13:57
In **iothubtransport_mqtt_command.c**

In IoTHubTransport_MQTT_Common_DoWork() calls to InitializeConnection().

In InitializeConnection(), if (!transport_data->isConnected) then calls to SendMqttConnectMsg().

In SendMqttConnectMsg() calls to mqtt_client_connect()

In mqtt_client_connect(), if fail to connect, NO IotHubClient_LL_ConnectionStatusCallBack will be called if connection failed.

The above call stack shows why a connection failure will never be reported if  "transport_data->isConnected == false". This is the factor that result in different behavior to the call to "IoTHubClient_LL_SendEventAsync()".

### Behavior 1:
If "SendEvent" is executed at the condition of "transport_data->isConnected == true", EventConfirmation callback will be called with an error report, and the **D2C message will be aborted and dropped**. In fact, all the messages in the queue will be aborted for they are processed within one DoWork() call. 

**The consecutive SendEvent calls will be executed in the next DoWork() cycle, the EventConfirmation callback behavior will become "Behavior 2".**

### Behavior 2:
If "SendEvent" is executed at the condition of "transport_data->isConnected == false", EventConfirmation  will never be invoked, a underlying connection retry will be run **until network resumed and connection being recovered the message will be sent to IoTHub, a EventConfirmation callback will be called with a "OK" report**.

**Comment by BertKleewein** [comment] 2017-01-19 00:26
Thanks.  I'm  working on a fix.

**Comment by BertKleewein** [comment] 2017-01-20 00:45
Regarding the connection status callback, I have a fix in  progress.  

Regarding the second issue: 
> So the message sent callback might have two different result in corresponding to network disconnection, one is callback with error, the other is no callback or a callback with timeout error.

It appears that we have a timing issue here.  Our SDK will queue messages if the network is not available.  We have a retry policy in place which will try to reconnect to the service with an exponential backoff.  If the SDK is not able to connect. it will retain the message in its queue until a connection can acquired or the timeout period expires.

The timing issue is that a network disconnection that happens in the middle of sending a message will cause a failure to be returned to the client.

In this way, you get an inconsistent behavior depending on the timing of the disconnect.  Most of the time, lack of a network connection will cause the message to be queued.  If you happen to hit a disconnect window, where the disconnection event takes place while the SDK is in the middle of sending a message, then that message will be aborted.  This is by design because the SDK only knows that a network error has taken place while sending the message.  It does not know what caused that error.  Since it's possible that the contents of the message caused the network error, it is better to return failure to the caller rather than re-queue the (possibly harmful) message and risk another network errror.

If you would like to introduce consistency by causing your messages to "fail quickly" when the network is not available, you should be able to set a short timeout as follows:
```
            tickcounter_ms_t timeout = 5000;
            IoTHubClient_LL_SetOption(iotHubClientHandle, "messageTimeout", &timeout);
```

If I understand your issues, I believe we have a solution on the way for your first problem.  Regarding the second problem, I hope I was able to provide sufficient explanation and maybe some workarounds.  It's also possible the fix for the first issue will help handle the second issue (though I was unable to prove this to myself).

I will respond again to this issue when I have the fix checked into the repo.  I will close the issue when the fix is released.

Please let me know if I misunderstood anything, if my explanation doesn't make sense, or if there's anything else I can do to help.

**Comment by BertKleewein** [comment] 2017-01-26 17:20
Fix is checked in.  Change was in azure-c-shared-utility submodule.  Submodule reference was updated [here](https://github.com/Azure/azure-iot-sdk-c/commit/7b075c31aae554df107938d5c3973ccc48253821)

**Comment by anporumb** [comment] 2017-01-30 19:22
Published.

**Closed by anporumb** 2017-01-30 19:22 UTC
Labels: bug, fix checked in
