### ISSUE TITLE
C++ compiler - extern C wraps templates inside cmath

### ISSUE THREAD

**Issue by kiranpradeep** [Azure/azure-iot-sdk-c#577] opened 2018-07-30 04:42 UTC
- **OS and version used:** macOS 10.13.4

- **SDK version used:** 1.2.8

# Description of the issue:
When including from C++ source, g++ compiler throws error: _templates must have C++ linkage__

# Code sample exhibiting the issue:

```
$: cat main.cpp
#include "iothub_client_ll.h"
int main() {
	return 0;
}
```

# Console log of the issue:

> xxxxxxxx:include xxxxx$ **g++ -c main.cpp -I azureiot/ -I azure_c_shared_utility/ -I .**
> In file included from main.cpp:1:
> In file included from azureiot/iothub_client_ll.h:37:
> In file included from azureiot/iothub_client_core_ll.h:31:
> In file included from azureiot/iothub_client_core_common.h:13:
> In file included from azureiot/iothub_message.h:13:
> In file included from ./azure_c_shared_utility/map.h:14:
> In file included from ./azure_c_shared_utility/crt_abstractions.h:13:
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:549:1: error: templates must have C++ linkage
> template <class _A1>
> ^~~~~~~~~~~~~~~~~~~~
> azureiot/iothub_client_ll.h:32:1: note: extern "C" language linkage specification begins here
> extern "C"

**Comment by jspaith** [comment] 2018-07-31 21:37
@kiranpradeep - thanks for calling this to our attention.

There's two issues I see here.  The first is that `map.h` ideally shouldn't be including `crt_abstractions.h` because this is getting us away from the API surface and getting us into internal utilities being exported out to the world.  `map.h` we need because of the (now deprecated) plumbing of the Map object to set properties.

We're going to look into whether we can decouple the header or not.  Also putting the `extern "C"` over everything is over-setting, so we'll look at scoping more, too.

**Comment by BigPeteB** [comment] 2018-08-02 18:08
Leaving aside any distinction between private and public headers, the root cause is definitely that C++ headers are being included from inside `extern "C"` blocks.

This is definitely a cross-platform issue, not just something that affects MacOS.

Pull request #584 created.

@kiranpradeep - I don't have a Mac handy, but on Windows I was able to reproduce this problem and fix several offending header files. You could try pulling #584 (as well as updating the `uamqp` subrepo from Azure/azure-uamqp-c#254) and see if this fixes the problem for you as well.

**Comment by jspaith** [comment] 2018-08-13 16:48
@BigPeteB's PR has addressed the C++ build issue (thank you!).  Closing this out as it impacted all platforms, but @kiranpradeep if you continue to hit issues please let us know.

**Comment by az-iot-builder-01** [comment] 2018-08-13 16:48
@kiranpradeep, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Closed** 2018-08-13 16:48 UTC
Labels: bug
