### ISSUE TITLE
CMake does not install provisioning client

### ISSUE THREAD

**Issue by zvrba** [Azure/azure-iot-sdk-c#408] opened 2018-03-11 16:09 UTC
I built the SDK with provisioning client with TPM HSM enabled. Everything builds successfully, but `cmake --build . --target install --config Release` installs only a subset of the built libraries and includes. This is for the latest release (2018-03-02).

**Comment by JetstreamRoySprowl** [comment] 2018-03-20 22:23
Hi @zvrba. This is by design. If you look [here in CMakeLists.txt] you'll see there are a ton of options for building. In order to build the prov client, you can add `-Duse_prov_client:bool=ON` to your cmake options.

**Comment by zvrba** [comment] 2018-03-21 06:27
Yes, this is related to #407 and I *did* add `-Duse_prov_client:BOOL=ON` to the command line. The provisioning client didn't get installed.

**Comment by JetstreamRoySprowl** [comment] 2018-03-21 17:56
@zvrba : Sorry, I arrived late to the party. Did your fix from #407 (thank you again) take care of this issue? If not, I can't repro from our current master so I must be missing something.

**Comment by zvrba** [comment] 2018-03-21 19:02
I didn't test with recent releases. With the fix for #407 I managed to build everything with the provisioning client turned on. With this fix, installation to the target prefix did _not_ install files, e.g., `azure_prov_client` includes did not get copied to `${INSTALL_PREFIX}/azure_prov_client`. Neither did `.lib` files.

**Comment by JetstreamRoySprowl** [comment] 2018-03-21 19:08
Cool. Will you please give me the exact command(s) you used so I can get a repro? I must be missing some context because your OP doesn't show the -Duse_prov_client, but later you say you included it.

**Comment by zvrba** [comment] 2018-03-22 07:36
This is what I did:

```
cmake -Duse_prov_client:BOOL=on -DCMAKE_INSTALL_PREFIX=/whatever/ ..
cmake --build . --target install --config Release
```

After fixing locally #407 both commands completed successfully. The second command installs most of the SDK but *not* the provisioning client headers and libraries.

**Comment by jspaith** [comment] 2018-03-22 16:00
I take it you're referring to

**Comment by jebrando** [comment] 2018-04-06 23:42
We believe this should be fixed in the latest master.  If you have any issues with this please reopen the issue.

**Closed by jebrando** 2018-04-06 23:42 UTC
Labels: enhancement

**Comment by yzhong94** [comment] 2018-04-12 18:51
@zvrba , thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V)

**Comment by TizianoFranzoi** [comment] 2019-08-13 08:52
I have a similar issue, while building azure - libs  1.3.0 with -Duse_prov_client:BOOL=on, 
It installs everything as expected but NOT the two libs: libutpm.a and  libmsr_riot.a 

I have to copy the the libs manually which is annoying.
