### ISSUE TITLE
[linux] Installation is broken

### ISSUE THREAD

**Issue by lmussier** [Azure/azure-iot-sdk-c#71] opened 2017-02-20 10:23 UTC
Hi,

We encounter a new issue with the install step of the SDK, here is what we do.

```
git clone --recursive https://github.com/Azure/azure-iot-sdk-c.git
./build.sh --install-path-prefix ~/azure_install
```

and finally 

`make install`
 from azure-iot-sdk-c/cmake/iotsdk_linux folder

```
[100%] Built target devicetwin_simplesample
Install the project...
-- Install configuration: ""
CMake Error at iothub_client/samples/iothub_client_sample_mqtt_dm/cmake_install.cmake:50 (file):
  file cannot create directory: /usr/share/iothub_client_sample.  Maybe need
  administrative privileges.
Call Stack (most recent call first):
  iothub_client/samples/cmake_install.cmake:43 (include)
  iothub_client/cmake_install.cmake:37 (include)
  cmake_install.cmake:41 (include)


Makefile:72: recipe for target 'install' failed
make: *** [install] Error 1
```
I've also try with --use-websocket, the websocket part is correctly installed but samples target the wrong folder.

```
Install the project...
-- Install configuration: "Debug"
-- Installing: /home/lmussier/workspace/build-agent/externals_install_folder/lib/pkgconfig/libwebsockets.pc
-- Installing: /home/lmussier/workspace/build-agent/externals_install_folder/lib/libwebsockets.a
-- Installing: /home/lmussier/workspace/build-agent/externals_install_folder/include/libwebsockets.h
-- Installing: /home/lmussier/workspace/build-agent/externals_install_folder/include/lws_config.h
-- Installing: /home/lmussier/workspace/build-agent/externals_install_folder/lib/libwebsockets.so.9
-- Installing: /home/lmussier/workspace/build-agent/externals_install_folder/lib/libwebsockets.so
-- Up-to-date: /home/lmussier/workspace/build-agent/externals_install_folder/include/libwebsockets.h
-- Up-to-date: /home/lmussier/workspace/build-agent/externals_install_folder/include/lws_config.h
-- Installing: /home/lmussier/workspace/build-agent/externals_install_folder/bin/libwebsockets-test-client
-- Installing: /home/lmussier/workspace/build-agent/externals_install_folder/bin/libwebsockets-test-server
-- Installing: /home/lmussier/workspace/build-agent/externals_install_folder/bin/libwebsockets-test-fuzxy
-- Installing: /home/lmussier/workspace/build-agent/externals_install_folder/bin/libwebsockets-test-server-pthreads
-- Installing: /home/lmussier/workspace/build-agent/externals_install_folder/bin/libwebsockets-test-server-extpoll
-- Up-to-date: /home/lmussier/workspace/build-agent/externals_install_folder/bin/libwebsockets-test-client
-- Installing: /home/lmussier/workspace/build-agent/externals_install_folder/bin/libwebsockets-test-fraggle
-- Installing: /home/lmussier/workspace/build-agent/externals_install_folder/bin/libwebsockets-test-ping
-- Installing: /home/lmussier/workspace/build-agent/externals_install_folder/bin/libwebsockets-test-echo
-- Installing: /home/lmussier/workspace/build-agent/externals_install_folder/share/libwebsockets-test-server/favicon.ico
-- Installing: /home/lmussier/workspace/build-agent/externals_install_folder/share/libwebsockets-test-server/leaf.jpg
-- Installing: /home/lmussier/workspace/build-agent/externals_install_folder/share/libwebsockets-test-server/libwebsockets.org-logo.png
-- Installing: /home/lmussier/workspace/build-agent/externals_install_folder/share/libwebsockets-test-server/lws-common.js
-- Installing: /home/lmussier/workspace/build-agent/externals_install_folder/share/libwebsockets-test-server/test.html
-- Installing: /home/lmussier/workspace/build-agent/externals_install_folder/share/libwebsockets-test-server/libwebsockets-test-server.key.pem
-- Installing: /home/lmussier/workspace/build-agent/externals_install_folder/share/libwebsockets-test-server/libwebsockets-test-server.pem
-- Installing: /home/lmussier/workspace/build-agent/externals_install_folder/share/libwebsockets-test-server/private/index.html
-- Installing: /home/lmussier/workspace/build-agent/externals_install_folder/lib/cmake/libwebsockets/LibwebsocketsConfig.cmake
-- Installing: /home/lmussier/workspace/build-agent/externals_install_folder/lib/cmake/libwebsockets/LibwebsocketsConfigVersion.cmake
-- Installing: /home/lmussier/workspace/build-agent/externals_install_folder/lib/cmake/libwebsockets/LibwebsocketsTargets.cmake
-- Installing: /home/lmussier/workspace/build-agent/externals_install_folder/lib/cmake/libwebsockets/LibwebsocketsTargets-debug.cmake
CMake Error at iothub_client/samples/iothub_client_sample_mqtt_dm/cmake_install.cmake:50 (file):
  file cannot create directory: /usr/share/iothub_client_sample.  Maybe need
  administrative privileges.
Call Stack (most recent call first):
  iothub_client/samples/cmake_install.cmake:43 (include)
  iothub_client/cmake_install.cmake:37 (include)
  cmake_install.cmake:41 (include)

```

**Comment by lmussier** [comment] 2017-02-20 10:49
Here is the offending part of the code :

azure-iot-sdk-c/iothub_client/samples/iothub_client_sample_mqtt_dm/CMakeLists.txt

```
if(UNIX)

    set(AZUREIOT_INC_FOLDER "pi_device" "../../../serializer/inc" "." "/usr/include/azureiot" "/usr/include/azureiot/inc")

    include_directories(${AZUREIOT_INC_FOLDER})

    set(iothub_client_sample_mqtt_dm_c_files
        iothub_client_sample_mqtt_dm.c
        pi_device/pi.c
    )
    set(iothub_client_sample_mqtt_dm_h_files
        iothub_client_sample_mqtt_dm.h
    )

    add_executable(iothub_client_sample_mqtt_dm ${iothub_client_sample_mqtt_dm_c_files} ${iothub_client_sample_mqtt_dm_h_files})

    target_link_libraries(iothub_client_sample_mqtt_dm
        iothub_client
        iothub_client_mqtt_transport
        serializer
        aziotsharedutil
        umqtt
        pthread
        curl
        m
    )

    set(iothub_install_files pi_device/iothub_client_sample_firmware_update.service .device_connection_string)

    install (TARGETS iothub_client_sample_mqtt_dm DESTINATION "/usr/share/iothub_client_sample")
    install (FILES ${iothub_install_files} DESTINATION "/usr/share/iothub_client_sample")

endif()  
```

This is the only sample that gets install properties, for my own usage I've temporary comment out the install part.

**Comment by anporumb** [comment] 2017-03-01 01:35
Hello @lmussier ,

We believe this is caused by not having sudo. The following part of your log makes me believe that: 

```
CMake Error at iothub_client/samples/iothub_client_sample_mqtt_dm/cmake_install.cmake:50 (file):
  file cannot create directory: /usr/share/iothub_client_sample.  Maybe need
  administrative privileges.
```

Can you please check if running the command with administrative privileges fixes your issue?

Thank you.

Best Regards,
Andrei Porumb

**Comment by lmussier** [comment] 2017-03-01 09:25
@anporumb I think you miss understood the issue, for sure running with sudo will allow files to be installed in /usr/share.
But the issue here is, the install prefix is ~/azure_install, and this prefix is not used by the sample.

**Comment by czyba** [comment] 2017-03-08 07:12
I ran into the same problem @lmussier described as well. I also worked around it by removing the install statements in the cmake file. I believe there are two possible ways to fix this for good:

1. If the sample should indeed be installed, it should be installed in the prefix
2. If the sample should NOT be installed, the two install statements should be removed or hidden by a flag. However even when you opt to hide them they should still respect the prefix on installation.

I think removing them is the consistent behavior, since the other samples are not installed either. I do not see why this sample should be the exception to the rule.

**Comment by anporumb** [comment] 2017-03-13 18:07
Hello,

We will look at this in March.

Best Regards,
Andrei Porumb

**Comment by MichaelDenczek** [comment] 2017-03-15 17:55
Recreated issue on Ubuntu.  Install fails...

**Comment by ewertons** [comment] 2017-03-15 20:00
Hi @MichaelDenczek , we are currently looking at the issue.
We will post an update soon. 
Thanks.

**Comment by ewertons** [comment] 2017-03-17 21:12
Hi @lmussier and @MichaelDenczek , a change has been checked in master for this issue.

However, due to recent changes you will not be able to install the solution in one call like the way you posted above. Here are the steps I followed to get the libraries and headers installed to a custom location (yes, unfortunately the commands need to be run for each library in separate, and in this order):

```
cd /azure-iot-sdk-c/c-utility  

mkdir cmake
cd cmake/
cmake -Duse_installed_dependencies=ON -DCMAKE_INSTALL_PREFIX=~/azure_install ..
make -j `nproc`
make install

cd /azure-iot-sdk-c/uamqp
mkdir cmake
cd cmake/
cmake -Duse_installed_dependencies=ON -DCMAKE_INSTALL_PREFIX=~/azure_install ..
make -j `nproc`
make install

cd /azure-iot-sdk-c/umqtt

mkdir cmake
cd cmake/
cmake -Duse_installed_dependencies=ON -DCMAKE_INSTALL_PREFIX=~/azure_install ..
make -j `nproc`
make install

cd /azure-iot-sdk-c

mkdir cmake
cd cmake/
cmake -Duse_installed_dependencies=ON -DCMAKE_INSTALL_PREFIX=~/azure_install ..
make -j `nproc`
make install
```

**Comment by ewertons** [comment] 2017-03-17 21:14
The fix is in change de9bbe145df775c1c0179cbedf039edd5f2fbed2

**Comment by ewertons** [comment] 2017-03-17 21:14
Upon checking ~/azure_install, you should see:

ewertons@5021b97d5d23:/azure-iot-sdk-c/cmake$ ll ~/azure_install/
total 20
drwxrwxr-x 5 ewertons ewertons 4096 Mar 17 20:35 ./
drwxr-xr-x 5 ewertons ewertons 4096 Mar 17 20:35 ../
drwxrwxr-x 2 ewertons ewertons 4096 Mar 17 20:38 cmake/
drwxrwxr-x 3 ewertons ewertons 4096 Mar 17 20:35 include/
drwxrwxr-x 2 ewertons ewertons 4096 Mar 17 20:38 lib/
ewertons@5021b97d5d23:/azure-iot-sdk-c/cmake$ ll ~/azure_install/lib/
total 2348
drwxrwxr-x 2 ewertons ewertons   4096 Mar 17 20:38 ./
drwxrwxr-x 5 ewertons ewertons   4096 Mar 17 20:35 ../
-rw-r--r-- 1 ewertons ewertons 336752 Mar 17 20:34 libaziotsharedutil.a
-rw-r--r-- 1 ewertons ewertons  57502 Mar 17 20:37 libiothub_client.a
-rw-r--r-- 1 ewertons ewertons 396962 Mar 17 20:37 libiothub_client_amqp_transport.a
-rw-r--r-- 1 ewertons ewertons 226224 Mar 17 20:37 libiothub_client_http_transport.a
-rw-r--r-- 1 ewertons ewertons 240556 Mar 17 20:37 libiothub_client_mqtt_transport.a
-rw-r--r-- 1 ewertons ewertons 236746 Mar 17 20:37 libiothub_service_client.a
-rw-r--r-- 1 ewertons ewertons 394086 Mar 17 20:37 libserializer.a
-rw-r--r-- 1 ewertons ewertons 431924 Mar 17 20:36 libuamqp.a
-rw-r--r-- 1 ewertons ewertons  54036 Mar 17 20:36 libumqtt.a
ewertons@5021b97d5d23:/azure-iot-sdk-c/cmake$

**Comment by ewertons** [comment] 2017-03-17 21:18
Thanks for reporting this problem.
Please let us know if you have any further comments or suggestions.
This issue will be closed, but feel free to reopen it if you need.

**Closed by ewertons** 2017-03-17 21:18 UTC
Labels: help wanted
