### ISSUE TITLE
Azure SDK disconnecting/reconnecting with reason: NO_NETWORK

### ISSUE THREAD

**Issue by byang321** [Azure/azure-iot-sdk-c#2406] opened 2022-11-24 01:12 UTC
Hi,

I have a device experiencing sudden and unexpected IOTHUB_CLIENT_CONNECTION_NO_NETWORK.
We disconnect the device and then try again and immediately succeed on reconnection. This then loops for 20 minutes, with a disconnect again in less than 5 seconds.

Nov 09 23:03:57 connStatusCbf(), L211: The device client has been disconnected, result = IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED, reason = IOTHUB_CLIENT_CONNECTION_NO_NETWORK
Nov 09 23:04:01 connStatusCbf(), L200: The device client is connected to iothub, reason = IOTHUB_CLIENT_CONNECTION_OK
Nov 09 23:04:02 connStatusCbf(), L211: The device client has been disconnected, result = IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED, reason = IOTHUB_CLIENT_CONNECTION_NO_NETWORK
Nov 09 23:04:06 connStatusCbf(), L200: The device client is connected to iothub, reason = IOTHUB_CLIENT_CONNECTION_OK
Nov 09 23:04:07 connStatusCbf(), L211: The device client has been disconnected, result = IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED, reason = IOTHUB_CLIENT_CONNECTION_NO_NETWORK

On a NO_NETWORK in the SDK logging I expected to see a set of MQTT failures: 
"Error: io_open failed", 
"Error: failure sending connect packet", 
"Error: failure opening connection to endpoint"

The Retry policy used is
IoTHubClient_SetRetryPolicy( m_iotClientHdl, IOTHUB_CLIENT_RETRY_EXPONENTIAL_BACKOFF_WITH_JITTER, 20);

Why would a device experience no_network, with no Error logs, but immediately succeed upon reconnection? Thanks

**Comment by ericwol-msft** [comment] 2022-11-28 20:03
You would need to share out the SDK logs for better context of what is going on. But yes, the "io_open failed" is that your device can not connect (socket failure) to the IoT service end-point. There are numerous reasons that this can happen, including DNS resolution issues.

**Comment by byang321** [comment] 2022-11-29 23:54
Hi, sorry for the confusion. I did not see an "io_open failed" error log, or any of the other errors. 

The above logs are all that occurred on a device that had already established a connection with the IoT service, and then with none of the expected error logs, started experiencing connection disconnects with reason NO_NETWORK.

Let me know if that cleared my question up.

**Comment by ericwol-msft** [comment] 2022-11-30 00:24
you can enable verbose SDK logs by setting the following options

        bool traceOn = true;
        IoTHubDeviceClient_LL_SetOption(device_ll_handle, OPTION_LOG_TRACE, &traceOn);

**Comment by byang321** [comment] 2022-11-30 00:46
I have logs enabled, and I have seen the expected errors on other devices with the same code. 

Example Logs on another device:
Nov 13 21:58:09 Error: Time:Sun Nov 13 21:58:08 2022 File:/usr/src/debug/azure-umqtt-c/1.1.10-r0/git/src/mqtt_client.c Func:mqtt_client_connect Line:1000 Error: io_open failed
Nov 13 21:58:09 Error: Time:Sun Nov 13 21:58:08 2022 File:/usr/src/debug/azure-iot-sdk-c/1.2.10-r0/git/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:2122 failure connecting to address 
Nov 13 21:58:09 Error: Time:Sun Nov 13 21:58:09 2022 File:/usr/src/debug/azure-c-shared-utility/1.1.10-r0/git/adapters/socketio_berkeley.c Func:lookup_address_and_initiate_socket_connection Line:282 Failure: getaddrinfo failure -3.
Nov 13 21:58:09 Error: Time:Sun Nov 13 21:58:09 2022 File:/usr/src/debug/azure-c-shared-utility/1.1.10-r0/git/adapters/socketio_berkeley.c Func:socketio_open Line:765 lookup_address_and_connect_socket failed
Nov 13 21:58:09 Error: Time:Sun Nov 13 21:58:09 2022 File:/usr/src/debug/azure-c-shared-utility/1.1.10-r0/git/adapters/tlsio_openssl.c Func:on_underlying_io_open_complete Line:760 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Nov 13 21:58:09 Error: Time:Sun Nov 13 21:58:09 2022 File:/usr/src/debug/azure-c-shared-utility/1.1.10-r0/git/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1258 Failed opening the underlying I/O.
Nov 13 21:58:09 Error: Time:Sun Nov 13 21:58:09 2022 File:/<4>/usr/src/debug/asp/2.1.0-r0/git/iotmgmt/azure_iot_ctrl.cpp, connStatusCbf(), L211: The device client has been disconnected, result = IOTHUB_CLIENT_CONNECTION_UNAUTHENTICATED, reason = IOTHUB_CLIENT_CONNECTION_NO_NETWORK

**Comment by ericwol-msft** [comment] 2022-11-30 01:16
None of this log exists in the current SDK. It looks like your SDK version is at least 6 years old. Please move to the latest LTS version so that we can support you.

**Comment by domasgim** [comment] 2022-12-20 06:15
I have experienced a similar issue, I would get a `NO_NETWORK` reason right after `IOTHUB_CLIENT_CONNECTION_OK`, I haven't managed to reproduce it every time and the SDK version is about 3 years old so I'm assuming its because of the outdated SDK.

**Comment by ericwol-msft** [comment] 2023-01-04 22:25
You can only have one device connected to the hub. If another device connects with the same device ID, the other device will be disconnected. Two devices connected that have the same hub device ID, will ping back and forth kicking the other device off of the hub.

**Comment by byang321** [comment] 2023-01-09 18:32
We ended up looking at the IotHub disconnect logs and found hundreds of InternalServerError's in one particular device instead of the ConnectionForcefullyClosedOnNewConnection Eric described above. 

While our outdated SDK still applies, would this be a IotHub issue that needs to be looked at?
![0adbc25f-a345-448e-85f5-74e8357c2993](https://user-images.githubusercontent.com/118946695/211381377-57dee39a-6706-4350-869f-7c80e3eb4e93.jpg)

**Comment by ericwol-msft** [comment] 2023-01-09 21:58
Yes, this is a Azure IoT Hub service issue. Please create a Support Request from the Azure portal and work with a support engineer on your issue. Thanks.

**Comment by ericwol-msft** [comment] 2023-01-19 01:20
I'm closing this issue. Please feel free to reopen if you have any further information.

**Closed by ericwol-msft** 2023-01-19 01:20 UTC
Labels: question, IoTSDK
