### ISSUE TITLE
IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY does not seems to be called upon desctruction

### ISSUE THREAD

**Issue by lmussier** [Azure/azure-iot-sdk-c#54] opened 2017-02-01 16:20 UTC
Hi,

Running our application UT after switching from 2016-09-09 to  2017-01-27 (sorry for this big gap :s), one of our test fails. This test send a lot of messages and destroys the iothub handle immediately. The previous behavior was that the confirmation callback was called with IOTHUB_CLIENT_CONFIRMATION_BECAUSE_DESTROY as confirmation status.

Now, on 2016-09-09 we don't see this call, the callback is not called anymore.

**Comment by anporumb** [comment] 2017-02-01 19:19
Hello @lmussier ,

What protocol are you using? What's the SHA of the code you have seen the BECAUSE_DESTROY not getting called?

That will help us in reproing.

Thank you.

Best Regards,
Andrei Porumb

**Comment by mm-mhr** [comment] 2017-02-01 20:34
I am experiencing (probably) the same issue after switching to 2017-01-27 release.
To be more precise:
The confirmation callback is not (always) called when calling IoTHubClient_Destroy.
I created a minimum example (attached) which demonstrates the issue.
Confirmation callback is "sometimes" called when I play with the debugger stepping throu the code. In release build it was never called in my minimum example so far.
[test.zip](https://github.com/Azure/azure-iot-sdk-c/files/746077/test.zip)

**Comment by lmussier** [comment] 2017-02-02 11:12
@anporumb MQTT and tag  2017-01-27 (sorry for the typo above..)

**Comment by anporumb** [comment] 2017-02-02 22:35
Hello @lmussier , @mm-mhr ,

This is what I did to reproduce the issue:
1) git checkout 440f7f446c63fee91f6e89cde38b17c4f341b406. This is the master HEAD commit at the time I am writing this.
2) did the necessary things to have a new "sample" that compiles test.cpp
3) I have used Windows (Visual Studio) and I have commented out some things from the source code. Nothing crucial. Also changed slightly the message printed in `SendConfirmationCallback`
4) I have introduced a variable sleep before `IoTHubClient_Destroy(iotHubClientHandle);`
5) I have then used different sleep periods to see the effect of delaying `IoTHubClient_Destroy(iotHubClientHandle);`
6) I have run the program 100 times (a batch file took care of that)

These are my data:

| sleep (ms)       |     SUCCESS                | BECAUSE_DESTROY         |  no message   |
|------------------|----------------------------|-------------------------|---------------|
|  1               | 0                          | 0                       |       100     |
|  10              | 0                          | 0                       |       100     |
| 100              | 0                          | 1                       |      99       |
| 125              | 0                          | 0                       |      100      |
| 125              | 0                          | 0                       |      100      |
| 150              | 100                        | 0                       |      0        |
| 200              | 100                        | 0                       |      0        |
| 1000             | 100                        | 0                       |      0        |

The SDK is not supposed to EVER lose messages (callbacks are always invoked). This is not what is happening. 

This is bug.

Thank you for your report.

Best Regards,
Andrei Porumb

**Comment by anporumb** [comment] 2017-02-03 15:46
Hello @lmussier , @mm-mhr,

I have checked in a fix (with tests) for the problem at hand. We had a regression when we've introduced not-holding-a-lock callbacks (still working on those for C2D messages).

Would be great if you could let me know if this fixes your scenario.

Best Regards,
Andrei Porumb

**Comment by lmussier** [comment] 2017-02-06 08:22
@anporumb I've checked with 3d6041d6c6e328d58c8449087f12a4310353d243, it works for me.
Thanks.

**Comment by mm-mhr** [comment] 2017-02-09 13:28
I cloned master c861ec3f26a7ff4debedf6dbb916072cec1be768 from 2017-02-09.
It works for me. Thank you.

**Closed** 2017-02-13 19:07 UTC
Labels: fix checked in
